### ISSUE TITLE
Possibilité de publier une recherche d'emploie

### ISSUE THREAD

**Issue by DrTableBasse** [NotANameServer/discord#103]
Bonjour à vous,

C'est la période où la plus part des étudiants recherches un emploie en alternance ou bien un CDD / CDI. Beaucoup savent, dans mon cas, que je recherche sans relâche. Donc je me disais qu'après avoir eu un salon proposition d'offres, il serait, selon moi, judicieux d'avoir un salon pour dire que l'on recherche un emploie... Bien sûr cela demandera une rigueur accrue de la part des utilisateurs. C'est à dire modifier le message quand il y a du changement mais aussi de la part des modérateurs qui devront filtrer les trolls. Mais je m'inquiète pas sur ça. 

Je sais que le serveur n'est pas forcément prévu à cet effet mais pourquoi pas j'ai envie de dire. 

En espérant que cette idée plaise à certains !

**Comment by Kakktuss** [comment]
Je suis tout à fait d'accord avec cette proposition, je suis aussi activement en recherche d'un nouvel emploi et un chan dans l'style pourrait pas mal à aider, si des recruteurs/dévs dans des boîtes se baladent sur NaN.

**Comment by Nolent** [comment]
Vu le peu de post dans #offre, je vois mal pourquoi un chan #demande sera pertinent.

**Comment by DrTableBasse** [comment]
> Vu le peu de post dans #offre, je vois mal pourquoi un chan #demande sera pertinent.

Ca peut toujours intéresser. NaN est un endroit composé en majeure parti de professionnels de l'informatique. Donc ça peut toujours être utile. Et puis imaginons un salarié se balade, il pourrait très bien faire remonter ça aux RH par exemple. Sait-on jamais jais envie de dire !

**Comment by Nolent** [comment]
Il peut très bien faire remonter qu'il peu poster une offre, je vois pas ce qui change dans le process

**Comment by DrTableBasse** [comment]
> Il peut très bien faire remonter qu'il peu poster une offre, je vois pas ce qui change dans le process

ça se fait souvent aussi quand il y a pas d'offres juste un "oh ben ça serait cool un alternant" dans le cas de ben et moi par exemple. Dans le cas de CDI / Cdd je suis d'accord avec toi aussi.

**Comment by Elanis** [comment]
Je comprends beaucoup ici en aient besoin, particulierement pour les stages/alternances. 
Mais:
- J'ai un peu peur de la modération qu'on va devoir gérer pour ce sujet, ca va probablement finir comme #offres, message sur ticket
- Je ne suis pas sûr que beaucoup de recruteurs vont être présents pour lire ce channel, la population pro du serveur n'est pas majoritaire, et la population pro capable de prendre des stagiaires/alternants l'est encore moins je pense.

**Comment by Julien00859** [comment]
Alors je vais être un connard mais... normalement discord ça sert pas à recruter ni à être recruté... #offre existe surtout pour pouvoir être ignoré et pour qu'on puisse dégager ceux qui font du recrutement sauvage. Pour reprendre un message qui est passé sur discord, NaN c'est pas pole-emploi.

Je pense que si on crée un tel salon, ça va juste être un melting-pot où tout le monde viendra poser son CV, déjà qu'on a des demandes pour #offre plusieurs fois par semaine, j'ose pas imaginer la charge de travail que ce sera de filtrer tous les CV...

**Comment by DrTableBasse** [comment]
En soit, ce que je disais à Rem en vocal, je préfère le remettre ici, si il y a un besoin de modération d'un salon comme ça, je peux me porter volontaire. Je pense que vous avez déjà assez de taff avec tout le serveur !
