### ISSUE TITLE
Chan tooling 

### ISSUE THREAD

**Issue by arkena00** [NotANameServer/discord#104]
Salut moi c'est Arkena

Je propose un chan tooling pour tout ce qui est lié à la programmation et qui n'a pas de place ailleurs. Et pour éviter que ce soit trop le bordel, utiliser des fils par tools ou catégorie de tool
Un truc du style : 
# tooling
- vcs
- build system
- ide
- jardinage

**Comment by Elanis** [comment]
Comme discuté plus tôt dans d'autres issues ou channels, il y a en effet pas assez de messages pour un canal pour un sujet en tant que tel (sinon c'est fourre-tout et on a #discussions pour ca :) ).
En revanche, je trouve l'idée d'un channel qui serait un repère de thread de sujets peu discuté une bonne idée. Faudra discuter pour les sujets en eux mêmes mais je trouve que ca peut être une bonne idée.

**Comment by Julien00859** [comment]
Je rejoins l'avis d'Elanis, on a pas vraiment besoin "d'isoler" ces discussions comme elles ne pullulent pas trop, cependant avoir un salon général où toute la connaissance pour le vcs/ci/cd serait regroupé permettrait de ne plus fragmenter la connaissance dans de multiples salons.

**Comment by DrTableBasse** [comment]
Ce qu'on peut faire à la place de passer par un salon, on peut très bien mettre un onglet sur Not a Hub. Ce sera plus simple d'y accéder et au moins on pourra fournir des exemples et avoir un visuel plus simple que sur discord

**Comment by Elanis** [comment]
Pour le coup c'est plus que de la doc, c'est vraiment de la résolution de problématiques, comme dans les channels standard.

**Comment by Julien00859** [comment]
Il faudra aussi inclure docker dans ce salon, et peut-être l'appeler devops

**Comment by Elanis** [comment]
+1 pour le nom

**Comment by florentm35** [comment]
A mon avis "devops" est un peu trop restrictif pour tout les sujets que doit adresser le chanel

**Comment by M0NsTeRRR** [comment]
J'ai l'impression que ça fait doublon avec systeme-et-reseau sauf pour la partie IDE et vcs (qui pour moi à sa place dans autres-langages). Parce que si le build, docker c'est pas du système, ça veut dire que tout ce qui va être ansible, packer, terraform etc... ça va aller là bas.
Le canal est loin d'être surchargé je vois pas trop l'intérêt d'en rajouter un pour des technos spécifiques à du système.

**Comment by Julien00859** [comment]
renommer le salon en "system-et-reseau-et-devops" alors :D

**Comment by Julien00859** [comment]
Je me permets de réouvrir le débat, il y a une grosse différence entre poser une question git parce qu'on a foiré ses commits ou ses branches et poser une question git dans le cadre de ci/cd.

Pour ce qui est dans un cadre de ci/cd, oui clairement synet
Mais pour le dev qui a flingué son repo, on est sur que sysnet est le bon endroit ?

Typiquement aujourd'hui il y a eu deux questions git, 
* https://discord.com/channels/323076998576603137/389160027857879051/1112394394658668544
* https://discord.com/channels/323076998576603137/553130821603819530/1112360186800255106
on ne peut pas vraiment dire qu'elles sont à leur place...

*Still more questions about git than about lua :upside_down_face:*

**Comment by DrTableBasse** [comment]
en soit, faudrait (ré)ouvrir un salon git quitte à ce que ça fasse doublon avec d'autres salons car je suis du même avis que julien. Ça dépend vraiment le cas et rediriger trente fois une personne c'est pas ouf

**Comment by Equinox4** [comment]
hello
Il n'y a clairement pas suffisamment de questions concernant git pour que cela nécessite un salon dédié. Il est vrai que selon le type de question, le salon systeme/reseaux n'est pas forcément adapté mais je pense qu'il est préférable de rediriger tout le monde au même endroit plutôt que de split entre différents canaux.

**Comment by DrTableBasse** [comment]
Alors pas un salon mais un thread dédié à ça

**Comment by Julien00859** [comment]
Un thread ce serait quand même vachement planqué

**Comment by Elanis** [comment]
Comme je disais hier, pour les 3 questions git qui se battent en duel dans le mois, ca me semble inutile de créer un salon. #systeme-et-reseau n'est pas le meilleur choix, mais il est ok.

**Comment by Equinox4** [comment]
le thread il va se faire archiver tellement que le nombre de questions est faible

**Comment by DrTableBasse** [comment]
Je sais plus si on peut dire à un thread de ne pas s'archiver 🤔

**Comment by Elanis** [comment]
Il se masque automatiquement sous une semaine d'inactivite (ou moins si moins est paramétré). Et un thread ca sera clairement invisible imo

**Comment by Julien00859** [comment]
Merci pour vos retours, on reste donc dans sysnet :)
