### ISSUE TITLE
Supprimer les canaux texte des salons vocaux

### ISSUE THREAD

**Issue by Nolent** [NotANameServer/discord#106]
Maintenant que les salons vocaux ont leur propre canaux texte (cliquer sur la bulle en haut a droite quand on est en vocal, ou clic droit sur le chan -> ouvrir la discussion), il ne me parait pas utile de garder les canaux #vocal-jeux , #vocal-talks et #vocal-sans-micro

**Comment by Julien00859** [comment]
Accéder à ces salons demande d'être présent dans le salon vocal pour accéder au salon textuel, niveau modération (surveillance passive) c'est pas génial génial. On doit aussi s'assurer que NaB soit présent dans ces salons, ne serait-ce que pour :modo:. Après c'est un problème de modo ça, on peut (=va devoir) s'adapter.

**Comment by DrTableBasse** [comment]
Surtout que là c'est qu'une béta. Je pense qu'il faudrait s'y attarder quand ce sera sorti pour tout le monde.

**Comment by Elanis** [comment]
> Accéder à ces salons demande d'être présent dans le salon vocal pour accéder au salon textuel, niveau modération (surveillance passive) c'est pas génial génial. On doit aussi s'assurer que NaB soit présent dans ces salons, ne serait-ce que pour :modo:. Après c'est un problème de modo ça, on peut (=va devoir) s'adapter.

On peut les lire sans être présent en vocal, mais sinon, d'accord pour le reste

**Comment by SirLynix** [comment]
Je garde l'issue ouverte tant que NaB ne pourra pas agir sur ces canaux.

**Comment by Elanis** [comment]
Not a Bot est capable d'écouter les canaux liés aux salons vocaux, la suggestion a donc été appliquée ;)
