### ISSUE TITLE
Création d'un canal veille technos 

### ISSUE THREAD

**Issue by DrTableBasse** [NotANameServer/discord#109]
Je pense qu'il serait intéressant d'avoir un salon où serait regrouper des sites pour se documenter un peu sur ce qu'il se fait dans le monde de l'informatique. Un peu comme le site https://www.usine-digitale.fr/

Je prends en exemple le serveur discord de Ben qui regroupe énormément de news sur différents sujets. Ca pourrait être intéressant.

**Comment by Elanis** [comment]
Je ne sais plus où on s'était dit ca, je retrouve plus l'issue donc ca doit être sur le serveur. Mais un canal veille n'est pas trop compatible avec la largeur en terme de sujets du serveur. Ca serait assez souvent des news qui ne concernent pas le lecteur et/ou un spam de news.
On en était venu à la conclusion qu'il vallait mieux que les gens s'abonnent d'eux même à des flux externes à NaN plutôt que de faire un canal fourre-tout sur NaN que (presque) personne allait lire.

**Comment by DrTableBasse** [comment]
C'est vrai que dit comme ça, autant faire une liste qui sortirait les sites que nous recommandons dans ce cas là. Ce sera sans doute plus pertinent

**Comment by Julien00859** [comment]
Il y a déjà un partage de liens dans les différents salons lorsque quelque chose d'intéressant apparait en ligne. Quand il n'y a aucun salon qui n'est dans le même thème qu'un article alors ça fallback sur #discussions et c'est très bien :)
