### ISSUE TITLE
Création d'un canal "Tooling"

### ISSUE THREAD

**Issue by florentm35** [NotANameServer/discord#111]
Il y a de plus en plus de question liée au tooling des projets (docker/git/CI/...), sujets qui on tendance à débordé sur les canaux #discution, #systeme-et-reseau et #architecture-dev qui ne sont pas à la base pas fait pour.

A voir si l'on restreint le canal à quelque thématique précise, ou bien si le canal doit être au tooling en générale (en passant par les IDE par exemple)

**Comment by GiregL** [comment]
Arkena avait déjà ouvert une issue sur le sujet du tooling:

https://github.com/NotANameServer/discord/issues/104

**Comment by Julien00859** [comment]
Duplicat
