### ISSUE TITLE
Création d'un chanel pour "l'embarqué"

### ISSUE THREAD

**Issue by van3ll0pe** [NotANameServer/discord#112]
En fait je me suis mis à l'embarqué et je vois très peu de tuto, cours sur internet ( sites, youtube, etc) que ce soit en anglais comme en français. C'est un domaine assez vaste puisque ça parle programmation comme électronique et sur le fonctionnement de puces. Je me suis dit que si un canal existait ça simplifierait et aiderait les personnes sur des problèmes en rapport avec l'embarqué.

**Comment by Equinox4** [comment]
hello, sur le serveur la création d'un nouveau canal se fait lorsque beaucoup de discussions sur un sujet ont lieu et que la nécessité de les séparer se fait sentir, c'est un peu l'offre et la demande, tant que les discussions sur tel sujet sont rares/ne prennent pas de place, il n'y a pas lieu de créer un canal dédié.
Il ne me semble pas avoir vu tant de questions que ça concernant l'embarqué dernièrement, donc il est peu probable qu'un canal soit créé pour ça, à voir si d'autres peuvent confirmer/infirmer cette observation.

**Comment by Karomy404** [comment]
"l'embarqué" pour moi c'est du système et du réseau ^^ 
Mais plus spécialisé comme "Android" par exemple, et comme vous l'avez tout les 2 dit, c'est un domaine de niche avec une plus petite commu et moins d'activité. Et on a la besoins de crée un channel quand il y a trop d'activité au mauvais endroit.
Donc ça répond pas vraiment au besoins en l'occurrence imo.

**Comment by Elanis** [comment]
Hello, en effet comme l'a si bien dit Mjö, on evite de créer des channels pour qu'ils aient un message tous les 2 mois. Je ne vois quasi jamais de questions sur de l'embarqué aussi, donc pas vraiment de raison de créer ce channel imo
