### ISSUE TITLE
Ajout de l'émoji Nan Army

### ISSUE THREAD

**Issue by antoinechauvn** [NotANameServer/discord#113]
![Sans titre (7)](https://user-images.githubusercontent.com/83721477/183079889-14b798ff-1cac-4f4d-ae3f-c824d5cbbb07.png)

**Comment by Julien00859** [comment]
Je trouve que les logos langages sont de trop. Aussi NaN sur le drapeau n'est pas correctement aligné avec le "mat" et ne suit pas la courbure du drapeau. Sinon j'aime beaucoup le concept :)

**Comment by Nolent** [comment]
C'est vrai que devoir changer l'émoji a chaque ajout/retrait de canal ca risque d'être chiant (même si on en a rarement).
Si jamais on les gardes, je trouve que le logo python est pas assez mis en avant, je le trouverais pas mal en gros sur la casquette :kappa:

**Comment by Superkooka** [comment]
C'est vrai que les logos proposé sont de trop, voici ma proposition
<img width="414" alt="nan" src="https://user-images.githubusercontent.com/35631093/183100599-a220c92e-3d86-4afc-8183-ac32b1eb06d1.png">
