### ISSUE TITLE
Le salon #manufacture-de-création-de-langage accessible que pour ceux qui ont le role  adapte

### ISSUE THREAD

**Issue by antoineB24** [NotANameServer/discord#116]
Bonjour, je me permet de crée cette issue  pour faire remarquer que le salon  #manufacture-de-création-de-langage est accessible pour tous le monde. Or tous le monde (sur ce serveur) ne veut pas cree un langage , alors ils reçoivent des messages sur un sujet qui ne l'interessent pas . La solution serai de faire comme pour #bots-discord, #system-et-reseau , ... 
c'est a dire de cree un role pour ce salon et le rendre accessible que par ce role

**Comment by pauloud** [comment]
J'ai pas compris si tu parlais de mentions non-désirées, ou si tu parlais pour ceux qui ont des notifs à chaque message ?
En tout cas l'avoir mis visible par tous jusqu'à présent aura parmi aux "anciens" de voir qu'il existait, c'est déjà ça.

**Comment by Elanis** [comment]
La suggestion concerne le fait de passer le canal derrière un rôle à prendre dans #rejoindre-les-canaux, pour éviter que le canal soit présent par defaut

**Comment by pauloud** [comment]
La suggestion je l'ai comprise, c'est l'argument qui me laissait perplexe

**Comment by SirLynix** [comment]
C'est prévu, il faut juste que je prenne le temps de le faire. 😅

**Comment by Elanis** [comment]
Je viens d'effectuer la modif, le canal a maintenant un rôle dedié
