### ISSUE TITLE
Créer un canal présentation

### ISSUE THREAD

**Issue by pauloud** [NotANameServer/discord#120]
Faire comme sur le serveur du twitch de Lynix en gros, ça permettrait de renforcer la dimension communautaire en permettant à chacun de présenter ses centres d'intérêts plus longuement et d'apparaitre plus sympatique aux yeux des autres, ou de parler éventuellement de son boulot/parcours pour être ping lorsque la discussion s'y prête.

**Comment by Elanis** [comment]
Sur un serveur de 12k personne, imo, ca va être un canal jamais lu, où tout le monde ira soit de sa pub, soit d'informations que personne ne lira jamais (ou s'en foutera).

Je vois pas l'utilité perso

**Comment by pauloud** [comment]
Effectivement un tel salon ouvert à tous serait spammé de pub
