### ISSUE TITLE
Renommer #etudes en un nom plus clair

### ISSUE THREAD

**Issue by Iltotore** [NotANameServer/discord#121]
Nous avons sur le Discord le salon `#etudes`, plutôt actif.

Mais assez régulièrement, certaines personnes se trompent sur sa fonction, pensant qu'il s'agit également d'un salon d'aide aux devoirs. L'exemple le plus récent étant: https://discord.com/channels/323076998576603137/405326955458592770/1016075062572486818

De ce que j'ai vu, il n'y a effectivement que la petite description du salon pour indiquer la véritable nature du `#etudes`:
> Des interrogations sur votre parcours scolaire ? C'est par ici !

Je propose anisi de renommer le `#etudes` en `#orientation` pour éviter toute ambiguïté et de détailler sa description.

**Comment by Elanis** [comment]
Appliqué par @WubiCookie hier soir
