### ISSUE TITLE
Rajouter un lien vers le bouton de création des tickets

### ISSUE THREAD

**Issue by florentm35** [NotANameServer/discord#122]
Mettre à jour la guideline "Contacter le staff" pour rajouter un lien vers le bouton de création de ticket, voir si on peux pas carrément intégrer le bouton à l'embeded facilement (mais j'y crois moyen)

**Comment by Karomy404** [comment]
Le bouton est dans #regles

**Comment by AllanBlanchard** [comment]
Oui mais il y a des gens qui ne savent pas scroll.
