### ISSUE TITLE
Remplacer #autres-langages par un salon forum

### ISSUE THREAD

**Issue by Nolent** [NotANameServer/discord#126]
Salut, je pense que cela peut être une bonne idée de remplacer le salon #autres-langages par un salon forum.
Cela permet a tout un chacun de créer un post pour leur langage. Ceux-ci sont automatiquement rendu inactif si personne ne parle jamais dedans, et les langages qui restent actif un certain temps pourraient être ajouté a la liste des canaux permanents.
Il reste a voir le comportement des bots dans ces post.

**Comment by Elanis** [comment]
Lynix a ajouté le support de NaB pour les forums hier justement, mais par contre, Discord n'a toujours pas bien conçu ce trucs. Y'a pas toutes les notifs de nouveaux messages, et le design est toujours pété sur certains écrans :/
![image](https://user-images.githubusercontent.com/7013446/195546564-f0af2a11-fabf-4281-9b6b-d16f79e38e62.png)

**Comment by Karomy404** [comment]
C'est ton Discord que tu réduit de moitié qui est pété ^^
Et si, tu as les notifs, si tu rejoins le poste. Come pour un fil

**Comment by Nolent** [comment]
Les admins ont besoin d'avoir des notifs sur tout les posts pour pouvoir surveiller

**Comment by Elanis** [comment]
Je vis en permanence (comme beaucoup de monde) avec un discord en half screen, faut atteindre les 2/3 d'écran pour que ca soit moins pété.
Et pour les notifs, ouai, la modération va être chiante si on peut pas passivement surveiller

**Comment by Karomy404** [comment]
Il suffit donc de rejoindre tout les postes forum, comme c'est déjà le cas avec les fils.

**Comment by Elanis** [comment]
Ouai, sauf qu'on a pas toujours des notifs pour la création de posts non plus

**Comment by Karomy404** [comment]
Pour ce forum, je propose de n'autoriser que le STAFF a ouvrir un nouveau poste sinon ?
Vous faites la création des postes des langages les plus parler dans ce salon, puis vous en rajouter si besoins sur demande avec le temps ?

**Comment by Nolent** [comment]
Dans ce cas ça change pas le système de canaux actuel. Avec par exemple Go qui a été ajouté puis supprimé par manque de message

**Comment by Ben-4444** [comment]
Si car la c'est une gestion de fils par plus récent. Et au bout de x temps défini le poste passe en "fermer" mais est toujours afficher et peut être réouvert (si le droit est donné) comme les fils

**Comment by SirLynix** [comment]
On pourrait aussi imaginer un module de NaB qui invite automatiquement le staff dans un fil, mais la seule façon que je connais de faire ça c'est de ping le staff, et j'en connais quelques uns qui vont pas aimer d'être ping à chaque création de fil.

Si on avait un moyen de faire ça sans notification ça serait très cool.

**Comment by SirLynix** [comment]
Littéralement vingt secondes après : https://discord.com/developers/docs/resources/channel#add-thread-member

**Comment by Elanis** [comment]
Ca pourrait être une solution oui, à voir si ca pete pas comme a une époque ou un thread sur deux s'affichait pas.
Et aussi, ca serait bien qu'ils fix l'UI, je maintiens

**Comment by zazbone** [comment]
Yop,


Plutôt qu'un poste par langage je verrais bien un poste par question (Indiquer la tech dans la question évidemment).
Ça éviterait d'avoir deux questions dans un salon `go` ou deux salons qui s'appellent "J'ai un problème en go".

Mais d'une manière générale l'idée est top, c'est 100 fois mieux que les files

**Comment by Ben-4444** [comment]
J'aime bien l'idée d'un poste par problèmes. ça se rapprocherais mieux d'un vrais forum en plus.

**Comment by Julien00859** [comment]
Sous réserve que je suis bien invité automatiquement sans ping dans l'ensemble de ces salons et que j'ai aussi moyen de les rendre muet facilement, je trouve également qu'utiliser le forum pour #autre-langage est une super idée.

**Comment by Elanis** [comment]
FYI, j'ai ouvert un rapport de bug côté Discord pour leur UI pétée, vu qu'ils viennent d'annoncer les forums dans les changelogs. Ils doivent considérer ca stable (mais visiblement sans avoir tout testé).

**Comment by Elanis** [comment]
Après un combat par mail assez exténuant, mon bug a été escalate, en attente d'une résolution ou de nouvelles :smile:

**Comment by Elanis** [comment]
Nouvelle du support discord, c'est un comportement voulu, ils veulent pas fix leur reponsive pété a moins d'un feedback assez voté, que j'ai donc créé: https://support.discord.com/hc/en-us/community/posts/10094303933079-Fix-broken-responsive-UI-on-Forum-layout

**Comment by florentm35** [comment]
Mais du coup c'est juste a cause de l'ui ou bien juste car il y a des dev à faire coté NaB ? (Car bon si c'est juste l'ui qui est pété en demi-écran, ça va juste embêter une personne, c'est pas la mort)

**Comment by Elanis** [comment]
Les deux.
Perso, ca me donne 0 envie d'utiliser ce type de canal avec cette UI pétée af, mais je ferais avec si je suis minoritaire de cet avis. Mais sans le bot dont on a parlé plus haut, c'est sûr qu'on mettra pas en place.

**Comment by Julien00859** [comment]
On a créé le forum :) On le laisse quelques temps pour essayer et puis on avisera.

**Comment by Elanis** [comment]
Experience que j'ai effectué ce matin, j'ai quitté un des canaux, il y a 5 nouveau messages dans un des threads, mais non visible dans le menu lateral (même pas le forum en surligné) et très discret dans le forum en lui même ...
![image](https://user-images.githubusercontent.com/7013446/202851058-12dcad66-51ea-42bc-a4c9-4b3b9f7b5841.png)
![image](https://user-images.githubusercontent.com/7013446/202851165-a545d7a5-6b91-4c85-b64c-e933c44f225a.png)

**Comment by Elanis** [comment]
De retour avec mon propre retour, je trouve que #autres-langages version forum n'est pas très pratique, je m'explique:
Les gens parfois posent des questions dans les threads mais ... hormis la modération presque personne n'est sur ce thread, donc personne ne voit la notif, donc personne ne réponds.
Parlant de modération, j'ai du rejoindre manuellement un par un les threads, pas hyper pratique non plus.

J'ajouterai, on s'est pris sur plusieurs jours des gens qui ont créé des threads pour des langages existants (soit en canal, soit en thread).

**Comment by florentm35** [comment]
Personnellement, je vais être honnête je ne vois pas l’intérêt du forum dans le format choisis dans autres-langages, ça ressemble juste a des canaux classique en plus bordélique, ne serait-il pas mieux d’avoir un post par problème/question avec dans le titre le nom du langage ?

**Comment by Elanis** [comment]
Ca serait moins pire en notifs (on serait notifié d'une question), mais hyper bordelique je pense parce que tout le monde va créer son post à la suite de l'autre. Imo, le canal de type forum est une mauvaise idée pour ce sujet tout court

**Comment by Nolent** [comment]
> Les gens parfois posent des questions dans les threads mais ... hormis la modération presque personne n'est sur ce thread, donc personne ne voit la notif, donc personne ne réponds.

Je pense pas que cela soit très différent du channel classique, je suis pas certain que beaucoup de monde passe du temps dans le chan autre langage. Puis la en regardant je vois que dans Go et Dart ça cause pas mal. IMO c'est surtout que les gens ne sont pas compétent dans ces langages / ne les connaissent pas (qui connaît Pony a par Prae ?). 
Par contre pour la modération je veux bien croire que ce soit relou. Et ça ne me choquerai pas de couper un peu en fonctionnalité pour faciliter la vie des modo

**Comment by Elanis** [comment]
> Je pense pas que cela soit très différent du channel classique, je suis pas certain que beaucoup de monde passe du temps dans le chan autre langage.

C'est toujours beaucoup plus que les 3 pégus (dont 2 staff) qui ont rejoint le canal.

**Comment by Elanis** [comment]
Pour ce qui est de l'activité, les plus actifs ont été Go et Bash, qui ont eu une question toutes les quelques jours. Contre une vingtaine d'autres threads qui ont été pour la plupart soit vides, soit sans réponse, soit avec 3 messages qui se battent en duel

**Comment by Julien00859** [comment]
btw ya ça mais je ne sais pas à quoi ça sert

![image](https://user-images.githubusercontent.com/8208953/206684109-192738d7-4ceb-4105-a76b-453e3d1451bf.png)

**Comment by Elanis** [comment]
C'est un équivalent à l'archivage côté thread iirc. Ca n'affiche plus le thread dans la liste des canaux. Par contre, contrairement aux threads standards, il semblerait qu'on puisse toujours les mentionner

**Comment by Nolent** [comment]
J'en vois avec des messages qui ont plus d'une semaine. 
Je sais pas si vous avez des chans que je vois pas. Mais pour moi on est pas a la vingtaine de chan (12 chan au total), dont 3 qui ont plus de 50 messages (bash, powershell, go). Perso ça me semblait évident qu'on aurait des chan vides avec des questions sans réponse depuis le début (comme ça arrive fréquemment dans le chan classique).

En revanche je maintiens que si c'est pour une facilité de modération, je vois rien a redire quand au retour au chan classique.

**Comment by Elanis** [comment]
> J'en vois avec des messages qui ont plus d'une semaine.

Dans la liste du forum on les voit oui, mais dans la liste des threads sur le côté (avec les autres canaux), ils disparaissent :)

**Comment by Julien00859** [comment]
Perso je suis d'avis d'arrêter l'expérience aussi, maintenant, la semaine pro ou dans un mois perso jmef, les forums c'est naze. Ce qui a été intéressant a été de déterminer quels étaient les salons avec de l'activité, je propose de créer un véritable salon pour ces langages :)

Tous les autres => corbeille et retour à #autre-langage classique

**Comment by florentm35** [comment]
Pour Bash et Powershell, ça me paraitrais pas déconannt de les rerouter dans #system-et-reseaux

**Comment by Julien00859** [comment]
Intéressant à remonter aussi
![image](https://user-images.githubusercontent.com/8208953/206761954-47a84de9-6a45-45c1-bd67-3c5218f0ebaa.png)

**Comment by Elanis** [comment]
Je suis d'accord yes.
Une semaine de plus et pas d'amélioration pour ce canal forum, je pense qu'on va pouvoir planter les derniers clous du cercueil.
Je vais passer le forum en read-only et re-passer le canal original en write autorisé. (Et faire un petit post pour expliquer dans le forum)

**Comment by zazbone** [comment]
Je ne suis pas trop d'accord pour mélanger les salons de langage.
Pour js/ts et le salon jvm, je donne ma langue au chat, ceux qui y touchent un peu savent sans doute mieux.
Mais pour mélanger julia et python, je ne vois pas trop l'intérêt ; Premièrement Python est bien assez actif (et les threads c'est chiant). Ensuite les deux langages ne sont pas du tout les mêmes à part certain use case similaire, auquel cas pourquoi pas mettre R ou go, ruby pour le côté serveur…
Je suis pour un maintien du système actuel, avec des salons de langages pour les plus communs et des salons système, réseau, game dev pour les questions plus techniques.
Dans le cas de julia vu le nombre de questions autres langages est suffisant, et pour ce qui touche aux data sciences pourquoi pas en discuter dans une autre issue même si je ne suis pas très convaincu

**Comment by Elanis** [comment]
Canal supprimé
