### ISSUE TITLE
Ajouter de la visibilité à la commande !vocal

### ISSUE THREAD

**Issue by florentm35** [NotANameServer/discord#129]
Modifier la guideline "L'aide en message privé " pour rajouter en plus de !mp la commande !vocal qui au final expose les mêmes points

**Comment by Julien00859** [comment]
Je suis d'accord sur le principe, je vais proposer une PR

**Comment by Julien00859** [comment]
Il existe en fait déjà un paragraphe quant à l'aide en vocal, étrangement ce paragraphe n'apparait pas sur discord...

https://github.com/NotANameServer/discord/blob/d4fc78eb2ae9ecff29328e996607675d1b8604c3/guidelines.md?plain=1#L27-L29

![image](https://user-images.githubusercontent.com/8208953/204622706-8128df92-7281-4191-9086-79fb1a88cdc5.png)


cc @Elanis

**Comment by Elanis** [comment]
Côté discord, la commande, j'ai:

```
Not a Name ne met pas en avant les demandes d'aide en vocal. En effet, les informations transmises en vocal ne sont qu'éphémères, alors qu'une information écrite dans le canal approprié peut être réutilisée plus tard et par d'autres personnes. 
De plus, nos membres aidant sur leur temps libre, il est plus facile pour eux de suivre une conversation écrite. 
Ainsi, nous vous demandons de poser vos questions dans les canaux appropriés ( rejoindre-les-canaux )
```


Y'a une inconsistance en effet 😄

**Comment by Julien00859** [comment]
Ya une erreur dans mon script, je vais corriger ça https://gist.github.com/Julien00859/828d8a24e6cb29bec54c240245a00a18#file-guidelines-py-L33-L40
