### ISSUE TITLE
Not a Rule Book

### ISSUE THREAD

**Issue by Julien00859** [NotANameServer/discord#13]
A des fins de documentation, je mets ici un lien vers le draft d'un nouveau règlement que nous avions commencé avec @GiregL https://pad.drlazor.be/s/_yXPqHuwr#

**Comment by x0rld** [comment]
le channel #suggestions est plus d'actualité au final

**Comment by GiregL** [comment]
Pour tout le monde,
Un dilemme s'offre a nous. Nous hésitons à fusionner la section #faq dans le Rule Book
On se tourne donc vers les membres du serveur, réagissez avec:
- 👍 fusion complète, le canal #faq disparait et les points abordés sont intégrés dans Not a Rule Book
- 👎 aucune fusion, le canal #faq reste à sa place. Certains points peuvent néanmoins être abordés dans Not a Rule Book, mais ces derniers restent minoritaires
- 🤷‍♂️ une fusion partielle à lieu. Les points les plus importants sont importés dans Not a Rule Book et la #faq reste à sa place

**Comment by GuillaumeBelz** [comment]
Le Not a Rule Book sera accessible comment via le discord ?

**Comment by GiregL** [comment]
Ce sera probablement le canal #règles mis à jour directement, du moins c'est ce qu'on prévoyais à ce moment

**Comment by GuillaumeBelz** [comment]
du coup, si le book et #faq ne sont pas fusionné, il y a doublon des regles sur le discord, dans 2 canaux différents ?

**Comment by GiregL** [comment]
La faq restera telle qu'elle est aujourd'hui, sans lien avec les règles
Les règles reprendront quelques points de la faq, mais seulement, dans son canal, il n'y aurait de doublon que pour ces points là

**Comment by GuillaumeBelz** [comment]
Ok. Je suis pas fan d'avoir 2 canaux pour les "regles", donc je suis pour la fusion. Merci pour les reponses.

**Comment by GiregL** [comment]
De toute façon on fera surement une proposition en pull-request de la config de ces deux canaux, en fonction du résultat du sondage. A ce moment, on pourra choisir quoi appliquer.

**Comment by Elanis** [comment]
> Pour tout le monde,
> Un dilemme s'offre a nous. Nous hésitons à fusionner la section #faq dans le Rule Book
> On se tourne donc vers les membres du serveur, réagissez avec:
> 
> * 👍 fusion complète, le canal #faq disparait et les points abordés sont intégrés dans Not a Rule Book
> * 👎 aucune fusion, le canal #faq reste à sa place. Certains points peuvent néanmoins être abordés dans Not a Rule Book, mais ces derniers restent minoritaires
> * 😕 une fusion partielle à lieu. Les points les plus importants sont importés dans Not a Rule Book et la #faq reste à sa place

Personellement, je pense que faire disparaitre "#faq" et tout mettre sur Github est une mauvaise idée. Les nouveaux ne vont jamais aller lire le markdown sur Github imho.

**Comment by SirLynix** [comment]
Je pense que la seule façon d'avoir un maximum de gens qui vont lire le règlement est que celui-ci soit clair, concis et surtout court.
Avoir un document plus complet sur le GH dont un lien serait posté sur le Discord pourrait être une bonne idée, mais abandonner le canal #règles actuel est, selon moi, une bêtise.

**Comment by GiregL** [comment]
> Personellement, je pense que faire disparaitre "#faq" et tout mettre sur Github est une mauvaise idée. Les nouveaux ne vont jamais aller lire le markdown sur Github imho.

Tout ne sera pas uniquement sur Github, les règles seront toujours sur le serveur, juste plus complètes

> Je pense que la seule façon d'avoir un maximum de gens qui vont lire le règlement est que celui-ci soit clair, concis et surtout court.
> Avoir un document plus complet sur le GH dont un lien serait posté sur le Discord pourrait être une bonne idée, mais abandonner le canal #règles actuel est, selon moi, une bêtise.

On a pensé le Rule Book pour être en plusieurs parties, dont une, au début, composée des règles principales, relativement concises et suffisamment précises pour ne pas laisser court à de mauvaises interprétations. Je t'invite à donner un avis sur cette partie d'ailleurs.
Les autres parties sont orientées sur les moeurs de la communauté, le contact du staff, les canaux particuliers (#vos-projets et compagnie)
Avoir un canal de règles long n'influe pas, selon moi, la "longueur des règles".

**Comment by SirLynix** [comment]
> Tout ne sera pas uniquement sur Github, les règles seront toujours sur le serveur, juste plus complètes

C'est en fait tout le problème.

>  Avoir un canal de règles long n'influe pas, selon moi, la "longueur des règles".

Un nouveau venu sur le serveur va cliquer sur le canal #regles, voir qu'il fait trois kilomètres de long et ne jamais le lire une seule seconde. Un bon canal de règle est clair et concis, et rares sont les membres prêts à lire quelque chose d'aussi long.  
L'intérêt du rule book, ou de la FAQ actuelle est selon moi pour les membres qui ont décidé de vraiment rester et de s'intéresser au serveur, là où les nouveaux venus ne liront que les règles.

D'autant plus que quand tu cliques sur un canal sur Discord, tu n'arrives pas au début mais à la fin de celui-ci.

**Comment by zazbone** [comment]
> L'intérêt du rule book, ou de la FAQ actuelle est selon moi pour les membres qui ont décidé de vraiment rester et de s'intéresser au serveur, là où les nouveaux venus ne liront que les règles.

Surtout si les commandes comme !code !ask et autres sont maintenues.

C'est beaucoup plus pratique de référer à un point spécifique du reglement avec les commandes plutot qu'en renvoyant juste sur la faq.
Que l'ensemble des détails des règles soit compilé quelque part est utile mais restera moin utile que les commandes

**Comment by GiregL** [comment]
> D'autant plus que quand tu cliques sur un canal sur Discord, tu n'arrives pas au début mais à la fin de celui-ci.

J'oublais ce détail, du coup je rejoins un peu ton point de vue.

> C'est en fait tout le problème.

Le duplicata des règles poserais problème ?

> (edit: quand je dis "les règles" je pense à un format plus court encore que celui existant aujourd'hui).

Dans ce cas je proposerais limite de faire les règles en 5 a 7 mots-clés (a trouver). Tout en ayant un lien direct vers le Rule Book complet.

**Comment by SirLynix** [comment]
> Le duplicata des règles poserais problème ?
C'est le fait de remplacer le canal actuel court et concis (et on peut faire mieux) par un pavé que personne ne lira plus précisément le problème.  
À vouloir faire trop complet on dégoûte simplement tout le monde de la lecture, et plus personne ne le lit.  
Et autant on peut reprocher à un nouveau venu de ne pas avoir pris deux minutes pour lire une dizaine de lignes de règlement, autant on peut difficilement lui reprocher pour quelque chose d'aussi gros que le rule book.

**Comment by Julien00859** [comment]
Je lis bien, la première section du rule book (intitulé *règlement*) reprend et reformule les quelques règles élémentaires de NaN, on pourrait ne garder *que* cette catégorie dans le salon #regle et laisser le reste dans la FAQ.

**Comment by florentm35** [comment]
Il pourrait être intéressant de rajouter un petit message sur les ping a outrance, car autant la majorité des membres n'en abuse pas mais certain sont assez chiant a ping n'importe quand si tu les as aider une fois des fois si tu a juste répondu a quelqu'un autre, apres soit un message dans la faq ou bien une regle sanctionnable (ou au moins qui calme les gens même s'il y a pas de sanction derriere), ça permetrait d'atténuer l'effet d'impression d'être pris pour un SAV

**Comment by Julien00859** [comment]
Il faudrait ajouter un lien vers la charte de discord aussi https://discord.com/guidelines
