### ISSUE TITLE
Creer des forum pour les canal sur les langages de programmation

### ISSUE THREAD

**Issue by antoineB24** [NotANameServer/discord#131]
Bonjour, je pense que vue les demandes d'aide venant des utilisateurs discord sur ce serveur sont nombreux, je me demandais si cela ne serait pas plus pratique de créé une section forum et une section canal (pour garder comme même les canaux), il y a plusieurs questions qui ont été ignore (sans faire exprès bien sur) alors qu'avec un forum la question ne sera pas ignoré. 

Niveau moderation, je n'ai pas encore regarde comment cela se pouvait se faire mais je pense qu'avec un flag le sujet sera bien signale, donc il faut compter sur les utilisateurs du forum pour signaler ou alors vous essayer de moderer vous meme ce qui est plutot dur 

Franchement, je trouve que l'idee du forum est une bonne idee  (j'ai vue qu'il a une issue pour remplacer le canal autre langage en forum #126 ) bon apres, le cote negative est la moderation mais je pense qu'on peut trouver une solution

**Comment by Elanis** [comment]
L'idée n'a pas vraiment eu de traction de la part de la communauté, je ferme du coup
