### ISSUE TITLE
un Advent of Code pour NaN

### ISSUE THREAD

**Issue by antoineB24** [NotANameServer/discord#136]
Ce serait bien de créer un advent of code  pour NaN, (pour ceux qui ne connaissent pas : https://adventofcode.com/ )  chaque jour de l'avent il y a un probleme (d'algo souvent) de plus en plus dure. Ce serait cool de cree un defi pour l'advent of code

**Comment by Elanis** [comment]
Justement, je faisais l'annonce pour l'evenement dans #defis :smile:
