### ISSUE TITLE
Rendre le serveur très restrictif pour les personnes sans rôle

### ISSUE THREAD

**Issue by Elanis** [NotANameServer/discord#138]
Actuellement, voici les canaux accessibles pour une personne sans rôle:

![image](https://user-images.githubusercontent.com/7013446/208083267-b83363c2-79ca-46d3-b6bf-2c1364730b3e.png)

Que pensez vous du fait de complètement bloquer l'accès à tous les canaux aux personnes sans rôle ?
Ou bien de bloquer plus de canaux qu'auparavant ?

Nous avons expérimenté cette idée dans #autres-langages version forum sans trop de soucis (cf. #126 ), il y avait même moins de digressions que sur la version textuelle.

**Comment by Julien00859** [comment]
Ils ne devraient voir sur les 4 salons "importants" avec "Lisez-moi" en prime

**Comment by antoineB24** [comment]
je pense déjà que le salon lisez-moi doit avoir un bouton qui indique qu'on a lue  qui va ensuite débloquer juste la categorie generale.

Ensuite, je pense qu'il faut aussi mettre la catégorie, lisez-moi   plus visible, (quand on est nouveau dans le serveur, on le voit pas très bien)

**Comment by Equinox4** [comment]
peut être qu'en cachant #discussion, ça incitera les gens à ne plus poser leur question dedans

**Comment by Equinox4** [comment]
#bienvenue faut peut être le garder pour qu'ils continuent d'être mentionnés

**Comment by x0rld** [comment]
> peut être qu'en cachant #discussion, ça incitera les gens à ne plus poser leur question dedans lorsqu'il viennent de rejoindre le serveur

#detente aussi ducoup

**Comment by Elanis** [comment]
Appliqué sur:
- Vocal Général
- Deuxième canal vocal
- #screenshots    
- #questions-professionelles

Voici ceux qui restent pour le moment:
![image](https://user-images.githubusercontent.com/7013446/210167810-0bdc48f6-7a6c-4e41-a3c5-e1199b6a19a8.png)
![image](https://user-images.githubusercontent.com/7013446/210167825-7583983d-d3b2-4a23-a8ed-d60920448ee2.png)

Je referais une second vague de "privatisation" des canaux plus tard, on va voir comment ca se comporte avec ceux-ci.

**Comment by Elanis** [comment]
Dans la continuité de ce sujet, j'ai une proposition à faire, passer la configuration de sécurité à "Elevé":
![image](https://user-images.githubusercontent.com/7013446/214248639-1d13ecf6-0776-4a9b-9268-ae8449771046.png)

Cela impliquera qu'il faut être présent depuis 10 minutes OU d'avoir choisi un canal afin de discuter.
Qu'en pensez vous ?

**Comment by SirLynix** [comment]
La raison pour laquelle on avait pas activé ça c'est parce que tu ne peux pas faire d'action sur le serveur pendant ces dix minutes, y compris cliquer sur des emojis pour débloquer des canaux (du coup ça bloquait tout le monde dix minutes inutilement).

À voir si c'est pareil avec le nouveau système.

**Comment by Elanis** [comment]
![image](https://user-images.githubusercontent.com/7013446/214304387-bf4852e9-4ad5-4763-bdcd-095974a6eccc.png)
C'est bloqué :/

**Comment by Elanis** [comment]
Incompatible avec le choix de #151, je clos
