### ISSUE TITLE
Interdire l'utilisation de GPT pour repondre 

### ISSUE THREAD

**Issue by andrelec1** [NotANameServer/discord#140]
Beaucoup "trop" de personne qui ne maitrise pas forcement la/les techno, reponde avec des screen de la question copier/coller dans GPT ...

Cela n'apport generalement aucune aide, et les reponse contienne du code qui ne fonctionne pas / ou qui n'est pas contextualisé ! 

Pourrait-on simplement bannir ce genre de comportement ?

**Comment by Julien00859** [comment]
On s'était amusé à faire répondre GPT à des questions venant de l'ancien test technique de ma société. Le bot n'a pas été capable de pondre du code valide, il n'a pas non plus été capable de correctement corriger ses erreurs quand on les lui a pointé. Il n'a pas non plus compris la solution lorsqu'on la lui a présentée.

Dès qu'on sort des patterns très bien définis des questions type stackoverflow ou bien du code bien documenté qui a été volé des projets sur github, dès qu'il s'agit d'être *réellement créatif* et d'innover, ce bot devient bien bête. À préciser aussi que tout n'est pas à garder ni de stackoverflow ni du code des programmes existant...

Je ne doute pas un instant qu'un jour une IA arrivera à écrire du bon code. Heureusement pour mon salaire, ce jour n'est visiblement pas encore arriver.

Une guideline va très vite arriver...

**Comment by Elanis** [comment]
Sans interdire l'utilisation de GPT tout court (il y a des discussions assez interessantes sur le sujet, ainsi que des exemples interessants dans le thread dedié), l'interdire pour répondre aux questions techniques est une bonne idée je pense oui

**Comment by SirMishaa** [comment]
Je pense qu'on devrait scooper à "Interdire GPT" pour répondre à des demandes questions code spécifiquement

GPT est (je trouve) bien plus doué sur les questions plus générales, exemple : 

**Est-ce qu'un développeur JavaScript devrait utiliser jQuery de nos jours ?** 

> Il n'y a pas de réponse unique à cette question, car cela dépend de vos préférences personnelles et de l'environnement de développement dans lequel vous travaillez. jQuery est une bibliothèque JavaScript populaire qui a été largement utilisée pour simplifier l'écriture de code JavaScript en fournissant des fonctionnalités de haut niveau pour effectuer des opérations courantes, telles que la manipulation du DOM, la gestion des événements et les requêtes AJAX. Cependant, avec l'évolution de JavaScript et la maturation des navigateurs, il est maintenant possible de réaliser la plupart de ces tâches sans utiliser jQuery, en utilisant du code JavaScript vanilla ou en utilisant d'autres bibliothèques ou frameworks.

> Il y a plusieurs raisons pour lesquelles un développeur JavaScript pourrait décider de ne pas utiliser jQuery :

> Premièrement, le code vanilla (c'est-à-dire le code JavaScript pur sans l'aide de bibliothèques ou de frameworks) peut souvent être plus rapide et plus léger que le code utilisant jQuery, car il ne nécessite pas le chargement d'une bibliothèque supplémentaire.

> Deuxièmement, les fonctionnalités de JavaScript natif sont souvent plus simples à utiliser et plus faciles à comprendre pour les développeurs qui apprennent JavaScript, car elles sont plus proches de la syntaxe de base de JavaScript.

> Enfin, de nombreux frameworks modernes, tels que React et Angular, ont leur propre manière de manipuler le DOM et de gérer les événements, ce qui peut rendre l'utilisation de jQuery inutile ou même contre-productive dans ces environnements.

> Cela étant dit, jQuery reste une bibliothèque populaire et largement utilisée, et il y a de nombreuses situations où elle peut être utile. Si vous êtes à l'aise avec sa syntaxe et que vous avez déjà une expérience de travail avec elle, il n'y a pas de raison de ne pas l'utiliser si vous le souhaitez. En fin de compte, la décision de l'utiliser ou non dépend de vos préférences personnelles et de l'environnement de développement dans lequel vous travaillez.

Dans cet exemple précis, c'est une réponse tout à fait valide, et je pense que balancer ça à un débutant sera plus utile que de lui envoyer un article. L'importance ça va surtout être de vérifier ce qui est produit par GPT. 

Pour le code par contre, je suis d'accord qu'il vaut mieux interdire son utilisation pour des réponses pour l'instant.

**Comment by SirLynix** [comment]
ChatGPT balance souvent des conneries au milieu de vraies réponses, avec le même ton d'expertise et c'est pour moi un gros problème. Je suis pour l'interdiction de son utilisation pour les réponses (d'autant plus que ça n'a aucun intérêt de copier-coller la réponse de ChatGPT sur Discord quand quelqu'un pose une question)

**Comment by REMqb** [comment]
Je pense qu'on peut accepter cette proposition et la mettre en application.

**Comment by Julien00859** [comment]
ChatGPT est banni sur stackoverflow

https://meta.stackoverflow.com/questions/421831/temporary-policy-chatgpt-is-banned

**Comment by Equinox4** [comment]
> The primary problem is that while the answers which ChatGPT produces have a high rate of being incorrect, they typically look like they might be good and the answers are very easy to produce. There are also many people trying out ChatGPT to create answers, without the expertise or willingness to verify that the answer is correct prior to posting.
c'est la conclusion à laquelle on était parvenu sur NaN, à l'origine de cette issue, il semblerait que la meilleurs chose à faire pour le moment soit en effet d'interdire les réponses générées par GPT dans les canaux technique.
