### ISSUE TITLE
Changement du nom du salon #bot-discord

### ISSUE THREAD

**Issue by CallMePixelMan** [NotANameServer/discord#141]
Bonsoir tout le monde, 
ma demande peut paraître un peu futile au premier abord, mais il s'avère que certaines personnes confondent parfois le salon `#bot-discord` avec le salon `#commandes-bots` sur le serveur. Rien de grave bien sûr, mais je trouve (et je ne pense pas être le seul) cela dérangeant. Autant pour l'auteur des commandes, qui se retrouve confus dans le mauvaise salon; que pour les gens investis dans l'aide dans ce salon qui retrouve des notifications pour autre chose que des demandes d'aide.

Ainsi; je propose de changer le nom du salon en quelque chose de plus expressif afin d'éviter les futures confusions. Je suggère les noms suivants : `#dev-bot-discord` ou `#creation-bot-discord`.

Merci d'avance, bonne soirée !

**Comment by Elanis** [comment]
Hello,

Je comprends le besoin, mais je ne suis pas sûr que ce soit totalement utile.
J'ai scroll sur plus d'un mois, je n'ai vu aucune erreur dans le genre (hormis celle de 3P hier soir).

C'est un canal derrière un rôle, donc ca diminue la proportion d'erreur de manière massive (vu que si tu le vois, c'est que tu sais qu'il existe un canal dedié au dev de bots).

Aussi, sachant que ca ne concerne pas que le developpement, mais aussi l'hebergement et l'API discord, j'aurais du mal à trouver un terme assez générique pour ne pas se retrouver avec des gens qui exflitrent leurs questions vers d'autres canaux.

A voir ce qu'en pensent les autres

**Comment by CallMePixelMan** [comment]
Re,

Bien que cela n'arrive pas tous les jours, c'est quelque chose d'assez récurant qu'on peut apercevoir de temps en temps, et c'est surtout une sorte de spam dans le salon car les gens vont généralement dans le salon `#commandes-bots` pour expérimenter avec le bot.

Même si le salon est derrière un rôle, les erreurs sont encore là et je pense que la quantité de travail nécessaire pour simplement changer le nom du salon est ridicule pour avoir quelque chose de plus explicite. 

Voici quelques exemples récents, bien sûr, je ne leur jette pas la pierre, mais je constate que la confusion inattentionnelle est là, et donc qu'il y à tout de même matière d'effectuer ce si petit changement. 
https://discord.com/channels/323076998576603137/539809627987247135/1055273846594355300
https://discord.com/channels/323076998576603137/539809627987247135/1054826328727224361
https://discord.com/channels/323076998576603137/539809627987247135/1034528043361894500

Pour ce qui du nom du salon, je ne pense pas que `#creation-bot-discord` change vraiment quelque chose au concept, et englobe complètement le fait de travailler avec l’hébergement. Personnellement, étant presque tout le temps dans ce salon, je peux vous dire que l'on a relativement peu de questions relatives à l'API directement (on travaille presque exclusivement sous wrapper).

**Comment by Elanis** [comment]
En effet, my bad, j'ai pas vu ces messages, j'ai scroll trop vite 😄

**Comment by CallMePixelMan** [comment]
Up!

Des nouvelles ?

**Comment by Elanis** [comment]
Hello, on a appliqué le renommage, le canal s'appelle maintenant #création-bots-discord
