### ISSUE TITLE
Renommer #c => #c-lang (ou autre idc)

### ISSUE THREAD

**Issue by Julien00859** [NotANameServer/discord#145]
Parce que discord c'est de la merde et que quand j'écris

> Il faudrait que tu décores ta fonction avec `@classmethod`

mais que j'oublie de mettre la balise code, je ping tous ceux qui ont le rôle c.

C'est déjà arrivé au moins 3x depuis que je suis staffeux...

Puis puis ya aussi qu'il est trigger à chaque fois qu'il y a `#c` au début d'un mot... <#1031780330815893594>iant...

**Comment by jonathanpoelen** [comment]
`#llvm` est plus large que seulement clang...

En fait, clang est le nom d'un compilateur C/C++. Pour éviter des ambiguïtés, `#c-langage` serait mieux. En plus, ça utilise la même nomenclature qu'`autres-langages`.

**Comment by Equinox4** [comment]
`#c-langage` ça me semble bien, `#llvm` personne va comprendre à par les experimentés

**Comment by SirLynix** [comment]
#llvm n'a aucun rapport particulier avec le C, `clang` est un nom de compilateur C et C++ très courant donc `#c-lang` perso je suis pas chaud, `#c-langage` me semble en effet bien plus indiqué (s'il faut vraiment changer ça, ce qui me parait un peu plus discutable 😛 )

**Comment by Elanis** [comment]
Appliqué
