### ISSUE TITLE
Fermer les salons vocaux

### ISSUE THREAD

**Issue by Julien00859** [NotANameServer/discord#146]
L'aide en vocal est interdite sur NaN, il n'y a aucune activité (défi/club-de-lecture) qui justifie de se réunir et plus globalement ces salons sont très souvent vide. Je propose de les fermer jusqu'à nouvel ordre.

Ne plus avoir de salon vocal sonnerait aussi le gla de tous ceux qui demandent de l'aide en vocal. Il sera facile de leur répondre "il n'y a pas de salon vocal sur NaN" en plus du "mes MP sont fermés". Plus aucune excuse pour transgresser le règlement quant à l'aide en mp/vocal. Moins de travail aussi pour la modération comme on n'a pas de log pour ces salons.

Pour ce qui est des quelques membres qui vont quelques fois en vocal, tant pis pour eux. La plupart de ces membres ne sont pas actif sur les salons textuels et n'ont pas grand chose à faire là de toute manière. Les quelques membres actifs (je pense à Mishaa, Kaktus et Lord 3P) devront aller ailleurs.

**Comment by Equinox4** [comment]
bof, c'est vraiment si embêtant que ça pour la modération au point de dire à ceux qui utilisent ces canaux d'aller ailleurs ?
je ne vois pas passer tant de demandes d'aide en vocal que ça, il y en a parfois mais généralement après un !vocal la demande est formulée par écrit.
Les canaux vocaux ne sont plus accessibles aux personnes sans rôle depuis #138 il me semble, cela devrait retirer pas mal de randoms.
Perso je trouverais ça dommage de les retirer, on est pas tous connecté H24, peut être que plus de gens les utilisent (j'en ai vu ajd et ce n'était pas Mishaa ni 3P)

**Comment by SirLynix** [comment]
Je trouverais ça dommage aussi, et un peu extrême, certains sont plus habitués au vocal et on a déjà vu des demandes d'aide bien se terminer en vocal (l'aide en vocal n'est pas interdite btw, juste déconseillée ou pour citer les guidelines "pas préconisées").

**Comment by Elanis** [comment]
Je suis de l'avis de Lynix et Mjö
