### ISSUE TITLE
Ajouter un sommaire à #guidelines

### ISSUE THREAD

**Issue by Elanis** [NotANameServer/discord#149]
Afin de se retrouver plus facilement dans le canal #guidelines, je pense qu'il faudrait ajouter un sommaire en début/fin de canal, ainsi qu'un lien "revenir au sommaire" dans le footer de chaque message.

**Comment by Equinox4** [comment]
j'aime bien l'idée, mais comment faire pour insérer un sommaire au début du canal ?

**Comment by Equinox4** [comment]
de toute façon quand on arrive sur le canal on voit le dernier message donc si on devait faire un sommaire, il devra se placer à la fin du canal

**Comment by Elanis** [comment]
> j'aime bien l'idée, mais comment faire pour insérer un sommaire au début du canal ?

Pour les guidelines, on edit les messages existants, donc c'est pas un soucis ^^

> de toute façon quand on arrive sur le canal on voit le dernier message donc si on devait faire un sommaire, il devra se placer à la fin du canal

Je pensais début et fin pour être sûr que le sommaire soit vu

**Comment by Equinox4** [comment]
> Pour les guidelines, on edit les messages existants
ça veut dire que les liens seront cassés
deux sommaires ça ferait un peu trop je trouve

**Comment by Elanis** [comment]
Y'a moyen de le construire intelligement :)
On utilise https://github.com/NotANameServer/discord/blob/main/guidelines.py pour regen les guidelines, il pourrait aussi build les sommaires en même temps sans trop de soucis je pense.

Pour les 2 sommaires, c'était une idée, mais oui, déjà un seul serait je pense utile :)

**Comment by Julien00859** [comment]
+1 pour avoir un sommaire au début, +1 si c'est possible de link chaque message
