### ISSUE TITLE
Le futur des rôles sur NaN

### ISSUE THREAD

**Issue by Elanis** [NotANameServer/discord#151]
Hello hello.

Il y a de ca quelques mois arrivait la nouvelle version de #rejoindre-les-canaux qui a donné un coup de jeune à tout ce système. Mais Discord a continué à faire évoluer ses systèmes (avec des décisions d'UX pas toujours terrible ...). Et nous arrivons à un nouveau point de décision de mon point de vue.

Nous avons actuellement 4 solutions possibles pour rejoindre les canaux:
- L'ancienne solution à base de réactions
- La solution actuelle, des messages contenant des select-box et des boutons
![image](https://user-images.githubusercontent.com/7013446/220919881-8b51207d-3dae-421a-85b9-9a1ad0e56b13.png)
- La solution discord à base de formulaires:
![image](https://user-images.githubusercontent.com/7013446/220920222-c6193525-f236-4c24-982d-25f96623bda2.png)
- La page "Chercher des salons"
![image](https://user-images.githubusercontent.com/7013446/220920565-37e07a5f-cbd7-45e2-b8ee-aa7d81a0dd6b.png)

----------

Je pense que pour faire un choix éclairé, il faut pouvoir prendre en compte:
- L'UX pour un nouveau membre (ce qui nous a fait remplacer la solution à base de réactions)
- L'UX pour ajouter de nouveaux rôles
- le fait que nous devrions pouvoir exclure les canaux dont nous sommes pas intéressés (tous le permettent plus ou moins, surtout vu que "Chercher des salons" est actif avec la solution actuelle
- Le fait que discord dans son UX chaotique a décidé d'afficher "**No Access**" pour les noms des canaux depuis quelques jours.
- https://github.com/NotANameServer/discord/issues/138 ?
- D'autres choses ?

----------

Ce n'est pas quelque chose de simple à décider, et c'est pour ca que j'ouvre cette issue, afin que les membres puissent discuter des pour et des contres de ces solutions.
A noter que pour les rôles colorés, rien ne nous empêche de les garder même si une solution différente de choix de canal de l'actuelle est décidée.

Je vous laisse la parole :)

**Comment by Nolent** [comment]
Avec l'apparition de "Chercher des salons", je penses que l'on peut supprimer les réactions et les boutons. On donne accès a tout les canaux par défaut et charge aux gens de cacher ceux qu'ils veulent (avec les formulaires quand ils rejoignent le serveur, puis avec la page "chercher des salons").
Cela fait retirer le systeme actuel de role par channel (vu qu'ils sont inutile a part pour les couleurs). Cela règle aussi le problème du no-access, vu que tout le monde à les accès.

**Comment by NightProg** [comment]
Je ne penses pas que la 4eme solutions soit une bonne idée pour les nouveaux membres le mieux serait un des 3 première solution, on mettra dans les règles comment choisir un canal, les règles que normalement tous le monde regarde

**Comment by Equinox4** [comment]
je reposte ici ce que je disais sur NaN + quelques avis supplémentaires
- le système de réactions est à abandonner, c'était bien à l'époque quand on avait rien d'autre mais ce n'est pas idéal, ça bug, on est obligé de bidouiller pour retirer les réactions ajoutées puisque y a une limite max (ou ça bug quand y en a trop je sais plus), les gens comprennent pas toujours et cliquent sur les émottes dans le texte, ce qui fait apparaitre une pop up pour souscrire à nitro du coup des gens pensent que le serveur est payant, bref pas ouf
- la solution actuelle avec les listes je la trouve bien, mais discord a récemment décidé de masquer le nom des canaux à ceux qui n'y ont pas accès ce qui rend le système actuel "fermé par défaut" un peu embêtant pour tout le monde chaque fois qu'on veux mentionner un canal (d’où la présente issue)
- je connais assez peu la solution à base de formulaires, ça peut être une bonne idée mais je crains que peu de gens n'aient la volonté de remplir un formulaire pour rejoindre un serveur. De plus cela ne résoudra pas ce problème de "No Access".
- La fonctionnalité "Rechercher les salons" semble être la solution, les noms des canaux s'affichent même à ceux qui l'ont masqué, mais cela requiert de passer en mode "ouvert par défaut", c'est à dire avec tous les canaux accessibles à everyone (donc les gens vont probablement avoir pleins de canaux à masquer *à chaque fois* qu'ils join). Un autre inconvénient, personnellement j'ai tendance à oublier que j'ai décoché des trucs la dedans donc au final je ne l'utilise pas, mais bon, c'est peut être juste moi qui ai une mémoire de poisson rouge.
Notez que même si on ouvre tous les canaux par défaut, certains canaux à accès limité (#sécurité par exemple) auront toujours ce problème (mais ce sera probablement beaucoup plus gérable d'avoir seulement 2-3 canaux comme ça plutôt que la majorité)

Je me demande si on ne pourrait pas faire une sorte de solution hybride, par exemple demander dans un formulaire si la personne veut *tous* les canaux, si oui -> join immédiatement, si non -> choisit tes canaux
Ou autre chose dans le même genre

voila en gros mon avis sur les différentes solutions proposées

**Comment by Elanis** [comment]
Je vais expérimenter pour voir, mais je crois qu'on peut avoir un formulaire qui préremplira #Chercher les salons, ce qui nous permettrait de résoudre toutes les problématiques. Je vais tester sur un serveur séparé et je vous partagerai mes tests ici

**Comment by Elanis** [comment]
De retour après mes experimentations, que j'ai du faire sur NaN même car les formulaires de onboarding sont limités aux commus de 5000 membres et plus :/

Voici ce que je peux en ressortir:
- On peut choisir des canaux affichés par defaut, j'en ai pris quelques un pour l'exemple:
![image](https://user-images.githubusercontent.com/7013446/221000325-8c96aac3-d60f-4b88-be2d-c9435d7dfbc3.png)
- Chaque page peut avoir jusqu'à 11 boutons:
![image](https://user-images.githubusercontent.com/7013446/220999703-e16966a7-fae5-4a98-b0da-41ec46bdbb0f.png)
Au delà, ca se transforme en select, et les valeurs ne possèdent plus de descriptions:
![image](https://user-images.githubusercontent.com/7013446/221000098-7b446569-de64-4b60-8d8d-e695c1ff3843.png)
- Les pages peuvent avoir des choix uniques ou multiples, et peuvent être forcées en requises ou non (ici, j'étais en non requis)
- Il est possible de donner des rôles et/ou des salons publics (qui seront donc pré cochés dans "#Chercher-des-Salons")
- Ce processus peut totalement cohabiter avec "#Chercher-des-Salons"
- Il est possible de créer des questions d'onboarding à la première connexion, mais aussi des questions encore accessibles par la suite

--------

Voici les canaux qu'on aura besoin de gérer:
- 12 dans la catégorie "langages" (11 langages + le fonctionnel) + #autres-langages (donné par défaut si un autre langage est choisi ? Ou par défaut tout court ?)
- 6 rôles "techniques" Rendu 3D (#rendu3d, #opengl, #vulkan), Base de données, Système et réseau, Développement de jeux-vidéos (#gamedev, #moteurs-de-jeux , #not-a-#gamejam), Développement de bots Discord, Manufacture de langages
- 14 projets
- Canaux divers (optionnellement dans le formulaire, sinon uniquement dans "#Chercher-des-Salons"): #stats, #questions-professionnelles, #screenshots, #architecture-dev, #hardware, #support-technique, #defis/#defis-discussions, #etudes-orientation, #jeux, #sciences, Canaux Vocaux

Roles:
- Roles colorés
- Defis

**Comment by Elanis** [comment]
Update: ils ont l'air d'avoir rollback leur ""feature"" qui affichait "#No-Access", ca nous donne du temps pour discuter de tout ca (until next time)

**Comment by Elanis** [comment]
*1 month later*
La feature est de retour ! C'est de nouveau la merde.

**Comment by x0rld** [comment]
![image](https://user-images.githubusercontent.com/45242856/230742950-1781d7cc-de18-4be2-abc1-3f115aab3a03.png)
j'ai ça perso quand ya un channel que j'ai pas

**Comment by Elanis** [comment]
Il semblerait que ca depende des gens si ca s'affiche ou pas. Mais j'ai déjà eu quelques reports disant que c'était de retour cette semaine :/

**Comment by Elanis** [comment]
J'ai commencé une experimentation à base de formulaires.

La version actuelle se base sur les rôles existants et est compatible avec #rejoindre-les-canaux, c'est surtout histoire de pouvoir voir si c'est utilisable en pratique avant de faire sauter toutes les permissions des canaux du serveur.

Pour un nouveau membre:
![image](https://user-images.githubusercontent.com/7013446/232316231-9acd149f-3fb1-4316-b53d-f088dbb7e8e0.png)
![image](https://user-images.githubusercontent.com/7013446/232316272-d4116263-9f3f-4f3d-93e1-9bcdde2f3d8f.png)
![image](https://user-images.githubusercontent.com/7013446/232316282-f6defbf7-6d9d-4e48-8e1d-c796eec1df31.png)
![image](https://user-images.githubusercontent.com/7013446/232316285-f9fd860c-3177-492d-b99e-64d7e292f74b.png)


Pour un membre déjà présent (ca ne sera pas pré coché pour vous pour la première utilisation, mais c'est conservé ensuite):
![image](https://user-images.githubusercontent.com/7013446/232316161-a8e21f81-6eb5-4c8d-beb7-13279e6645c5.png)
![image](https://user-images.githubusercontent.com/7013446/232316165-c4c4a7f3-ca7f-4ec1-b5c7-98d68f9e0764.png)

**Comment by Julien00859** [comment]
J'adore <3

**Comment by Julien00859** [comment]
> #autres-langages (donné par défaut si un autre langage est choisi ? Ou par défaut tout court ?)

=> visible par défaut, les arrivants auront le formulaire prompt et ce sera difficile pour eux de ne pas choisir leur langage, autant qu'on se simplifie la vie.

Génial pour la catégorie "Quel type de notifications souhaites-tu recevoir ?"

Ya :video_game: qui est répété deux fois, je propose de remplacer le premier par :chess_pawn: `chess_pawn` (dommage pour le contraste)

**Comment by florentm35** [comment]
Je pense qu'il serait bon de mettre les personnalisations des canaux des techniques avant les salons de projets, c'est le cœur du serveur

**Comment by Elanis** [comment]
Update:
- rejoindre-les-canaux a été caché il y a quelques semaines
- les salons de la catégorie "Technologie" ont été passé public mardi sans soucis
- nous avons enchainé avec les catégories "Rendu 3D" et "Dev. de J.V." aujourd'hui

**Comment by Elanis** [comment]
Effectué pour les projets hier, reste plus que les langages

**Comment by Elanis** [comment]
Effectué pour les langages
