### ISSUE TITLE
Description des canaux

### ISSUE THREAD

**Issue by Equinox4** [NotANameServer/discord#152]
J'ai vu plusieurs personnes taper la commande !help à la recherche des cours listés dans les réponses aux commandes de type `!cours<lang>`, et il est vrai que ces commandes ne sont listées nul par ailleurs que sur github (sauf pour le canal #java).
Je propose de revoir les descriptions des canaux de la manière suivante:
- déplacer la liste des cours/tutoriels/conseils qu'on peux y trouver actuellement dans la commande respective, puisque la taille de la description est limitée et qu'on arrive au bout sur certains canaux
- ajouter un texte qui décrit réellement le canal (par exemple celle de #java me semble bien)
- indiquer à la suite du texte que des cours pour le langage du canal en question sont disponibles en tapant `!cours<lang>`

**Comment by Equinox4** [comment]
Voici donc comment je propose de réécrire les descriptions:
```
#asm
:langage_asm: Canal pour toute question relative aux langages assembleurs.

#c
:langage_c: Canal pour toute question relative au langage C.
Utilisez la commande `!coursc` pour afficher une liste de cours recommandés.

#cpp
:langage_cpp: Canal pour toute question relative au langage C++.
Utilisez la commande `!courscpp` pour afficher une liste de cours recommandés.

#csharp
:langage_csharp: Canal pour toute question relative au langage C#.
Utilisez la commande `!courscsharp` pour afficher une liste de cours recommandés.

#html-css
:langage_html: Canal pour toute question relative aux langages HTML/CSS.
Utilisez la commande `!courshtml` pour afficher une liste de cours recommandés.

#java-jvm
:langage_java: Canal pour toute question relative aux langages JVM (Java/Kotlin/Scala/...).
Utilisez la commande `!coursjava` pour afficher une liste de cours recommandés.

#javascript-typescript
:langage_js: :langage_ts: Canal pour toute question relative aux langages JavaScript et TypeScript.
var:thumbsdown:let/const:thumbsup:
Utilisez la commande `!coursjs` pour afficher une liste de cours recommandés.

#langages-fonctionnels
Canal pour toute question relative a un langage fonctionnel (Haskell, Lisp, ...) ou concernant les paradigmes de programmation fonctionnelle.

#lua
:langage_lua: Canal pour toute question relative au langage Lua.

#php
:langage_php: Canal pour toute question relative au langage PHP.
Utilisez la commande `!coursphp` pour afficher une liste de cours recommandés.

#python
:langage_python: Canal pour toute question relative au langage Python.
Utilisez la commande `!courspython` pour afficher une liste de cours recommandés.

#rust
:langage_rust: Canal pour toute question relative au langage Rust.
Utilisez la commande `!coursrust` pour afficher une liste de cours recommandés.

#autres-langages
Canal pour toute question relative à un langage ne possédant pas son canal dédié.
```
Tout ce qui n'est pas écrit ci-dessus et qui se trouve actuellement dans les descriptions sera déplacé dans le résultat de la commande correspondante.

**Comment by Julien00859** [comment]
Je pense plus à un affichage très cours du type ":snake: Langage Python `!courspython`"

**Comment by Equinox4** [comment]
j'ai mis des descriptions génériques faute de mieux mais on peux mettre ce que vous voulez à la place, du moment que la commande est indiquée.

**Comment by Iltotore** [comment]
> :langage_java: Canal pour toute question relative aux langages JVM (Java/Kotlin/Scala/...).
Utilisez la commande `!coursjava` pour afficher une liste de cours recommandés.

Avoir avec @florentm35 mais cette description me parait bien. Je pense que c'est important de garder la partie qui donne des exemples de langages JVM (hors Java).

**Comment by florentm35** [comment]
> > :langage_java: Canal pour toute question relative aux langages JVM (Java/Kotlin/Scala/...).
> > Utilisez la commande `!coursjava` pour afficher une liste de cours recommandés.
> 
> À voir avec @florentm35 mais cette description me parait bien. Je pense que c'est important de garder la partie qui donne des exemples de langages JVM (hors Java).

Le seul point que je pourrais voir c'est pour Clojure et Scala, je en sait pas si il ne serait pas mieux dans langage fonctionnelle (bon après vu le peux de question sur ses deux langage, c'est un peu un faux soucis)
@Iltotore Tu en pense quoi ?

**Comment by Iltotore** [comment]
>  je en sait pas si il ne serait pas mieux dans langage fonctionnelle

Je pense que ça dépend de la question mais que par défaut ça devrait se faire dans #java-jvm et aller vers #langage-fonctionnel si la question porte sur la programmation fonctionnelle

**Comment by Equinox4** [comment]
ok, pour le moment je vais donc ouvrir la PR avec les changements de #python, j'attendrai encuite quelques jours supplémentaires puis si aucun autre changement n'est proposé, je fusionnerai.

**Comment by Julien00859** [comment]
Je préférerais qu'on ait un style cohérent partout avant qu'on se décide à changer quoi que ce soit :grimacing:

**Comment by Equinox4** [comment]
On peut décider d'avoir un style semblable pour toutes les descriptions comme on peut avoir une style différent pour chacune, It's up to you.
Personnellement j'aime bien aussi quand c'est pareil partout donc pour concilier cette idée avec la description que tu as proposé tantôt, je suggère d'appliquer une courte description du style ":java: Langages JVM (Java/Kotlin/Scala/...)" (avec un emote, c'est cool les emotes) suivit de la commande

**Comment by Equinox4** [comment]
ça pourrait donner ça par exemple:
```
#asm
:langage_asm: Langages assembleurs.

#c
:langage_c: Langage C.
!courc pour afficher une liste de cours.

#cpp
:langage_cpp: Langage C++.
!courscpp pour afficher une liste de cours.

#csharp
:langage_csharp: Langage C#.
!courscsharp pour afficher une liste de cours.

#html-css
:langage_html: Langages HTML/CSS.
!courshtml pour afficher une liste de cours.

#java-jvm
:langage_java: Langages JVM (Java/Kotlin/Scala/...).
!coursjava pour afficher une liste de cours.

#javascript-typescript
:langage_js: :langage_ts: Langages JavaScript et TypeScript.
var:thumbsdown:let/const:thumbsup:
!coursjs pour afficher une liste de cours.

#langages-fonctionnels
Langages fonctionnels (Haskell, Lisp, ...) et paradigmes de programmation fonctionnelle.

#lua
:langage_lua: Langage Lua.

#php
:elephant: Langage PHP et frameworks associés (Laravel, Symfony, etc).
!coursphp pour afficher une liste de cours.

#python
:snake: Langage Python !courspython

#rust
:langage_rust: Langage Rust.
!coursrust pour afficher une liste de cours.

#autres-langages
Canal pour toute question relative à un langage ne possédant pas son canal dédié.
```
