### ISSUE TITLE
Ajout de la formation de Grafikart sur JavaScript et Typescript pour les suggestions de ressources JS/TS

### ISSUE THREAD

**Issue by SirMishaa** [NotANameServer/discord#153]
# Le changement, c'est maintenant
(Au passage, c'est la nouvelle formation de Grafikart sorti il y a 4 mois pour la première vidéo, réécriture complète avec même un passage sur Node.js. Concernant la qualité et la pédagogie de cette dernière, [Grafikart n'a plus rien à prouver de ce côté-là](https://grafikart.fr/), je la recommande personnellement à mes amis) 

![image](https://user-images.githubusercontent.com/42717232/222835984-6b8ead0c-4c08-465d-aeb6-e7e351606d2d.png)

```json
{
  "embed":{
    "color":15981340,
    "fields":[
        {
            "value":"Cours vidéo en français et gratuit, avec un passage sur Node.js: [Apprendre le JavaScript](https://www.youtube.com/watch?v=asToYAq0F-I&list=PLjwdMgw5TTLXgsTQE_1PpRkC_yX47ZcGV) \nCours vidéo en français et gratuit: [Apprendre le TypeScript](https://www.youtube.com/watch?v=ffCIANfx_-0&list=PLjwdMgw5TTLX1tQ1qDNHTsy_lrkCt4VW3)",
            "inline":false,
            "name":":movie_camera: Formation Grafikart (recommandée)"
        },
        {
            "value":"Version anglaise: [The Modern JavaScript Tutorial](https://javascript.info/) :flag_gb:\nVersion française: [Le tutoriel JavaScript moderne](https://fr.javascript.info/) :flag_fr:",
            "inline":false,
            "name":":closed_book: Cours JavaScript moderne"
      },{
            "value":"Cours en anglais sur le JavaScript: [Eloquent JavaScript](https://eloquentjavascript.net/)",
            "inline":false,
            "name":":blue_book: Eloquent JavaScript"
      },{
            "value":"Cours en anglais sur le JavaScript: [You Don't Know JS](https://github.com/getify/You-Dont-Know-JS)",
            "inline":false,
            "name":":blue_book: You Don't Know JS"
      },{
            "value":"Cours vidéos en anglais et __payant__ sur les technologies web Front-End\nLes cours ont un __accès gratuit pour 6 mois avec le pack Github Student__\n[Frontend Masters](https://frontendmasters.com/)",
            "inline":false,
            "name":":movie_camera: FrontendMasters"
      },{
            "value":"Pensez à regarder également dans les messages épinglés, des ressources y sont listées.",
            "inline":false,
            "name":":pushpin: Messages épinglés"
      }]
  }
}
```

**Comment by Equinox4** [comment]
good, je vais créer la PR et modifier l'embed.

**Comment by yannbcf** [comment]
Je ne remets pas en doute la qualité des formations / cours francophones mais j'aurais plus tendance à faire confiance à https://www.totaltypescript.com/ par exemple, crée par Matt Pocok, une personne très connue dans l'univers typescript et qui a travaillé chez Vercel

**Comment by Equinox4** [comment]
hello, l'un n’empêche pas l'autre, on peut très bien ajouter ce lien aussi.

**Comment by SirMishaa** [comment]
> 

Pour le coup, ce n'est pas le scope de cette issue. On parle bien de la formation française de Grafikart.
Il y également de très bonnes ressources de FrontendMaster qui sont link, pour les formations en anglais dans l'embed.

Si tu penses que c'est pertinent de l'ajouter, tu peux faire une issue.
