### ISSUE TITLE
Les salons vocaux

### ISSUE THREAD

**Issue by Julien00859** [NotANameServer/discord#158]
J'en ai marre d'être interrompu lorsque je fais des réunions de travail (notahub/incipyt/club-de-lecture) par des membres gogoles qui viennent poser leurs questions à la con ou bien juste "discuter".

Je propose de rendre invisible tous les salons vocaux par défaut et de faire un rôle (accessible via #rejoindre-les-canaux) pour les rendre visible. Ce rôle permettrait de filtrer la grosse majorité des noobs qui veulent poser leurs questions.

Je proposer aussi d'ajouter un bot capable de réguler les accès aux salons vocaux, comme celui qui tourne sur Read-the-Docs. Que n'importe qui puisse créer son salon et décider de rendre ce salon invisible et/ou accessible sur invitation.

**Comment by zazbone** [comment]
Hello,
ça pourrait être un salon par projet aussi (not a hub, nazara, defis ...), si les personnes à l'initiative du projet en font la demande.
Du coup, ça serait à la fois caché à la plupart des gens et justifierait que les questions ou les interventions hors sujets n'ont pas leur place.

**Comment by JeanCASPAR** [comment]
Hey,
Je ne sais pas si quelque chose d'aussi radical que faire un canal vocal privé soit nécessaire mais quelque chose comme un canal "Discussions sérieuses" ou "groupe de travail" ou autre, ou un canal public accessible par rôle pour les projets qui en ont le besoin serait sans doute suffisant.

**Comment by florentm35** [comment]
Sinon au lieu de le mettre dans le salon #rejoin-les-canaux mettre un message dans les guidelines expliquant le fonctionnement des vocaux et rappelant que les canaux vocaux ne sont pas des vocaux d'aide et rajouter un petit bouton pour accepter et avoir accès au canaux vocaux.

Après un système de canaux à la volé/configurable pourrais être intéressant.

**Comment by JeanCASPAR** [comment]
> Sinon au lieu de le mettre dans le salon #rejoin-les-canaux mettre un message dans les guidelines expliquant le fonctionnement des vocaux et rappelant que les canaux vocaux ne sont pas des vocaux d'aide et rajouter un petit bouton pour accepter et avoir accès au canaux vocaux.
> 
> Après un système de canaux à la volé/configurable pourrais être intéressant.

On a déjà !vocal dans les #guidelines, je pense que si les personnes en question avaient lu les #guidelines elles n'iraient pas en vocal pour ça.

**Comment by florentm35** [comment]
> On a déjà !vocal dans les #guidelines, je pense que si les personnes en question avaient lu les #guidelines elles n'iraient pas en vocal pour ça.
C'est pour ça que j'indique d'avoir un btn ou une réaction dans la guideline, ça limiterais grandement le nombre de nuissible dans les canaux vocaux

**Comment by Julien00859** [comment]
> Hey, Je ne sais pas si quelque chose d'aussi radical que faire un canal vocal privé soit nécessaire mais quelque chose comme un canal "Discussions sérieuses" ou "groupe de travail" ou autre, ou un canal public accessible par rôle pour les projets qui en ont le besoin serait sans doute suffisant.

On a déjà des salons "Not-a-Hub" et "Club-de-Lecture" ça n'empêche pas les nuisibles



> > On a déjà !vocal dans les #guidelines, je pense que si les personnes en question avaient lu les #guidelines elles n'iraient pas en vocal pour ça.
> 
> C'est pour ça que j'indique d'avoir un btn ou une réaction dans la guideline, ça limiterais grandement le nombre de nuissible dans les canaux vocaux

Bonne idée ça !

**Comment by Equinox4** [comment]
même idée que pour les projets, on peut masquer les canaux vocaux par défaut et ajouter une option dans "channels and roles" pour les faire apparaitre
on peut aussi renommer l'un d'entre eux pour les discussions sérieuses

**Comment by Equinox4** [comment]
maj: les canaux vocaux sont désormais masqués par défaut et NaB comprend un module pour créer des salons vocaux privés
