### ISSUE TITLE
Création de !coursql

### ISSUE THREAD

**Issue by x0rld** [NotANameServer/discord#159]
Edit: j'ajoute ce qu'il y a de pin qui est un cours

Je me suis souvenu de ce site qui est pratique pour pratiquer sur les bases de requêtes SQL et je me dis que ça serait intéressant dans la commande

https://sqlzoo.net/wiki/SQL_Tutorial

Cours de sql en français : https://sql.sh/

Payant https://www.udemy.com/the-complete-sql-masterclass-for-data-analytics 
Formation SQL from Zero to Hero (sur PGSQL)

**Comment by Equinox4** [comment]
on pourra ajouter sql.sh qui est en français
