### ISSUE TITLE
Déplacer les messages dans #suggestions

### ISSUE THREAD

**Issue by JeanCASPAR** [NotANameServer/discord#16]
Y a pas vraiment de raison de faire un nouveau chan et de virer #suggestions, autant juste mettre le webhook dans #suggestions et supprimer #github

**Comment by GuillaumeBelz** [comment]
A voir si #suggestion a ete supprimé ou juste masqué. Si c'est supprimé, je pense que c'est trop tard.

Par contre, renommer github en suggestions me semblerait effectivement plus clair. Il n'est pas evident tout de suite qu'un canal "github" est la pour faire les suggestions

**Comment by JeanCASPAR** [comment]
Pour l'instant le canal est encore visible.

**Comment by GuillaumeBelz** [comment]
Ah ok lol :D

**Comment by SirLynix** [comment]
> Y a pas vraiment de raison de faire un nouveau chan et de virer #suggestions, autant juste mettre le webhook dans #suggestions et supprimer #github

L'idée était de partir à neuf. Je ne considère pas l'historique de ce canal comme important mais peut-être que les membres aimeraient le garder, auquel cas ce qu'on peut faire c'est faire un webhook dédié à #suggestions pour avoir l'ouverture des issues/PR uniquement et garder les commentaires dans #github (qu'on renommerait en github-comments ?). Voir #20

**Comment by SirLynix** [comment]
Implémenté via #20
