### ISSUE TITLE
Lien de paste artemix obsolète

### ISSUE THREAD

**Issue by 3PSY0N** [NotANameServer/discord#162]
Hello, quick issue pour prévenir que dans les guidelines le lien d'artemix est mort, il peut sûrement être supprimé.

https://github.com/NotANameServer/discord/blob/0b01b07aa78f044e74ea7548d00a2a17c2f706b6/guidelines.md?plain=1#L90

**Comment by Elanis** [comment]
Merci, c'est reglé !
