### ISSUE TITLE
Supprimer les tabs inutiles dans GH ?

### ISSUE THREAD

**Issue by GuillaumeBelz** [NotANameServer/discord#17]
Tant qu'il n'y a pas un besoin spécifique, peut etre supprimer les tabs Actions, Projects et Wiki de GH ?

<img width="493" alt="Screen Shot 2021-04-26 at 12 29 08 PM" src="https://user-images.githubusercontent.com/1651508/116139560-00432f00-a68b-11eb-8310-e161afe3a304.png">

**Comment by GiregL** [comment]
Je ne connais pas trop GH pour ce genre de choses, mais y'a pas moyen de relier la partie Wiki et la doc même (le contenu du repo) ?

**Comment by JeanCASPAR** [comment]
Wiki peut être utile si lazor mets les règles au propre, non ?

**Comment by GiregL** [comment]
On bossera dessus tout a l'heure, mais aucune idée d'où elles finiront

**Comment by GiregL** [comment]
Bah sinon le wiki peut être le mode d'emploi du dépôt même, avec comme contenu ce genre de choses: [L'issue 12](https://github.com/NotANameServer/discord/issues/12)

**Comment by GuillaumeBelz** [comment]
Oui, ca serait possible. C'est juste une question de choix d'organisation. Mais vu que le repo est déjà un ensemble de docs MK, ca me semble pas forcément pertinent d'avoir un wiki si c'est juste pour 2-3 pages. (ca fait 2 endroits pour gérer de la doc et le wiki sera très peu visible et donc visité)

Pour le moment, j'ai désactivé le wiki. A voir si quelqu'un a un truc intéressant a proposer pour le wiki (et dans ce cas, il pourra ouvrir une nouvelle issue pour proposer ce qu'il veut ajouter dans le wiki)

**Comment by Mesteery** [comment]
à la limite `Projects` on aurait pu laisser, c'est pas mal pour suivre l'avancement, comme une roadmap

**Comment by GuillaumeBelz** [comment]
Il faut créer un projet et le gérer (ie mettre des issues dans l'avancement, faire des milestones, etc). C'est a mon avis le genre de chose qui doit être fait uniquement si une personne prend la responsabilité de gérer la chose, sinon c'est juste un truc qui va mourir au bout d'un mois.

Donc comme le wiki, ca me semble plus pertinent de le fermer pour le moment et d'attendre d'avoir une personne qui propose un truc sérieux pour réouvrir.

**Comment by Mesteery** [comment]
> C'est a mon avis le genre de chose qui doit être fait uniquement si une personne prend la responsabilité de gérer la chose, sinon c'est juste un truc qui va mourir au bout d'un mois.
c'est pas vraiment un problème et dans tous les cas je peux m'en occuper (mais faut déjà qu'on ait les droits)
