### ISSUE TITLE
RoadMap

### ISSUE THREAD

**Issue by DrTableBasse** [NotANameServer/discord#170]
En me baladant sur internet, à mon habitude, je suis tombé sur un site que je trouve vraiment sympatoche pour aiguiller d'avantage les gens qu'importe leur niveau

https://roadmap.sh/

Une roadmap suivant un thème, un langage ou bien une techno.

Je pense qu'il serait sympas d'avoir une commande pour avoir la roadmap ou bien l'ajouter sur les commandes de cours 😄

**Comment by Equinox4** [comment]
l'idée est interessante, surtout pour répondre aux gens qui ne savent pas par ou commencer
on pourrait créer une commande `!roadmap` pour link ce site avec une petite explication

**Comment by DrTableBasse** [comment]
en sachant que le site propose déjà des roadmap sur différents thèmes, ce site se voit "non complet" voire trop poussé sur certains points.
Pour juger de l'utilité du site, je pense qu'il faudrait donner ça aux ambassadeurs et qu'ils disent ce qu'ils en pensent. On pourrait se faire une idée :D 

dans mon cas je suis plutôt fan, on a mis ça en place pour ma classe

**Comment by Julien00859** [comment]
J'ai découvert ce site quelques temps après avoir fini mes études donc il ne m'a jamais vraiment été utile à titre personnel. Je pense qu'il est intéressant pour quelqu'un qui n'est plus *débutant* et qui veut étendre ses horizons: découvrir le nom des frameworks ou s'ouvrir à l'admin-sys. Je ne pense pas que *tel quel* aucun ambassadeur ne pourra en faire quelque chose: les `!cours<langage>` sont tout aussi (voir plus) complets que les roadmaps et ont l'immense avantage de présenter des ressources en français. Dans le cas de la roadmap python, elle me semble superficielle et les steps donnent souvent des liens vers tutorialspoint et geeksforgeeks qui proposent des tutoriels de piètre qualité.

Les roadmaps backend et devops me semblent plus intéressantes. Peut-être que @M0NsTeRRR pourra donner son avis, voire épingler ces roadmaps dans #systeme-reseau-deveops . Je n'en ferais rien pour #python car nous référençons déjà https://www.fullstackpython.com/

**Comment by DrTableBasse** [comment]
je dis absolument pas le contraire mais je trouvais que c'était juste un plus 😄

**Comment by M0NsTeRRR** [comment]
On peut l'épingler dans le canal système et réseau à minima comme un état de l'art des solutions qui existent dans le métier :)

**Comment by DrTableBasse** [comment]
yes je mets le lien 😄

**Comment by Iltotore** [comment]
Je tiens à prévenir: certaines roadmaps du site sont assez vieilles ou bancales. Certaines sont pas mal et pourraient bien être recommandées mais je pense qu'il ne faut pas recommander n'importe quelle roadmap et voir au cas par cas.

**Comment by Equinox4** [comment]
c'est ce que je pensais aussi, on vas sélectionner les roadmaps qui sont pas trop mal en précisant que le reste n'est pas forcément à jour/recommandé

**Comment by Equinox4** [comment]
moi j'ai regardé pou backend/php, il faudrait que chaque amba nous indique si la raodmap correspondant à son/ses channels sont ok aussi

**Comment by M0NsTeRRR** [comment]
On a intégré la roadmap sécu et devops dans #système-réseau-devops

**Comment by DrTableBasse** [comment]
vas voir la gueule de la roadmap, ça sera ignoble sur discord...

**Comment by DrTableBasse** [comment]
essaie de ton coté si tu veux, tu verras que ça sera dégueulasse

**Comment by Equinox4** [comment]
on aura pas toutes les infos disponibles en cliquant sur les items si on met juste une image sur discord

**Comment by DrTableBasse** [comment]
Et puis si tu prends une image pour le devops on est a la limite du panorama donc pas adapter

**Comment by Elanis** [comment]
Les differents ambassadeurs sont passé sur l'issue pour ajouter ou non à leurs canaux la roadmap, donc je ferme :)
