### ISSUE TITLE
Ajout de la commande `!scrapping` (alias `!webscrapping`) pour quote plus rapidement la guideline

### ISSUE THREAD

**Issue by CallMePixelMan** [NotANameServer/discord#173]
Tout est dans le titre (et ça prend racine de ma première issue #172 avec @Elanis). 
Je pense que c'est juste quelque chose de pratique, avec pourquoi pas des infos sur le véritable but de Selenium ou encore des extraits de CGU (comme celles de Vinted) de sites qui interdisent explicitement le scrapping.

Le but est juste de pouvoir écarter très vite les demandes borderlines autour du scrapping, je pense que ça ne peut pas faire de mal.

Bonne journée !

**Comment by Equinox4** [comment]
Hello, ça me semble être une très bonne idée

**Comment by Equinox4** [comment]
done
