### ISSUE TITLE
Idées nouveaux salons

### ISSUE THREAD

**Issue by dcpc007** [NotANameServer/discord#175]
Vu les tendances, un chan #devops pourrait être bien pour les topics git,  terraform ansible et similaires

Et un autre #virtualisation avec vmware, docker podman kubernetes.

Telkar

**Comment by M0NsTeRRR** [comment]
Les topics que tu mentionnes sont déjà discuté dans le canal #system-et-reseau. Il y a aussi trop peu de discussion sur chacun des topics pour justifier un canal dédié.

ça rejoint une ancienne proposition https://github.com/NotANameServer/discord/issues/139

**Comment by Elanis** [comment]
Je suis d'accord avec les deux commentaires précédents.

Ce que j'ai aussi proposé dans #architecture-dev sinon c'est de renommer #systeme-et-reseau pour être plus explicite.
#systeme-reseau-devops pourrait être une solution par exemple.

Je n'ai pas d'avis sur ce renommage, mais je partage l'idée ici au cas où.

**Comment by Equinox4** [comment]
ça fait un peu un nom à rallonge

**Comment by Equinox4** [comment]
on peut éventuellement ajouter dans la description du canal que les questions devops y ont aussi leur place ?

**Comment by Elanis** [comment]
Les gens lisent pas la phrase concernant Git, je suis pas sûr qu'ils vont lire celle pour le devops :/

**Comment by Equinox4** [comment]
true, mais au moins ça sera écrit "officiellement" x)

**Comment by Julien00859** [comment]
Sinon faire comme pour les langages, faire un *section* Système et Réseau, déclinée en plusieurs salons

**Comment by Elanis** [comment]
Mon commentaire dans l'autre issue est toujours valable imo

> Je ne pense pas que ce soit une bonne idée, pour deux raisons:
> 
> * Systèmes et réseaux est un canal actif, mais pas hyperactif, j'ai assez rarement vu des discussions se superposer (au ratio de toutes les discussions qui y ont lieu
> * Beaucoup de questions seraient "le cul entre deux chaises", car elles ont à la fois une composante système, et une composante réseau (exemples: configuration d'un cluster kubernetes, d'un bind9, d'iptables, etc.)

(https://github.com/NotANameServer/discord/issues/139#issuecomment-1363681262)

**Comment by Julien00859** [comment]
encore quelqu'un s'est trompé https://discord.com/channels/323076998576603137/553130821603819530/1136314299543998474

**Comment by Equinox4** [comment]
ok, on peut tenter
