### ISSUE TITLE
Retours sur le sondage des 10 000

### ISSUE THREAD

**Issue by LeMinaw** [NotANameServer/discord#18]
Quelques points me semblent améliorables, dans l'éventualité d'une prochaine fois (ou de toute autre truc du même genre). Prendre conscience de ces "failles" permettra aussi une meilleure interprétation potentielle des données.

**Premier point :**

![image](https://user-images.githubusercontent.com/3968360/116142555-b423d900-a6e2-11eb-87f8-b573bae077b3.png)

Je me doute que ça n'a rien de volontaire, mais il serait souhaitable de remplacer _Sexe_ par _Genre_, et de permettre un choix _Autre_ en plus (car actuellement, si on ne se considère pas comme homme ou femme, on a pas d'autre choix que de ne _pas vouloir l'indiquer_).

(À l'objection "Osef de toute façon y'a que des mecs en IT", qu'on m'a déjà sortie dans un contexte presque semblable, je répondrai que c'est _justement_ une excellente raison de jouer la carte de l'inclusion le plus possible)

**Autre point assez mineur :**

![image](https://user-images.githubusercontent.com/3968360/116143375-be92a280-a6e3-11eb-9a60-d958fc632a3d.png)

La question ne précise pas s'il s'agit des formations liés à l'info ou non. Si on considère tout diplôme, je cocherai par exemple les cases vertes, mais uniquement la rouge s'ils doivent être liés à l'IT (ça fait une sacrée différence).

**Comment by SirLynix** [comment]
Je ne vois aucune raison pour s'opposer à ces deux requêtes, même si de ce que j'ai compris on ne peut pas mettre à jour le sondage actuel sans risquer de perdre les réponses déjà fournies donc ça devra attendre le prochain.

Parlant du prochain sondage, ça pourrait être intéressant d'en faire de façon un peu plus régulière, type tous les six mois ? (Pour rappel le précédent sondage était fin 2019, pour les 5000 membres).

**Comment by FaustinM** [comment]
Je pense que tous les ans est plus simple à gérer et à remplir pour les utilisateurs, stackoverflow fait ce système de sondage annuel, autant garder ce modèle

**Comment by Julien00859** [comment]
Je clos l'issue comme le sondage est cloturé depuis longtemps, on garde évidemment tout ceci en tête pour les prochaines fois :)
