### ISSUE TITLE
Ajout d'un salon WIP(Work-In-Progress) pour les projets

### ISSUE THREAD

**Issue by NightProg** [NotANameServer/discord#182]
Je pense que les membres du serveur ne se permettent pas de partager des projets WIP parce que justement, ils ne sont pas encore finis. Ajouter un salon wip-projet (je ne sais pas encore le nom exact du salon) permettra de partager aux membres, qui eux pourront, s'ils ont envie participé au projet. Le salon sera soit le même système du :
  - salon screenshot : il y aura un mode lent, mais tout le monde pourra sans faire un ticket partager son WIP projet (le meilleur système selon moi)
  - ou alors, faire comme le salon projet

**Comment by Equinox4** [comment]
En soi, le salon vos-projet accepte les projet en WIP, il faut juste que le projet soit avancé un minimum

**Comment by Elanis** [comment]
#vos-projets est déjà ouvert aux messages sans tickets (il faut juste que les gens prennent 2 minutes pour lire les règles du canal pour savoir comment poster).
Et je suis d'accord avec Mjö, #vos-projets n'est pas fermé aux WIP, il est juste fermé aux idées qui sont "arrivées il y a 5 minutes". On a enormement de projets qui ont été présentés alors que c'était des bêta (ou même des alpha), sans soucis.

**Comment by NightProg** [comment]
oui mais bon si l'utilisateur doit faire deux ticket, une pour le projet wip, et une quand ce sera fini, autant cree un nouveau salon avec mode lent

**Comment by Equinox4** [comment]
hein ?
On vient de dire que il n'y a plus besoin de faire un ticket pour poster dans ce canal et que les projet wip sont acceptés

**Comment by Equinox4** [comment]
donc tu peux simplement poster un message quand ton projet est en wip, puis un autre qq temps plus tard pour annoncer les évolutions

**Comment by NightProg** [comment]
Ah oui, excusez-moi, je n'ai pas vu le message d'Elanis, Github ne l'affiche pas(mon wifi est pas top)

**Comment by Julien00859** [comment]
puis ya screenshot aussi
