### ISSUE TITLE
Mention Discord

### ISSUE THREAD

**Issue by jujudavexe** [NotANameServer/discord#185]
Ajouter un rôle pour savoir si l’on veut bien se faire mentionner ou non.
Cela serai pas mal car j’ai pu constater que certaines personnes dont moi préféreraient se faire mentionner pour voir les messages qui leurs sont destinés.

**Comment by Julien00859** [comment]
Ça existe déjà, https://discord.com/channels/323076998576603137/860920579154772018/860921172912111656

> Ceux qui ne sont pas dérangés par les notifications peuvent se renommer pour ajouter l'emoticon 🛎️ :bellhop_bell: à leur pseudo.

**Comment by jujudavexe** [comment]
Le problème c'est que sur discord, avec windows 11, quand on met cet émoji dans notre pseudo il est convertis en un symbole très peu intuitif. 
Voici ce que ça fait : https://discord.com/channels/323076998576603137/392444836441227274/1170390751457329352

**Comment by Equinox4** [comment]
hello, effectivement le caractère 🛎️est remplacé par son équivalent ascii très peu lisible quand il est placé dans le pseudo.
On pourrait le remplacer par 🔔qui n'a pas cet inconvénient ?
