### ISSUE TITLE
Création du canal actualité brulante

### ISSUE THREAD

**Issue by NightProg** [NotANameServer/discord#192]
Bonjour à tous, je pense que ce serveur a besoin du canal  "actualité brulante" (le nom peut changer), vu son activité plus grande que pour certaine channel que le serveur. De plus les membres de ce serveur donnent l'impression d'aimer et de parler de fait divers et brulant comme la politique. Je propose donc que le thread "actualité brulante" deviennent à son tour un canal.

Bonne journée à tous.

**Comment by Equinox4** [comment]
mdr, non

**Comment by Elanis** [comment]
Non merci, par contre je peux proposer de lockedout tous les membres actifs du thread pour reduire l'activité si vraiment elle est trop grande

**Comment by NightProg** [comment]
Vous avez pourtant fait cela pour l'ancien thread joke-it. L'activité n'est pas un problème, c'est juste que c'est dommage et que selon moi, en vaut le coup. Je pense que certaines personnes n'ont pas encore pris connaissance de ce thread. 
Et aussi, puis-je avoir votre avis sur ce sujet, pourquoi vous ne voulez pas cette idée.

Bonne soiré à tous

**Comment by Elanis** [comment]
Je vais expliciter la position du staff: On tolère l'existence du thread parce qu'il permets de sortir toutes les discussions foireuses ou soumises à débat des canaux #discussion et #detente, pour les garder pour les discussions un peu plus autour du sujet du serveur. Mais ca ne veut pas dire qu'on veut voir son activité augmenter, au contraire.
C'est un thread totalement HS par rapport au sujet du serveur et qui part *très souvent* en live.

**Comment by Equinox4** [comment]
Pour être honnete, on attend la moindre occasion pour faire disparaitre ce thread, il ne doit sa survie que parce que on a beaucoup d'actualités brulantes en ce moment, et que les gens ne peuvent pas s'empecher d'en parler. Personne dans le staff n'a envie de modérer ce thread, alors on ne va certainement pas en faire un canal.

**Comment by NightProg** [comment]
D'accord, merci de vos clarifications, je comprends parfaitement. C'est vrai que des dérapages peuvent arriver  souvent dans ce genre de sujet.

**Comment by GiregL** [comment]
Vous avez qu'a faire l'expérience de le fermer pendant quelques jours, voir si ça revient dans les autres canaux ou pas
Et si ça revient pas, problème réglé pour tout le monde

**Comment by Elanis** [comment]
On a analysé l'activité des discussions depuis l'application du slow mode et hier et la conclusion du staff c'est: ca ne change rien.
On a donc décidé de verrouiller le thread.

Néanmoins, ca ne veut pas dire que *toutes* les discussions HS sont interdites.

Les sujets d'actualités repartent dans #discussions et #detente  *mais* si jamais cela dure trop longtemps, il faudra créer un thread dédié **au sujet en lui même**.

On espère que ca améliorera l'ambiance autour des sujets d'actualité et que la modération sera moins une charge.

Un petit rappel tout de même, car ce n'était pas toujours respecté ici, nous allons enforcer un peu plus le règlement sur ces sujets, et particulièrement la [guideline sur les débats](https://discord.com/channels/323076998576603137/860920579154772018/860921226150412289).

Enfin, il faut se rappeler que NaN est avant tout un serveur d'IT, et même si on ne peut pas empêcher le fait que certains sujets soient discutés, on peut se passer d'autres.
