### ISSUE TITLE
Ce serveur discord pue la merde

### ISSUE THREAD

**Issue by JimmyGaubert** [NotANameServer/discord#193]
J'ai demandé gentillement de l'aide sur ce que je pensais être un serveur d'entraide.
J'ai attendu, n'ayant pas de réponse au bout de 6h je me décide : J'ai osé cross poster ma demande d'aide sur le salon general.. Quelle erreur ! On m'a insulté puis répondu qu'il fallait attendre, je cite "les experts en js" du serveur. Je ne savais pas que le ministère du travail délivrait des titres d'experts en javascript, c'est nouveaux ça ?! Ensuite on m'a proposé de poser ma question à chat-gpt. C'est le pire conseil qu'on peux donner.

Outre les insultes et le lynchage en salon public, je retiens aussi autre chose : LES MEMBRES M'ONT DEMANDÉ DE PAYER POUR AVOIR UNE RÉPONSE A MA QUESTION DANS LE SALON D'ENTRAIDE JAVASCRIPT ????

 Y'a quoi de gratifiant à demander de l'argent aux gens sur un serveur d'entraide ? Sérieusement ce serveur a un soucis.

**Comment by Equinox4** [comment]
Bonsoir,
Le github n'est pas fait pour venir exposer ton mécontentement du serveur, on est pas sur un réseau social ici.
Si tu as quelque chose à dire tu peux mp un membre du staff.
Merci de ne pas polluer d'avantage ce dépot ou ton compte sera signalé.
