### ISSUE TITLE
Ajout de la chaîne de mCoding aux ressources de !courspython 

### ISSUE THREAD

**Issue by CallMePixelMan** [NotANameServer/discord#195]
Hello tout le monde, 

Je ne sais pas si les commandes genre `!courlangage` s'y prettent mais je pense qu'il serait intéressant de mettre en avant des chaînes youtubes de personnes qui offrent régulièrement du contenu de qualité autour d'un langage. En particulier pour le langage Python la chaïne de [mCoding](https://www.youtube.com/@mCoding), pourquoi pas non loin de la section "Articles". 

Pour ceux qui ne connaissent pas sa chaîne, il traite dans un format vraiment digeste et accessible plein de questions propres à Python, à son fonctionnement, à ses lib (async, ASGI, etc.), aux bonnes pratiques professionnelles, etc.

Je pense que c'est une bonne chaîne à mettre en avant car ça permet d'offrir aux néophytes, en plus d'un cours, un moyen de suivre les meilleures pratiques de manière régulière en proposant du contenu YouTube à visionner.

Bonne journée !

**Comment by Julien00859** [comment]
Je suis favorable

https://youtu.be/qUeud6DvOWI?si=mQ4UoBcT-mAiUtQ1&t=394
