### ISSUE TITLE
Erreur dans le texte d'une commande

### ISSUE THREAD

**Issue by Bethoth** [NotANameServer/discord#197]
Comme vous pouvez le voir dans la capture d'écran ci-dessous, il est écrit Benoït Vittupier mais l'auteur se prénomme (assez logiquement) Benoît. C'est une erreur mineure mais ça reste mieux qu'il n'y en ait pas.

![image](https://github.com/user-attachments/assets/d415537b-4e04-486b-9a4b-86eb4157f824)

**Comment by Elanis** [comment]
C'est reglé, merci :)
