### ISSUE TITLE
Ajouter des ressources sur l'accessibilité du web dans !courshtml

### ISSUE THREAD

**Issue by Bricklou** [NotANameServer/discord#198]
L'accessibilité du web reste un sujet très peu abordé dans de très nombreux cours sur le web. Pourtant, il n'en reste pas moins important pour permettre à tous de naviguer au mieux sur le net.

Je propose donc de rajouter des liens vers des ressources parlant de l'accessibilité du web.

Voici quelques exemples de ressources :
- https://w3c.github.io/accessibility-intro/ (EN)
- https://www.w3.org/WAI/ (EN)
- https://design.numerique.gouv.fr/ (FR)
- https://www.youtube.com/playlist?list=PLzwHdQWfGYgaOs3drhozCyHWW4pVO4Skw (FR / vidéo)

**Comment by Equinox4** [comment]
Très bonne idée, c'est une remarque que je fais très régulièrement lorsque j'analyse des sites web conçus par des débutants, mais aussi par des dev plus expérimentés qui ne pensent pas forcément à cet aspect du web.
On pourra également ajouter un lien direct vers les WCAG actuelles https://www.w3.org/TR/WCAG22/

**Comment by Equinox4** [comment]
voila à quoi ressemblerait le nouveau message:

> ### <:langage_html:436841854328242181> Cours sur les langages HTML et CSS
> **📕 Marksheet**
> Cours en anglais sur le HTML et CSS surpassant celui de OC: [Marksheet](<https://marksheet.io>)
> 
> **🎥 Formations vidéo par Grafikart**
> - Formation HTML: [Apprendre l'HTML](<https://www.grafikart.fr/formations/html>)
> - Formation CSS: [Découverte du CSS](<https://www.grafikart.fr/formations/css>)
> 
> **📘 Cours du MDN**
> Cours publié par le MDN sur le HTML: [Les bases du HTML](<https://developer.mozilla.org/fr/docs/Apprendre/Commencer_avec_le_web/Les_bases_HTML>)
> 
> **✨ Qualité et Accessibilité**
> 
> - [Web Accessibility Initiative (WAI)](<https://www.w3.org/WAI/>) (EN)
> - [Web Content Accessibility Guidelines (WCAG)](<https://www.w3.org/TR/WCAG22/>) (EN)
> - https://w3c.github.io/accessibility-intro/ (EN)
> - [DesignGouv site](<https://design.numerique.gouv.fr/ >) (FR)
> - [DesignGouv playlist](<https://www.youtube.com/playlist?list=PLzwHdQWfGYgaOs3drhozCyHWW4pVO4Skw>) (FR / vidéo)
> 
> **📌 Messages épinglés**
> Pensez à regarder également dans les messages épinglés, des ressources y sont listées.
