### ISSUE TITLE
Séparer le canal #github en deux

### ISSUE THREAD

**Issue by SirLynix** [NotANameServer/discord#20]
Actuellement le canal #github sur le serveur prend à peu près toutes les notifications, c'est-à-dire chaque commentaire sur chaque issue et certains membres ont déjà décidés de désactiver les notifications de ce canal, il faut dire que ce n'est pas très lisible.

Je propose deux solutions, la première comme le titre l'indique c'est de séparer le canal en deux, peut-être avoir #github et #github-discussion (et n'avoir les commentaires que dans le canal de discussion).

L'autre solution étant de désactiver les commentaires des issues/PR dans le webhook et de tout laisser sur le GitHub, personnellement je n'aime pas cette solution (je préfère avoir un message sur le serveur à chaque commentaire, quitte à ce que ça soit dans un canal séparé).

**Comment by GiregL** [comment]
J'opte pour la première option perso. Les nouvelles issues passent inaperçues actuellement. Le plus compliqué sera surement de lire les commentaires "dans le bon ordre" mais là a part un canal par thread j'ai pas d'option. Et je doute fortement que quelqu'un veuille un canal par thread 🤢

**Comment by Elanis** [comment]
+1 Pour la premiere option aussi

**Comment by Haldarys** [comment]
Aussi pour la première option, je ne vois pas vraiment l'intérêt d'afficher chaque commentaire ça rend vraiment le channel illisible.
Une idée (sûrement pas possible avec le bot github actuel) pourrait être d'avoir un message de résumé quotidien ou régulier des activités plutôt qu'un message entier par commentaire.

**Comment by GiregL** [comment]
Actuellement c'est un webhook, pas un bot. Je ne crois pas qu'on puisse le régler comme ça

**Comment by SirMishaa** [comment]
> 
> 
> Aussi pour la première option, je ne vois pas vraiment l'intérêt d'afficher chaque commentaire ça rend vraiment le channel illisible.
> Une idée (sûrement pas possible avec le bot github actuel) pourrait être d'avoir un message de résumé quotidien ou régulier des activités plutôt qu'un message entier par commentaire.

Le bot, actuellement, si je ne me trompe pas, ne permet pas (facilement) de faire ça. C'est effectivement possible d'handle le webhook et de le mettre en forme par le bot, mais ça demande un peu de boulot. 

Je vote pour la première solution.

**Comment by Equinox4** [comment]
du coup, comme dit dans #16 , je pense que ça serait bien de juste mettre les ouvertures de PR/issues dans #suggestion, et des laisser les coms dans #github.

**Comment by SirLynix** [comment]
C'est implémenté. Désormais les commits et la création/fermeture d'issues et de PR sera envoyée sur #suggestions (peut-être changer le nom du canal ?), et les commentaires/review seront envoyés sur #github-comments
