### ISSUE TITLE
Ajout d'un nouveau lien pour les libraries/wrappers discord

### ISSUE THREAD

**Issue by Lexedia** [NotANameServer/discord#201]
Depuis [la purge faite par discord](https://github.com/discord/discord-api-docs/discussions/4456) il y a ~2 ans, il y a beaucoup moins de lib répertoriées sur la page https://discord.com/developers/docs/developer-tools/community-resources#libraries

Je propose d'ajouter https://libs.advaith.io à la commande `!devbots` ou a la description du canal `#création-bots-discord`, qui est un comparatif de plusieurs librairies répertorié par langage. ça peut permettre aussi a des gens de découvrir des libs qui peuvent peut-être mieux convenir à leur besoins.

**Comment by Elanis** [comment]
Hello :) C'est ajouté! Désolé du délai, on a du zapper l'issue :p
