### ISSUE TITLE
Un canal pour les contrats freelance ?

### ISSUE THREAD

**Issue by SirLynix** [NotANameServer/discord#27]
Hello,

Côté staff du serveur on reçoit régulièrement des demandes pour poster une recherche de contrat freelance dans #offres, ce qu'on refuse à chaque fois car on préfère privilégier ce canal aux contrats d'embauche.

Néanmoins, je me pose la question, est-ce que ça pourrait pas être intéressant d'ouvrir un second canal (disons #offres-freelance) pour autoriser cela ? C'est une vraie question à laquelle je n'ai pas la réponse, étant donné qu'on a décidé d'interdire cela sans consulter la communauté.

**Comment by GiregL** [comment]
La raison pour laquelle vous aviez décidé ça c'était a cause de l'impossibilité de garantir que les offres soient fiables et pas quelque chose de sous payé / impossible ou quoi que ce soit dans le style des annonces de Codeur.com qui sont souvent foireuses.
Je verrais que deux options :
- Laisser libre court et déléguer le rôle de l'analyse de ces offres aux freelances intéressés
- Contrôler les annonces dans les tickets et s'en remettre a la l'expérience du staff pour déterminer qui est bon ou non

**Comment by GiregL** [comment]
Il me semble qu'un freelance peut être engagé par un particulier comme par une entreprise non?
Si c'est seulement les entreprises, on peut demander le numéro de SIRET de "l'employeur" et une preuve que c'est bien eux.
Si c'est tout le monde, ça va être la misère et le plus simple serait alors de se "dédouaner" et de donner la responsabilité de la chose à l'un ou l'autre. Mais ça je sais pas si c'est possible non plus.

**Comment by Julien00859** [comment]
Je me permet de clôre le sujet (vous êtes libre de le ranimer) comme il n'a pas reçu beaucoup de "traction" depuis qu'il est ouvert.
