### ISSUE TITLE
Augmenter la visibilité pour les langages JVM autres que java

### ISSUE THREAD

**Issue by florentm35** [NotANameServer/discord#31]
Certains utilisateurs du salon java souhaiterais que les autres langages JVM (Kotlin et Scala principalement) soient un peu plus mis en avant, plusieurs idées on été proposés :
- Modifier le message dans #rejoindre-les-canaux par exemple en modifiant `Canal Java` par `Canal Java et JVM (Kotlin/Scala/Clojure)`
- Modifier le nom du channel en #java-jvm ou #java-kotlin-scala-clojure, pour ce point je suis moins d'accord, car le premier reste trop vague et ne parlera absolument pas au débutant, le deuxième est trop long et n'apporte pas grand chose.
- Modifier la description du channel #java pour indiquer qu'il s'agit du canal pour tous les langages JVM et mettre une liste des principaux représentants (java, kotlin, scala, clojure)

A noter que le nombre de messages sur les autres langages JVM reste assez marginal, l'issue est plus la pour discuter de la faisabilité et de l'utilité de c'est modification, personnellement je ne ferais pour l'instant que les points 1 (modification dans #rejoindre-les-canaux) et 3 (modification de la description du chan)

**Comment by SirMishaa** [comment]
Je suis d'accord. 

*Javabien pour moi*.

**Comment by Yberion** [comment]
D'accord pour point 1 et 3, sans avis pour le point 2.

**Comment by Haldarys** [comment]
Je suis d'accord sur les 3 points avec #java-jvm pour le 2. Même si ce n'est pas forcément débutant friendly on y gagne en précision et on ne perds rien à le mettre.

**Comment by Mesteery** [comment]
En vrai, `#java-jvm` c'est bien, et ça perturbe pas vraiment les débutants (il y a quand même `java`), personnellement, ce qui me gène c'est la répétition, mais y aurait pas moyen de faire autrement sans complètement perdre les débutants.

**Comment by Wafelack** [comment]
Peut-être en version complète, `#java-virtual-machine` ? Sinon oui, je suis 100% d'accord.

**Comment by Iltotore** [comment]
> En vrai, #java-jvm c'est bien, et ça perturbe pas vraiment les débutants (il y a quand même java), personnellement, ce qui me gène c'est la répétition, mais y aurait pas moyen de faire autrement sans complètement perdre les débutants.

Cela avait déjà été proposé sur le serveur et je suis toujours en faveur de cette idée.

**Comment by florentm35** [comment]
Au niveau de java-jvm comme j'ai indiqué en interne :
C'est un bon compromis sur l'intention mais je suis plus septique sur l'utilité pratique, a mon avis les gens ne vont pas comprendre que le jvm et pour parler des autres langages jvm

Personnelement je me demande si il vaudrait pas mieux un nom type java-kotlin-scala (qui sont les principaux représentant du chan) même si c'est un poil long et qu'on oublie certain langage

**Comment by Julien00859** [comment]
On l'a renommé java-jvm de manière temporaire jusqu'à ce qu'on trouve un meilleur nom.

**Comment by florentmartin35** [comment]
Reste si possible les point 1 et 2

**Comment by Julien00859** [comment]
Ok pour le point 1 :)

> :langage_java: : Canal Java/JVM (aussi Kotlin, Scala, Clojure)

**Comment by florentm35** [comment]
Pour le point 3 je propose :
Canal pour toutes questions relatives au langage JVM (Java/Kotlin/Scala/...)

:langage_java: !coursjava pour une liste de cours

**Comment by Iltotore** [comment]
> Pour le point 3 je propose :
> ```
> Canal pour toutes questions relatives au langage JVM (Java/Kotlin/Scala/...)
> 
> :langage_java: !coursjava pour une liste de cours
> ```
>  

Attention au pluriel sur `aux langages JVM` mais je suis en faveur de cette description.

**Comment by Elanis** [comment]
![image](https://user-images.githubusercontent.com/7013446/170471397-223b3ba6-2898-4ead-a952-cdf5de64c8b5.png)
![image](https://user-images.githubusercontent.com/7013446/170471459-5e22d1f0-eadd-46de-9397-c4f70a5e022f.png)
