### ISSUE TITLE
Ajouter une commande/règle contre les screen shot

### ISSUE THREAD

**Issue by zazbone** [NotANameServer/discord#32]
Yop!
Beaucoup de nouveaux partagent leur code avec des screenshots de leur écrans ou des photos.

Il faudrait informer sur:
- Le fait que c'est illisible
- Lourd pour rien
- Difficilement éditable/testable par les autres utilisateurs
- (ça donne l'impression d'avoir la flemme de bien présenter son problème)

Une commande me  semble une bonne idée (peut être un rework de !code suffirait)
Pour ce qui est d'une inclusion plus détaillé dans la faq ou les règles me semble pas neccessaire

**Comment by Mesteery** [comment]
https://github.com/NotANameServer/discord/blob/main/faq.md#poster-du-code-code

**Comment by zazbone** [comment]
La commande affiche quand même le lien vers la faq
Qui est pour l'instant bien souvent ignoré
Par rework j'entendais pas plus que l'inline de la faq dans un embed nab

**Comment by Mesteery** [comment]
C'est prévu le rework de certaines commandes. Faudra juste attendre la mise en place du nouveau règlement.

**Comment by Julien00859** [comment]
Up @zazbone est-ce que le nouveau règlement est mieux par rapport à ta demande actuelle ?

**Comment by zazbone** [comment]
Hello, oui du coup avec la maj de !code ça a l'air de suffir

Tu voudrais que je ferme l'issue c'est ça ?

**Comment by Mesteery** [comment]
Personnellement je trouve que `!code` ne parle pas assez explicitement des screens. Par exemple, la dernière fois, malgré plusieurs rappels avec cette commande, la personne n'a pas compris qu'il ne fallait pas envoyer de screens : https://canary.discord.com/channels/323076998576603137/358724375597416449/864447341296615445 (tout commence ici).

**Comment by zazbone** [comment]
Ok effectivement ça pourrait être explicitement dis du coup

Mais il faudrait aussi sans doute faire comprendre que c'est pas juste conseiller. Parce que là il y avait aussi de la mauvaise volonté manifeste. Du coup si c'est pas clair que ça gène tout le monde pas sur que ça arrange ce genre de cas

**Comment by ADVANCEDPATH** [comment]
la commande [reverse order] + {reboot control booster}
