### ISSUE TITLE
Possibilité de refaire un évènement comme la Not A GameJam 

### ISSUE THREAD

**Issue by TNtube** [NotANameServer/discord#33]
Hello !
J'ouvre cette issue pour poser à la fois une question et faire une proposer un événement.
Est-ce possible d'envisager dans l'année une deuxième édition de la Not A GameJam ? Si ce n'étais pas dans vos plans, le travail que demande un tel événement serait-il envisageable ?

Merci d'avance !

**Comment by florentm35** [comment]
Il faut bien voir que ce n'est pas le probleme de vouloir l'organiser mais bien de trouver un organisateur

**Comment by Elanis** [comment]
+1 pour ce que dit Florent, je suis aussi intéressé par une seconde gamejam, j'ai bien aimé la première, mais je n'ai personnellement pas le temps pour l'organiser, et je pense que c'est le cas de pas mal de monde malheureusement :/

**Comment by Elanis** [comment]
Petite mise à jour pour cette issue. J'ai pris le lead pour débuter l'organisation d'une seconde édition de Not a Gamejam. Les news seront postées dans #not-a-gamejam, comme pour la première édition.

**Comment by Julien00859** [comment]
up @Elanis

**Comment by Elanis** [comment]
C'est en route ! cf l'annonce: https://discord.com/channels/323076998576603137/446972878718500874/1019204000752607253

Un google forms a été créé afin de recueillir les avis de la communauté.
