### ISSUE TITLE
la doc de la commande !code est incomplète

### ISSUE THREAD

**Issue by jonathanpoelen** [NotANameServer/discord#42]
Le lien de la commande `!code` pointe sur https://support.discord.com/hc/fr/articles/210298617-Bases-de-la-mise-en-forme-de-texte-Markdown-mise-en-forme-du-chat-gras-italique-soulign%C3%A9, malheureusement cette pas n'indique pas comment mettre en couleur du code.

**Comment by JeanCASPAR** [comment]
J'allais ouvrir une deuxième issue avant de remarquer celle ci 😄

Ça pourrait donner ça :

> Pour les non-connaisseurs de Discord, il existe un moyen de poster du code bien formaté, lisible et coloré. Référez-vous à la documentation de Discord :
>
> https://support.discord.com/hc/fr/articles/210298617-Bases-de-la-mise-en-forme-de-texte-Markdown-mise-en-forme-du-chat-gras-italique-soulign%C3%A9.
>
> Pour ajouter la coloration syntaxique, il suffit de rajouter le nom du langage après les trois accents graves, comme ceci :
> \`\`\`python
> code
> \`\`\`
> La liste des langages supportés est disponible sur https://highlightjs.org/static/demo/.
>
> Si jamais votre code est beaucoup trop long pour tenir en un message ou que vous remplissez votre écran avec, il existe des sites pour poster vos codes. Il vous suffit de copier-coller votre code dans le site et de le sauvegarder, vous serez redirigés sur une page où votre code a été sauvegardé et vous pourrez copier-coller l'URL unique sur Discord.
>
> - https://paste.artemix.org/
> - https://bin.readthedocs.fr/

Ou bien, on pourrait carrément enlever le lien vers la doc qui est assez pauvre en explications sur les blocs de code et présente la syntaxe md générale pour discord, et écrire comment faire direct dans l'embed

**Comment by jonathanpoelen** [comment]
Pour information, j'ai fait un rapport de bug à discord et le dernier message après quelques échanges concernant les blocs de code est:

> Je souhaite vous informer que je transmets dès maintenant votre ticket à notre équipe de développement pour qu'elle l'examine plus en détail. Je vous présentes toutes mes excuses pour la gêne occasionnée et vous tiendrai au courant dès que j'en saurai davantage !

C'était il y a 5 jours, pour le moment je n'ai pas eu plus de nouvelle.

Concernant les codes trop longs, depuis un moment discord dispose d'une fonctionnalité pour ne pas les voir. Ils sont transformés en fichier que l'on peut télécharger et un bouton permet d'en voir une grosse partie du début (généralement tout). Perso, je trouve que passer par un site intermédiaire à plus de contrainte.

**Comment by JeanCASPAR** [comment]
ça ne fonctionne pas sur mobile @jonathanpoelen

**Comment by Julien00859** [comment]
Up @jonathanpoelen as-tu des retours du support de discord ?

**Comment by jonathanpoelen** [comment]
Oui, un message automatique il y a 8 jours pour dire que c'est toujours dans la file d'attente.

Et je viens de voir qu'il faut que y répondre s'il est encore d'actualité... Je n'avais pas vu ><

**Comment by Mesteery** [comment]
Je viens de voir que ce commentaire aurait mieux sa place ici :
https://github.com/NotANameServer/discord/issues/32#issuecomment-899057916

**Comment by Equinox4** [comment]
note: la page a peut-être été mise à jour depuis, mais maintenant la coloration syntaxique est indiquée
