### ISSUE TITLE
Utiliser les threads pour permettre les discussions sur les screenshots ?

### ISSUE THREAD

**Issue by DragonJoker** [NotANameServer/discord#44]
Je viens de voir qu'ils ont mis ça en place sur le discord "Graphics Programming", et ça me semble être une bonne idée ?
S'il y a moyen de ne permettre les discussions qu'en threads ce serait idéal, mais bon.

**Comment by SirLynix** [comment]
J'y ai pensé dès l'introduction des threads, et effectivement s'il y a un endroit où ils conviennent parfaitement c'est dans les commentaires de ce genre de canal.

Je n'ai pas accès à mon ordinateur avant ce WE mais je m'occuperais de mettre à jour quelques messages pour le formaliser, mais en ce qui me concerne vous pouvez déjà faire des threads pour les screenshots / assets / etc.

**Comment by Julien00859** [comment]
Up, ping @SirLynix oublie pas ;)

**Comment by SirLynix** [comment]
En fait c'est fait depuis quelques jours, j'avais juste oublié de fermer l'issue 😅
