### ISSUE TITLE
Modification des couleurs des rôles concernant les langages de programmation.

### ISSUE THREAD

**Issue by CallMePixelMan** [NotANameServer/discord#46]
Bonjour, 
c'est une suggestion toute simple mais je pense qu'il serait intéressant de changer la couleur des rôles de couleur par la couleur que l'on peut trouver sur Github, dans le descriptif des langages utilisés d'un dépôt. Il serait alors -- à mon sens -- plus simple de reconnaitre instinctivement un développeur qui code en un langage X car son pseudo est de couleur Y, la même étant utilisé comme code couleur pour le langage sur Github.

Voilà un exemple de à quoi cela ressemblerait en pratique :
_La conversation est masquée par respect pour les usagers. J'ai choisi cette conversation car on peut retrouver plusieurs couleurs de rôles._
![image](https://user-images.githubusercontent.com/65821351/128518910-c33cd280-b5e6-40d5-ba24-cdcd4c2cf69f.png)

La liste des couleurs disponibles peut être retrouvée ici : https://github.com/ozh/github-colors

En espérant que cette suggestion vous plaise. 😄

**Comment by SirMishaa** [comment]
La couleur de Rust n'est pas jolie du tout :(
![image](https://user-images.githubusercontent.com/42717232/128522598-3e42e188-f185-43dc-a0d0-fc628b6ffcec.png)

**Comment by CallMePixelMan** [comment]
Le choix des couleurs, c'est assez subjectif.. Personnellement je trouve que ça contraste bien avec le font gris de l'interface

**Comment by Elanis** [comment]
Le soucis qu'on a eu avec les multiples tentatives de changement de couleurs, c'est qu'il faut que soit compatible avec les themes clairs, foncés et contrast fort; mais aussi qu'on puisse distinguer les couleurs, et qu'on puisse avoir des couleurs pour les autres rôles non liés à un langage (staff, bot, booster).

De plus, les couleurs de GH, sont approprié à des progress bar, je ne suis pas sur qu'elles le soit totalement pour du texte.

**Comment by SirMishaa** [comment]
Pour le coup, je reste contre. 

Les gens sont habitués à une certaine couleur comme bleu pour le C#, orange pour le Rust, violet pour le Java, jaune pour le Javascript, etc. 

Changer les couleurs n'apporte franchement pas pus de visibilité et risque de perdre les gens. 
Et c'est un peu une galère avec les thèmes foncés / clairs. Là, on a quelque chose qui fonctionne bien.

**Comment by CallMePixelMan** [comment]
@Elanis
> Le soucis qu'on a eu avec les multiples tentatives de changement de couleurs, c'est qu'il faut que soit compatible avec les themes clairs, foncés et contrast fort; mais aussi qu'on puisse distinguer les couleurs les unes des autres, et qu'on puisse avoir des couleurs pour les autres rôles non liés à un langage (staff, bot, booster).
GH a une interface sombre et claire, les couleurs sont faites pour être utilisée, peu importe le thème sélectionné.  

Pour ce qui est des couleurs pour les rôles de staff, le but n'est pas de changer la couleur de tout le serveur, seulement celles des rôles pour les langages. Je viens d'aller jeter un coup d'œil et je ne vois aucun conflit avec les couleurs pour les rôles du staff. 

> De plus, les couleurs de GH, sont approprié à des progress bar, je ne suis pas sûr qu'elles le soient totalement pour du texte.

Je ne trouve pas que ça fasse tache, c'est juste dans le pseudo après tout.

***

@SirMishaa
> Les gens sont habitués à une certaine couleur comme bleu pour le C#, orange pour le Rust, violet pour le Java, jaune pour le Javascript, etc.

Beaucoup des couleurs déjà citées ne changent presque pas (Jaune pour JS, orange pour le Rust -- même si oui, la différence est quand même visible --) Je pense que c'est surtout une question d'habitude après tout, je vois surtout derrière ce changement un sens pratique (et logique).

**Comment by CallMePixelMan** [comment]
Je souhaite revenir sur ma suggestion initiale après les retours négatifs et avoir échangé avec certains membres de la communauté en privé. 

L'idée derrière cette suggestion est de renforcer le lien entre Github et le serveur Discord (étant donné que c'est visiblement la direction vers laquelle le serveur avance, avec les suggestions par Issues Github par exemple).

Je comprends et j'entends parfaitement les critiques, mon but n'est clairement pas de changer l'identité du serveur (certains m'ont dit que c'était les couleurs de NaN, et qu'elles devaient rester ainsi car elles viennent de NaN) mais simplement de donner un lien et une signification plus forte aux couleurs des rôles.

Étant donné que le changement de couleur est un sujet qui a l'air sensible, je suis complètement ouvert à la discussion et aux débats, dans le but de peaufiner cette suggestion. ☺️

J'espère avoir été plus clair sur l'objectif -- selon moi -- de ce changement. 
Bonne soirée 👍

**Comment by Julien00859** [comment]
Hello Pixel, je rejoins les autres pour dire qu'effectivement les couleurs sur discord ont été étudié pour être adapté aux deux thèmes de discord et que nous sommes plutôt habitué aux couleurs actuelle. Je rejoins ton idée pour dire que si les couleurs étaient toute récentes qu'on aurait pu les changer pour suivre la palette de github mais nous sommes dans une situation où la majeure parti des membres *ne fréquentes pas régulièrement github* (soit ils n'utilisent pas git (majorité), soit d'autres dépots comme bitbucket) et sont *attachés* à leur couleur. Moi-même j'ai eu du mal à m'habituer à couleur bleue du staff après être resté pendant 4 ans vert 😉 

Comme je constate qu'il n'y a pas beaucoup de personnes qui abondent dans ton sens, je propose qu'on rejette ta proposition et qu'on clôture l'issue. Est-ce que ça te va ?

**Comment by CallMePixelMan** [comment]
Hey, pas de soucis, je comprends totalement. C'est pas grave, c'était juste une petite feature qui aurait pu être cool selon moi, mais je vous rejoins sur le fait que les couleurs actuelles font le travail. 

Bonne soirée à vous tous !
