### ISSUE TITLE
Utilisation des threads dans le channel #defis pour remplacer #defis-discussions

### ISSUE THREAD

**Issue by Equinox4** [NotANameServer/discord#47]
Ça a été proposé dans #defis-discussions, je l'officialise ici.
On peut configurer les permissions d'un channel pour interdire aux gens d'écrire, sauf dans un thread, du coup ça serait pas mal que les ambassadeurs puissent créer un thread en dessous du défi en cours, dans lequel les gens écriront pour discuter du défi.
Comme ça les nouveaux n'auront plus à chercher le canal #defis-discussion, et les discussions seront bien organisées par défi dans les threads.

**Comment by florentm35** [comment]
Peu d'interet, les messages de #defis-dicution tourne généralement autour du dernier défis uniquement et un channel est beaucoup plus visible et invite beaucoup plus a la discution, de plus il faudrait faire l'effort de rejoindre le thread a chaque nouveau defis, ce qui va rendre la visibilité pire que le chan actuel (en plus les thread ping n'importe comment)

C'est plutot l'acces au channel qui devrait être revue (par exemple dans rejoindre les canaux)

**Comment by Mesteery** [comment]
Je pense que #defis-discussions devrait même être visible par défaut et désactivable dans #rejoindre-les-canaux, pas l'inverse

**Comment by Equinox4** [comment]
https://github.com/NotANameServer/discord/issues/47#issuecomment-894680478
Je suis tout à fait d'accord.
https://github.com/NotANameServer/discord/issues/47#issuecomment-894681997
bof, aucun autre channel ne fonctionne de cette manière, ça ferait juste bizarre imo
