### ISSUE TITLE
Ajout d'un canal Haskell / FP ?

### ISSUE THREAD

**Issue by Wafelack** [NotANameServer/discord#48]
Bonsoir,

Ces derniers temps, les discussions en rapport avec le langage Haskell se sont multipliées ; c'est pourquoi je pense que la création d'un canal centré sur le susnommé langage pourrait être utile.

Qu'en pensez vous ?

Wafelack

**Comment by GiregL** [comment]
J'ai aussi remarqué la multiplication de discussions autour de Haskell, mais surtout de la programmation fonctionnelle en général.
On a eu pas mal de demandes d'aides pour OCaml dans #autres-langages, ainsi qu'Haskell maintenant.

Faire quelque chose de plus général que Haskell seulement serait plus bénéfique je pense.

**Comment by Mesteery** [comment]
Imo, je pense pas que mélanger plusieurs langages dans un même salon soit une bonne aidé. Après je m'attends pas à une grosse fréquentation alors ça devrait passer.

**Comment by GiregL** [comment]
Petite pensée à #javascript-typescript qui en mélange deux
Autre pensée a #java qui ajoute aussi le Kotlin et Scala
ça ne serait pas la première fois qu'on mélange des langages, et en plus, ces canaux sont bien plus fréquentés que ne le serait celui pour Haskell et autres.

**Comment by Mesteery** [comment]
> Petite pensée à #javascript-typescript qui en mélange deux

TS est juste un superset de JS.

> Autre pensée a #java qui ajoute aussi le Kotlin et Scala

Oui.

**Comment by Wafelack** [comment]
> J'ai aussi remarqué la multiplication de discussions autour de Haskell, mais surtout de la programmation fonctionnelle en général.
On a eu pas mal de demandes d'aides pour OCaml dans #autres-langages, ainsi qu'Haskell maintenant.

Je plussoie, un canal `#fs-ml-haskell` ou `#fp` pourrait être encore plus utile.

**Comment by GiregL** [comment]
> Je plussoie, un canal #fs-ml-haskell ou #fp pourrait être encore plus utile.

Au lieu de `#fp`, plutôt `#fonctionnel`

Par contre il faut voir si le canal ne va pas servir de lieu de discussion autour du fonctionnel, plutot que lieu d'entraide. Jusque là la plupart des sujets c'était du troll, des discussions générales ou autres. Les demandes d'aides sont plus rares.
Peut-être par contre qu'un tel canal en attirera.

**Comment by Elanis** [comment]
+1 Pour un canal `#fonctionnel`, y'a pas mal de discussions autour du sujet. Haskell seul ca serait trop limité je pense.

> Par contre il faut voir si le canal ne va pas servir de lieu de discussion autour du fonctionnel, plutot que lieu d'entraide. Jusque là la plupart des sujets c'était du troll, des discussions générales ou autres. Les demandes d'aides sont plus rares.
Peut-être par contre qu'un tel canal en attirera.

L'un empeche pas l'autre imho, `#architecture` par exemple a des discussions theoriques autant que pratique

**Comment by Mesteery** [comment]
Avoir un salon `#fonctionnel` dans une catégorie `Langages` contenant seulement des salons de langages et non de paradigmes ferait plutôt bizarre.

**Comment by Mesteery** [comment]
> L'un empeche pas l'autre imho, #architecture par exemple a des discussions theoriques autant que pratique

Ce salon est dans la catégorie `Technologies`.

**Comment by Tim-ats-d** [comment]
> Avoir un salon `#fonctionnel` dans une catégorie `Langages` contenant seulement des salons de langages et non de paradigmes ferait plutôt bizarre.

Dans la catégorie `autre` plutôt ?

**Comment by Mesteery** [comment]
Cette catégorie n'est pas tellement faite pour ça. Celui-ci pourrait partir dans `Langages` ou sinon `Technologies`.

**Comment by GiregL** [comment]
> L'un empeche pas l'autre imho, #architecture par exemple a des discussions theoriques autant que pratique
Faut voir la tronche des discussions. Les blagues sur les salaires, c'est moyen.

> Avoir un salon #fonctionnel dans une catégorie Langages contenant seulement des salons de langages et non de paradigmes ferait plutôt bizarre.
Je vois pas pourquoi ça serait bizarre, on est pas forcé de faire uniquement des canaux ayant des noms de langages dans la catégorie `Langages`. Un paradigme est tout aussi important.

> Dans la catégorie autre plutôt ?
ça serait un peu hors sujet imho

> ou sinon `Technologies`
Le fonctionnel n'est pas vraiment une technologie non plus

**Comment by Mesteery** [comment]
> Le fonctionnel n'est pas vraiment une technologie non plus

Oui je sais d'où mon `sinon` et https://github.com/NotANameServer/discord/issues/48#issuecomment-897900157.

> Je vois pas pourquoi ça serait bizarre, on est pas forcé de faire uniquement des canaux ayant des noms de langages dans la catégorie Langages. Un paradigme est tout aussi important.

Car c'est carrément incohérent et inconsistant.

**Comment by GiregL** [comment]
> Car c'est carrément incohérent.

Pourquoi se forcer à être cohérent sachant que c'est complètement compréhensible

**Comment by Wafelack** [comment]
Je ne vois pas le problème de mettre `#fonctionnel` dans Langages, il y a bien un salon `#asm`, et il n'y a pourtant pas "l'assembleur", mais "des langages d'assembleur", donc je ne vois pas où se situerait l'incohérence.

**Comment by Mesteery** [comment]
`#asm` c'est bien plus précis qu'un paradigme. Et ça reste un langage, même s'il y en a plusieurs.

Personnellement, je trouve qu'avoir ce canal ici fait très déplacé et incohérent, avec un autre nom ça passerait peut-être mieux.
![image](https://user-images.githubusercontent.com/48163546/129257706-cc921e84-a0d1-47a3-b964-2415f8bbc9c9.png)

**Comment by Wafelack** [comment]
Je ne pense pas qu'il puisse y avoir plus représentatif comme nom, tu aurais des propositions ?

**Comment by Mesteery** [comment]
bah `haskell-ocaml` ?

**Comment by Wafelack** [comment]
Et si j'ai une question sur le PureScript ou le Coq je ne peux pas y aller ?

**Comment by Mesteery** [comment]
Oui, et pleins de langage.

C'est la même cas que `java` d'ailleurs où Scala, Kotlin, et tout autre langage JVM y sont autorisé, et pourtant le canal ne les mentionne pas tous ni porte pas le nom `jvm` (ou `poo` pour exagérer).

**Comment by GiregL** [comment]
Au pire les admins choisiront...

**Comment by Mesteery** [comment]
> Et si j'ai une question sur le PureScript ou le Coq je ne peux pas y aller ? Et si j'ai une question sur une implémentation ou un concept ?

Dis moi, pour poser une question sur la programmation orienté objet, tu vas où ?

**Comment by Wafelack** [comment]
Est-ce que des gens ont manifesté le besoin d'avoir un salon pour parler de POO ?

**Comment by Mesteery** [comment]
Tu esquives la question là.

**Comment by Wafelack** [comment]
Non, je montre simplement que ta question n'a aucun rapport avec ce dont nous parlons.

**Comment by Tim-ats-d** [comment]
Je pense que les développeurs intéressés par la programmation fonctionnelle sont enclins à s'intéresser à d'autres langages fonctionnels un peu moins connus que la trinité Haskell/Ocaml/Lisp et qu'un salon nommé "fonctionnelle" serait plus judicieux.

**Comment by Wafelack** [comment]
Ce serait tellement fonctionnel qu'il faudrait un \`l' et un `e' en plus ?

**Comment by Wafelack** [comment]
>

**Comment by Wafelack** [comment]
Navré, mauvaise manipulation.

**Comment by Tim-ats-d** [comment]
> Ce serait tellement fonctionnel qu'il faudrait un `l' et un `e' en plus ?

J’entendais "programmation fonctionnelle".

**Comment by Mesteery** [comment]
> Non, je montre simplement que ta question n'a aucun rapport avec ce dont nous parlons.

Non, pas vraiment. Ça n'aurait juste aucun sens d'avoir un salon global pour un paradigme dans une catégorie nommé `Langages`. Je rappelle ta question :
> Et si j'ai une question sur le PureScript ou le Coq je ne peux pas y aller ? Et si j'ai une question sur une implémentation ou un concept ?

ce serait applicable pour n'importe quel paradigme. Ce n'est pas parce que les personnes ne se manifestent pas qu'il y en aurait pas besoin. Or, avoir des paradigmes au lieu de langages n'aurait aucun sens dans une catégorie destiné à de l'aide pour des langages. Bref, moi cela me dérange pas plus que ça, hormis l'incohérence.

**Comment by GiregL** [comment]
> Ça n'aurait juste aucun sens d'avoir un salon global pour un paradigme dans une catégorie nommé Langages. 

J'ai presque envie de dire qu'on s'en fout, c'est que des noms...

**Comment by Mesteery** [comment]
Oui mais c'est contradictoire et faux.

**Comment by Wafelack** [comment]
Oui, c'est vraiment de la sodomie de diptères, je ne pense pas que ça ait une grande importance tant que cela reste clair.

**Comment by Mesteery** [comment]
Non, pas ici.

**Comment by GiregL** [comment]
Sinon moi je reste d'avis de laisser le libre choix aux admins - modos.
L'issue est pour l'ajout d'un canal, pas pour en nommer un.
Autant passer au vote si oui ou non on en rajoute un.

**Comment by Equinox4** [comment]
https://github.com/NotANameServer/discord/issues/48#issuecomment-897935295
si tu as des question sur la théorie et le paradigme, tu vas dans #architecture
si tu as des questions sur le langage, tu vas dans l'autre-channel-dont-on-a-pas-encore-trouvé-le-nom

**Comment by nokomprendo** [comment]
`#langages-fonctionnels` sinon

**Comment by JeanCASPAR** [comment]
Je plussoie.
Après parmi les gens qui font du fonctionnel ici, lesquels sont en recherche d'une communauté où poser leurs questions ? (S'entend : n'en ont pas déjà ?)

Je pense que y aura peu de débutants et que le canal ne sera pas forcément aussi actif que #python, si on en crée faut l'avoir en tête et pas le supprimer au bout de deux mois comme ce qui s'est passé pour #rust sur RtD, plus personne n'y parlait parce que les rustacéens étaient tous sur NaN.

**Comment by Julien00859** [comment]
M'est d'avis que l'on peut commencer avec un salon "fourre-tout" `#langages-fonctionnels` dans un premier temps, je pense que les uns et les autres serez d'accord de commencer par partager un espace de discussion commun quelque soit le langage. Ce serait le 1e salon sous la catégorie langage qui serait dédié à un paradigme et non pas à un langage précis mais il me semble que la catégorie technologique est moins adapté. Une petite entorse à ce qui existe actuellement, à savoir pas tout à fait un langage sous la catégorie langage mais au final ce n'est qu'un mot ;)

**Comment by GiregL** [comment]
> lesquels sont en recherche d'une communauté où poser leurs questions ? (S'entend : n'en ont pas déjà ?)

Pour le coup les communautés Haskell francophones sont plutôt rares, ça serait bien d'avoir ça sur NaN.

**Comment by SirMishaa** [comment]
De toute façon, même si le canal parle d'un paradigme de la programmation fonctionnelle, s’il y a des demandes d'aides, il est toujours possible de créer des fils pour éviter de spammer le canal. 

Ou même d'avoir des fils pour une spécificité fonctionnelle, genre Haskell. 

Enfin, je veux dire par là qu'il y a pas mal de fonctionnalité donc ça devrait aller ! :p
