### ISSUE TITLE
Avoir une couleur pour le canal #langages-fonctionnels

### ISSUE THREAD

**Issue by GiregL** [NotANameServer/discord#50]
Hello,

Je me disais que ça serait sympa d'avoir une couleur pour les langages fonctionnels.
La problématique, c'est que le canal représente plusieurs langages. Je pensais donc qu'on pourrait utiliser la couleur du logo du canal qui représente le plus le fonctionnel, ou d'un autre langage sinon. En plus ça rajoutera un peu plus de diversité dans le chat.

Je vous met les color code html pour que vous puissiez avoir un aperçu.
Pour Haskell: un violet ( #453a62 )
Pour OCaml: un orange ( #f08703 )
Pour Elixir: un violet pâle ( #695073 )
Pour Scala / Erlang: un rouge ( #dc322f #8c032f )
Pour F#: un bleu ( #8c032f #8c032f )
Pour les autres langages, mettez en commentaire

**Comment by Julien00859** [comment]
Je ne pense pas qu'ajouter un rôle de couleur (et donc réserver une couleur) pour chacun des langages fonctionnels alors qu'ils sont sous-représentés sur le serveur soit une bonne idée pour le moment. Il y a déjà de la diversité dans les couleurs actuellement du fait que la plupart d'entre vous êtes également des développeurs dans les autres langages colorés.

Il y a d'ailleurs beaucoup plus important à faire que de vous rajouter des couleurs, je ne vois toujours aucun message épinglé et aucune PR pour proposer des nouvelles commandes. En d'autres termes, j'estime que le staff a déjà mis beaucoup en plus pour vous, que la balle est dans votre camp maintenant 😛

**Comment by GiregL** [comment]
Le point n'était pas d'avoir une couleur par langage, même si mon message a un peu la tronche de le demander. C'était de choisir l'une de ces couleurs pour le canal.
Pour les ressources du canal je vais surement m'y attaquer bientôt, du moins proposer quelque chose.

**Comment by wyx0-xyz** [comment]
À la rigueur, faudrait attendre de voir quels langages ressortent le plus de ce salon et ensuite faire les rôles de couleur et pk pas rename le salon avec les langages

**Comment by GiregL** [comment]
Ceux qui vont ressortir ça sera: Haskell et OCaml
C'est les plus courants.

**Comment by Tim-ats-d** [comment]
> je ne vois toujours aucun message épinglé

Le pad est bien documenté en ressources concernant les langages fonctionnels les plus connus et est,
à mon avis, prêt à être épinglé.

> aucune PR pour proposer des nouvelles commandes.

Les idées de commandes viendront avec l'usage, ça serait stupide d'en rajouter pour en rajouter à mon sens.
