### ISSUE TITLE
Permettre aux créateurs de threads d'épingler des messages dans celui ci

### ISSUE THREAD

**Issue by GiregL** [NotANameServer/discord#51]
Tout est dans le titre.

**Comment by SirLynix** [comment]
Il ne me semble pas que Discord le permette, en tout cas je ne vois pas d'option le permettant (même pas dans la configuration d'un thread).

**Comment by GiregL** [comment]
Peut-être par l'intermédiaire de Not a Bot? Autoriser une commande de pin de message du type
`!pin <lien du message>`
seulement au créateur du thread, s'il est possible de le récupérer.

**Comment by Julien00859** [comment]
+1 pour autoriser le créateur d'un thread (ainsi que celui dont le message est devenu un thread) à `!pin <message id>`

**Comment by pauloud** [comment]
Si techniquement on peut avoir des permissions différentes de celles du salon,  on pourrait peut-être tenter l'expérience d'autoriser tout le monde à épingler et désépingler dans les threads ?

**Comment by GiregL** [comment]
ça aurait de forte chances de finir en énorme bordel.

**Comment by pauloud** [comment]
On a qu'à dire que ceux qui veulent tenter le coups mettent un pouce à mon post du dessus, et ceux qui pensent qu'il faut pas essayer mettent un pouce au post de Lezenn.

**Comment by Elanis** [comment]
Les commandes !pin et !unpin sont maintenant disponible pour ce besoin :)
