### ISSUE TITLE
Ressources sur github

### ISSUE THREAD

**Issue by arkena00** [NotANameServer/discord#52]
Salut,
Ce serait pas mal d'avoir une liste des ressources liés aux chans ou autre sur des pages sur le github et de pin ça dans les salons, ce serait beaucoup plus pratique à lire que sur discord.

**Comment by Elanis** [comment]
+1, on a eu cette discussion pour #game-dev en particulier, ou la liste des ressources/outils pourrait vite monter. Je pense qu'épingler le lien vers un .md ici serait pas mal du coup

**Comment by SirMishaa** [comment]
Je pense qu'il serait temps de proposer le site officiel de notaname avec des choses comme les ressources, les membres, les éventments, etc... On est quand même le plus gros serveur francophone de programmation...

**Comment by SirMishaa** [comment]
@SirLynix

**Comment by Elanis** [comment]
Pourquoi ne pas générer des github page avec ce repo ? On aura toutes les infos du serveur et plus sur un site au moins, et sans avoir aucune maintenance du côté du dev.

**Comment by Mesteery** [comment]
> 
> 
> Je pense qu'il serait temps de proposer le site officiel de notaname avec des choses comme les ressources pour les différents langages techni, les membres, les éventments, etc... On est quand même le plus gros serveur francophone de programmation...
> 
> On peut imaginer un site collaboratif ou l'on peut partager des deb blog post, des messages de recrutement qui soit automatiquement forward, ce genre de petite chose.
> 
> Et franchment, avec un deisgn moderne et simple, c'est fait en un weekend avec deux-trois devs.
> Je ne sais pas si certains peuvent être intéressés ? Le projet serait sur NotANameServer/website dans un répo.

On en a déjà discuté dans l'ambassade, cf. NaH.

**Comment by SirMishaa** [comment]
Pour le site via Github Pages, j'ai réalisé une issue #53

**Comment by Julien00859** [comment]
https://github.com/NotANameServer/Not-a-Hub
