### ISSUE TITLE
Cohérence de genre dans le paragraphe sur la sécurité informatique dans #guidelines

### ISSUE THREAD

**Issue by Nolent** [NotANameServer/discord#55]
`Il n'y a personne qui est à la fois habitué, experte reconnue du domaine et qui voudrait devenir ambassadeur d'un canal sécurité.`

HabituéE ou expert, je ne sais pas où est la faute mais y'a un problème de cohérence de genre

**Comment by Elanis** [comment]
Au niveau des sonorités, pour moi c'est `habitué, expert reconnu`. Et grammaticalement, il me semble que le "qui" est neutre ici, ce qui validerait cette orthographe.

Je laisse les autres me corriger si je dis des conneries.

**Comment by pauloud** [comment]
Je ne crois pas que ce soit le "qui" qui neutralise. On dirait "Il n'y a aucune fille qui est/soit  idiote ici " (les deux modes sont admis corrects selon le degré de certitude) 
En fait si on analyse en diachronie, "personne" est à l'origine un nom féminin seulement mais dans l'emploi d'aujourd'hui de "personne" pour dire "l'absence de personne", avec ou sans le "ne" devant, "personne" est neutre. 
(Pas de source, mais j'ai eu de très bon résultats en grammaire à la fac)

**Comment by Elanis** [comment]
Cette issue a été traitée et peut être fermée du coup je pense @Julien00859 , @SirLynix
