### ISSUE TITLE
Channel golang

### ISSUE THREAD

**Issue by Swiiz** [NotANameServer/discord#57]
Ajouter un channel golang

**Comment by GiregL** [comment]
On a déjà eu un canal pour du Go il me semble, il était trop peu actif.
Sinon on ne voit pas souvent passer de demandes dans #autres-langages, je doute que ce soit assez pour alimenter un canal entier.

**Comment by Julien00859** [comment]
Actuellement il n'y a que quelques questions par semaines dans le salon #autre-langage. À titre personnel je trouve qu'il n'y a pas encore assez d'activité que pour devoir isoler ces discussions ailleurs.

**Comment by Swiiz** [comment]
Ok j'étais pas au courant merci
