### ISSUE TITLE
Ajout d'une référence pour la commande !courscpp.

### ISSUE THREAD

**Issue by DaimyoHub** [NotANameServer/discord#58]
Cela fait déjà quelques semaines que le fameux livre _Le guide du C++ moderne – De débutant à développeur_ de Mehdi Benharrats et Benoît Vittupier est sorti. Je pense que nous sommes tous d'accord pour dire qu'il est tout à fait judicieux d'ajouter ce livre à la courte liste de références pour l'apprentissage du C++; d'autant plus que Primer commence à se faire vieux.

Le lien vers une plateforme pour acheter le livre: https://livre.fnac.com/a14868645/Mehdi-Benharrats-Le-guide-du-C-moderne-De-debutant-a-developpeur

**Comment by SirLynix** [comment]
Ça a été fait il y a un moment, je ferme. Tu peux rouvrir si le format actuel ne convient pas.
