### ISSUE TITLE
C++ TL;DR news 5 (CppCon)

### ISSUE THREAD

**Issue by GuillaumeBelz** [NotANameServer/discord#62]
Précédent : https://github.com/NotANameServer/discord/issues/34

Tiens, je n'ai plus les droits ici :) @SirLynix Autorisez au moins de pouvoir ajouter des tags et assigner une issue a quelqu'un. Et plus généralement, plus vous limiterez les droits ici, moins vous aurez de gens qui contribueront.

**Comment by SirLynix** [comment]
Pas sûr de voir comment je peux autoriser les membres à rajouter eux-mêmes leurs propres labels, je n'ai pas trouvé d'option pour ça.

**Comment by GuillaumeBelz** [comment]
Je ne vais pas faire d'article sur la CppCon. Pas assez de choses intéressantes.
