### ISSUE TITLE
Ajout d'une reconnaissance du mauvais canal à NotABot

### ISSUE THREAD

**Issue by Zu1p0** [NotANameServer/discord#65]
Salut tout le monde, je propose ici une solution partielle au problème des mauvais canaux dans le serveur.

Pour les nouveaux arrivants, en effet, on ne compte plus le nombre de messages dans les mauvais canaux, notamment #discussion, souvent à propos d'un problème dans une langage de programmation (#python, #cpp...) ou une technologie (#bots-discord, #hardware...).

Dans la majorité des cas, en général, une ou plusieurs personnes dévouées de la communauté répondent assez rapidement, en répondant par exemple "#rejoindre-les-canaux --> #python", messages pas forcément très compréhensible.

Ainsi, je propose l'ajout d'une fonctionnalité à NotABot, qui détecterai les messages mal placés, et répondrai en conséquence.

Dans un premier temps, je propose de la cantonner à #discussion et #détente, pour un élargissement dans un second temps.
La détection des mauvais messages se feraient par la recherche de mots-clés, comme "problème", "python", "aide", ... qui, si un certain nombre sont présents, déclenchent un message de NotABot du genre :

"Etes-vous sur d'utiliser le bon canal ? 
Tous les canaux destinés à des langages de programmation / des technologies sont accessibles via #rejoindre-les-canaux."

Dans un second temps, il serai aussi possible d'implémenter une réponse personnalisé selon le message : une détection du mot clé "python" (en plus d'autres, bien entendu") déclencherai un message : 

"Etes-vous sur d'utiliser le bon canal ? 
Le canal #python est destiné aux question à propos de celui-ci"

Cela pourrai marcher avec tous les canaux invisibles par défaut.

Bref, bonne chance pour lire mon pavé :sweat_smile:, n'hésitez pas à dire ce que vous en pensez ci-dessous, et pourquoi pas implémenter cette fonctionnalité à NotABot !

**Comment by x0rld** [comment]
Ça serait trop chiant à gérer les faux positifs je pense

**Comment by Zu1p0** [comment]
Même si plusieurs mots-clés seraient demandés ? Pas sûr

**Comment by pauloud** [comment]
A explorer a priori, si on paramètre ce robot que pour les canaux visibles par défaut en adaptant éventuellement les mots-clés pour chacun d'entre eux pourquoi pas

**Comment by Julien00859** [comment]
Je suis contre. Il y a un investissement minimum obligatoire pour chaque membre qui rejoint le serveur. Développer une solution pour automatiquement spammer les salons sur base de certains mots-clés va juste être chiant et inutile.

Déjà les faux positifs, on va juste passer notre temps à devoir raffiner la tolérance du bot pour qu'il arrête d'envoyer des messages à chaque fois qu'un certain mot clé n'apparaisse. On a autre chose à faire.

Ensuite pour les vrais moments où le message serait utile, il s'avère que les nouveaux ne lisent **jamais** les messages du bot. Si il n'y a pas un humain qui introduit le bot:

>Tu peux suivre la recommandation du bot ci-dessous:
> !ask

alors le gars *ne lit juste pas le message*. Automatiser l'envoie ne va servir à rien car de toute manière si ils n'ont pas une interaction humaine ils ne font rien.

Il faut vous rendre compte que les gars qui débarquent et qui ne savent pas utiliser #rejoindre-les-canaux sont les mêmes qui ne savent pas se débrouiller par eux-mêmes, ne savent pas faire de recherche sur internet et encore moins lire une documentation. Mon avis sur la situation est que vous devez juste les ignorer. Si ils ne sont pas foutus d'investir le minimum de temps pour s'intégrer au serveur alors ce n'est pas à vous de faire des efforts pour les aider.

Force m'est de constater que les différentes commandes !ask, !code, ... servent surtout de défouloir aux membres habitués plutôt qu'aux noobs.

**Comment by Equinox4** [comment]
> Même si plusieurs mots-clés seraient demandés ? Pas sûr

Me semble qu'on avait déjà eu une suggestion semblable, et on en était arrivé à la conclusion que selon le contexte, il n'est pas toujours possible de différencier une demande d'aide concernant un langage de quelqu'un qui utilise les même mots mais pour dire autre chose.

Je suis globalement d'accord avec ce que dit Lazor, même si pour nuancer:

> Mon avis sur la situation est que vous devez juste les ignorer

Malheureusement, ce n'est pas possible, car la personne va alors poster tout son code dans #discussion et se demander pourquoi personne ne lui répond.

> Force m'est de constater que les différentes commandes !ask, !code, ... servent surtout de défouloir aux membres habitués plutôt qu'aux noobs.

Pas vraiment un défouloir, c'est juste que ces commandes ont été créées parce que cette situation arrive fréquemment, et c'est fatiguant de répéter la même chose à la longue, donc forcément, au bout d'un moment, on va pas toujours prendre la peine de rédiger un message et on va juste balancer celui du bot.

**Comment by Zu1p0** [comment]
C'est vrai que je n'ai pas beaucoup d'expérience dans la classification de texte, je ne me rend pas sans doute compte de la difficulté de mettre en place cette fonctionnalité : je proposais ça comme ça après une énième fois à rappeler le même message :sweat_smile:

**Comment by guess27-proto** [comment]
Je me permet de transférer le message que j'ai posté sur le serveur discord en rapport avec cette issue :

Alors je me permet juste une remarque. C'est vraiment intéressant comme idée cependant pour le réaliser ya 2 solutions principalement.

La première qui consiste à rédiger un système de black list qui lorsque qu'elle détecte un mot ou plusieurs (faut crée un algo qui fait des estimations par exemple une note pour chaque mot ex : "le mot clé python dans canal js vaut 1, le mot clé base de données vaut 2 etc... et à la fin on fait un calcul qui donne une note de confiance si elle dépasse un seuil la personne est invité à poser ça question ailleurs) mais le problème de faux positif comme il a était dis sur GitHub est important car ont se base uniquement sur des mot clé pas sur le sens de la phrase. Cependant ça serait le méthode la plus simple à mettre en place et aussi la plus légère niveau utilisation cpu sur le serveur

la deuxième solution fait appelle à l'IA et notamment à l'introduction d'algorithme en lien avec le TAL et c'est beaucoup plus technique à mettre en place et surtout l'utilisation cpu sera plus importante.

**Comment by Julien00859** [comment]
Hello @guess27-proto j'ai bien lu ton message et je m'excuse, nous avions décidé de rejeter l'idée et j'ai oublié de fermé l'issue.
