### ISSUE TITLE
Détection des bots

### ISSUE THREAD

**Issue by Gawaboumga** [NotANameServer/discord#66]
Hello,
Proposition bête pour détecter les bots, voir si un utilisateur a posté le même message sur différents canaux différents. Éventuellement:
- Nombre de canaux différents.
- Mots-clefs (discord, crypto, btc, ...).
- intervalle de temps.
=> ban

**Comment by x0rld** [comment]
steam,csgo ça marche bien aussi comme mot-clefs

**Comment by rurueuh** [comment]
Le fait de poster un lien sur plusieurs chanels dans un temps très reduit

**Comment by Julien00859** [comment]
Voila une petite compilation des messages qui ont été flag. Je compte m'attaquer à Lua ce weekend pour proposer une fonctionnalité auto-mute dans NaB. J'ai remplacé les liens pour ne pas leur faire de la pub.

> airdrop discord nitro by steam, take it https://example.com

> @​everyone Free distribution of discord nitro for 3 months from steam!
> https://example.com

> Steam is giving away free discord nitro, have time to pick up at my link https://example.com before the action is over.

> @​everyone
> A free Discord Nitro | Steam Store Discord Nitro Distribution.
> Get 3 month of Discord Nitro subscription. The special offer ends Now 11, 2021.
> With Nitro you are able to personalise your profile, screen share in HD, upgrade the emojis and much more.
> Click the link below to get yours!
> https://example.com

> @​everyone
> Free Discord Nitro AirDrop from Steam!
> Share your screen in HD!
> Collect or create your own custom and animated emoji!
> Support the server and let everyone know about your support!
> https://example.com

> Steam is giving away free discord nitro, have time to pick up at my link https://example.com before the action is over.

> @​everyone Free gift discord nitro for 1 month for you! https://example.com

> this gift is for you bro https://example.com

> @​everyone Lol, jahjajha free discord nitro for 3 month!!
> https://example.com

> Steam Store Discord Nitro Distribution.
> Get 3 month of Discord Nitro subscription. The special offer ends Oct 1, 2021.
> With Nitro you are able to personalise your profile, screen share in HD, upgrade the emojis and much more.
> Click the link below to get yours!
> https://example.com

> Discord Nitro for Free - Steam Store
> Discord nitro distribution
> Get 3 Months of Discord Nitro. Offer ends October 11, 2021 at 11am EDT. Personalize your profile, screen share in HD, upgrade your emojis, and more!
> https://example.com

> @​everyone
> Discоrd Nitrо fоr Frее - Steаm Stоre
> Discоrd nitrо distributiоn
> Get 3 mоnths of Discord Nitrо. Оffer ends September 31, 2021 at 11 am EDT, Persоnalize your profile, screen share in HD, upgrade yоur emоjis, and mоrе!
> https://example.com

> 🎃 Woo! Halloween is coming.
> And there is Discord Halloween's giveaway!
> — https://example.com —
> Get free Discord Nitro from Steam!
> Just link your Steam on this site and get the gift. @​everyone

**Comment by SirLynix** [comment]
Pour information, je sais déjà comment régler ce problème en étendant le module anti-raid de NaB, je suis juste incroyablement occupé avec mes cours en ce moment.

Actuellement le module anti-raid est déjà capable de virer le spam avec des paramètres assez simples (grosso-modo il auto-mute si X messages ont été postés dans une fenêtre de Y secondes, ces valeurs sont réglées sur 6 messages en 2 secondes sur NaN actuellement).

L'idée serait d'étendre ce système et de ne pas compter un certain nombre de messages sur X secondes, mais un score à ne pas dépasser. On garderait un message = score de 1, mais on pourrait dire qu'un message contenant un lien aurait un score de 2 (et donc là il suffirait de spammer trois messages contenant des liens en six secondes pour trigger), on peut ensuite être plus spécifiques et dire qu'un message contenant "free nitro" ou "free Discord Nitro" possède un score de cinq (deux messages = mute), etc.

C'est assez simple à mettre en place, et je m'en occuperais dès que j'ai le temps, mais je dois faire passer le taff avant tout (et je suis assez short à ce niveau).

**Comment by SirLynix** [comment]
Bon du coup j'ai eu un peu de temps, et le fait d'avoir décrit le fonctionnement plus haut a aidé, j'ai implémenté un truc ultra rapide dans NaB, c'est pas configurable et on peut faire mieux mais ça devrait déjà bloquer la grosse majorité.

Du coup ça va virer les messages du genre et auto-mute le membre de façon permanente avec une alerte de modération (jusqu'à ce qu'un admin passe par là pour décider de ce qu'il faut faire, notamment pour gérer les potentiels faux positifs).

**Comment by Julien00859** [comment]
Voila un tableau qui récapitule la fréquence d'occurrence de différents mots clés dans chacun des messages de spam connu de NaN.

![image](https://user-images.githubusercontent.com/8208953/140612773-ec065341-3691-41ac-8cfd-1a5dd38cc464.png)

Le tableur au format libre office : [discordspam.ods](https://github.com/NotANameServer/discord/files/7490610/discordspam.ods)

Récapitulatif:

| mot clé | occurrence |
| ------- | ---------- |
| https://example.com | 20 |
| nitro | 17 |
| discord | 17 |
| steam | 15 |
| free | 12 |
| 3 months | 7 |
| away | 4 |
| gift | 3 |
| airdrop | 3 |
| cs:go | 1 |

**Comment by IAMISSAM** [comment]
Pourquoi @everyone est pas compté ? Ça a l'air d'être un mot clé important pour la détection

**Comment by Julien00859** [comment]
Bien vu, j'ai edit mon message pour l'inclure :)

**Comment by Julien00859** [comment]
Il est à noter qu'il n'y a presque pas de recoupement entre `3 month` (sans s), `away`, `gift` et `airdrop`. En faisant un OR inclusif sur ces 4 mots, j'obtiens un hitrate de 85% (17/20), les trois derniers messages sont hit par les autre mot-clés avec 50%+ hitrate.

**Comment by Equinox4** [comment]
> Voila un tableau qui récapitule la fréquence d'occurrence de différents mots clés dans chacun des messages de spam connu de NaN.

Il est cool ton tableau, par contre il y a des anomalies, par exemple la ligne 10, on voit que le message contient "Nitro for Free", mais les colonnes "nitro" et "free" sont à false. Ne pas oublier d'ignorer la casse ;)

**Comment by Equinox4** [comment]
ah non, ils sont plus malins que ça, sur la dixième ligne, le "o" de "nitro" est une lettre de l'alphabet cyrillique, donc le mot n'est pas détecté. (et pareil pour "Free", les "e" ne sont pas des "e")
Je ne sais pas comment on pourrait contrer ça :thinking:

**Comment by Julien00859** [comment]
Je suis au courant, cf: https://discord.com/channels/323076998576603137/378187529473622026/906570831226875955

**Comment by Julien00859** [comment]
https://github.com/DigitalPulseSoftware/NotaBot/commit/2b90793f7818b8209abf350bf4936807bcacf3d1
