### ISSUE TITLE
Création d'un bot discord communautaire

### ISSUE THREAD

**Issue by SirMishaa** [NotANameServer/discord#67]
Un bot par la communauté, pour la communauté. 

Actuellement, il y a beaucoup de demande d'ajout et d'amélioration concernant le bot
- #23 
- Possibilité de créer des canaux vocaux temporaire facilement (je ferai une issue)
- Ajouter les nouvelles fonctionnalités, comme les boutons natifs de discord là où cela est nécessaire
- Rework du système pour rejoindre les canaux via un système plus simple et moderne (voir [screen](https://i.imgur.com/HPjBNUB.png), je ferai également une issue) 
- ...

Le système actuel ne convient pas / peu, que ce soit en termes de structure, de documentation, ou de technologie. (Je ne blâme pas la techno, je dis juste ce qu'il en est). Même si pas mal de personne semble vouloir contribuer à l'amélioration du bot, généralement, c'est quelque chose qui est peu fait, peut être compte tenu du fait de la difficulté à comprendre le code et la structure existant. 

C'est pour ça que je propose la création d'un nouveau bot qui serait réalisé par la communauté, dont la technologie serait débattue et votée. Compte tenu des responsabilités de ce dernier, je veux bien review chaque PR (avec éventuellement un membre du staff, comme Lazor) avant qu'elle passe en production sur le serveur, afin d'éviter une injection de code arbitraire ou une mauvaise pratique par exemple. 

Les fonctionnalités à y inclure seront d'abord débattues dans une issue, ici, avant d'être accepté par l'administration et implémentée sur le bot par la suite. Les ressources pour contribuer au bot serait sur le répo, avec une bonne documentation et un guide sur les étapes pour proposer du code pertinent et correct. 

Je pense vraiment que ça peut être intéressant pour pas mal de personne qui veulent contribuer dans l'open source, en plus de pouvoir faire évoluer les possibilités sur le serveur. 

#### Points importants à surveiller
Pour moi, ce serait globalement une bonne chose, même s'il faut faire attention aux points suivants : 
- Les nouvelles fonctionnalités **doivent** être d'abord validées sur un ticket, ici
- Les contributions doivent être review, le code doit rester un minimum qualitatif (documentation dans le code, explication.) 
- Des explications sur la structure et sur la façon de contribuer doivent être fournies
- Chaque release est vérifiée par un membre de l'administration (pour des raisons de sécurité, avant de passer en prod) 

N'hésitez pas à laisser vos avis en commentaire ! 
Merci pour la lecture

<hr>

♦️ Aussi, **il ne s'agit pas de débattre de la technologie derrière le bot ici**, cela serait fait dans une autre issue si l'idée plaît et si l'administration est d'accord.

**Comment by mdevolde** [comment]
Je suis motivé à y contribuer si l'administration est d'accord et si le langage choisi est dans mes cordes :)
Et globalement, je suis d'accord avec le système de check du code qui est proposé par la communauté pour rester sur un projet avec un contenu qualitatif.

**Comment by Equinox4** [comment]
je reporte ici une partie du com que j'ai laissé sur NaN:
Même si j'admets que la technologie utilisée actuellement ne me sied guère, et freine ma contribution à NaB, je trouverais personnellement plus interessant de chercher à améliorer l'existant, le bot actuel fonctionne plutot bien et est deja établi dans pas mal de serveurs, ça serait dommage de perdre ça.

**Comment by SirMishaa** [comment]
Lynix va faire une documentation.

Nous avons gagné la bataille, mais pas la guerre. 
![image](https://user-images.githubusercontent.com/42717232/141658757-d6b1d136-19de-4cef-af75-cd52ee5efa42.png)

**Comment by Elanis** [comment]
Au final, le developpement de NaB est plus actif qu'auparavant, l'idée d'un autre bot semble s'eloigner encore plus. Je ferme
