### ISSUE TITLE
Renommer le canal architecture et deplacer systeme-et-reseau

### ISSUE THREAD

**Issue by florentmartin35** [NotANameServer/discord#68]
### **Contexte :**
Il arrive d'avoir des questions infra/reseau dans le channel architecture
### **Proposition :**
-Déplacer systeme-et-reseau juste en dessou de architecture
-Rennomer architecture en architecture-logiciel ou architecture-dev

C'est deux points permetraient plus simplement de s'orienter vers le bon canal.

**Comment by Julien00859** [comment]
Tu veux bien mettre ici un lien vers un message problématique ? Est-ce que c'est un problème courant ou bien ça n'arrive qu'une fois toutes les 2 lunes ? Est-ce que les messages en question étaient des questions relatives à l'architecture réseau d'une application du genre "micro-service vs monolith" ?

**Comment by florentmartin35** [comment]
Tu as de base peu de message de base dans le canal, je dirait 1 message/discution sur 10 qui est hors sujet et je dirait un bon 50% qui sont lié a du système ou du hardware (toutes les éstimations son au doigt mouillé) voici quelques exemples de message : 
-https://discord.com/channels/323076998576603137/553130821603819530/914463629280161812
-https://discord.com/channels/323076998576603137/553130821603819530/904352723783282718
-https://discord.com/channels/323076998576603137/553130821603819530/903765626676465744
-https://discord.com/channels/323076998576603137/553130821603819530/897139456547635260

Apres le but est surtout de rendre le canal plus claire facilement, il n'y a pas de probleme bloquant actuellement

**Comment by Elanis** [comment]
J'ai remarqué aussi à plusieurs reprises que les questions dans architecture sont assez souvent des questions d'infra/réseau. C'est courant malgré la description du canal.
#architecture-logicielle me semble une bonne idée

**Comment by Project-BAM** [comment]
Bonjour,

Je ne suis pas vraiment d'accord, on parle d'un salon présent dans une catégorie à coté de Database / Hardware / Support-Technique / Système & réseaux.
Les règles ne décrivent même pas ce qu'il doit contenir, donc aujourd'hui il remplis correctement son rôle, c'est tout ce qui ne passe pas dans les autres salons de la catégorie.

Je suis conscient que c'est un discord orienté programmation, une catégorie par langage n'est pas de trop.
Par contre, c'est difficile de faire du salon monolithique sur les salons d'infrastructures.
Il y a autant besoin de salon comme :
- architecture logiciel, pour définir si tel lib de Python Back-end + Java Front est plus adapté.
- infrastructure, pour débattre des best-practices sur un cluster serveur web Apache ou  Tomcat + BDD MySqL ou autre + GUI utiles pour rendre l'écosystème plus performants. 

![image](https://user-images.githubusercontent.com/37377720/143785646-d16d1135-4faa-4507-aa72-0980bd1ad8e2.png)

**Comment by Elanis** [comment]
> Les règles ne décrivent même pas ce qu'il doit contenir, donc aujourd'hui il remplis correctement son rôle, c'est tout ce qui ne passe pas dans les autres salons de la catégorie. 

La description devrait être suffisante, pour rappel, c'est:
> Une question non liée à un langage ? Une discussion sur un principe de programmation ou d'architecture ? Bienvenue dans votre demeure.

Mais malheureusement, on le voit avec des tas de salons, les gens ne lisent pas la description de salon, le renommage est une solution à mon avis ici pour lever l'ambiguité

**Comment by Project-BAM** [comment]
**Une question non liée à un langage ?** Une discussion sur un principe de programmation **ou d'architecture ?** Bienvenue dans votre demeure.

Je suis d'accord, il y a ambiguïté, aussi bien par le nom, la définition ou la proximité avec les autres salons de la catégorie.
Modifié la description pour être clair et mettre à jour le message dans rejoindre les salons, me semble pas mal.

**Comment by pauloud** [comment]
J'approuve le renommage et le déplacement, 
Je trouve que "une question non liée à un langage" c'est pas très clair, du moins pour moi qui n'ai pas énormément d'expérience mais qui prend le temps de lire les descriptions (je ne suis jamais trop sûr du fait qu'une manière de raisonner soit liée ou  non à un langage ) peut-être que "une question sur la conception de votre application" est mieux.

**Comment by Julien00859** [comment]
Le vrai problème est que le salon architecture (ainsi que hardware) ne sont pas "protégé" par un rôle. Je pense qu'en activant un rôle dans #rejoindre-les-cannaux on va éviter tous les faux-positifs.

**Comment by florentm35** [comment]
Tu as de forte chance au passage de tué le canal architecture qui n'est déjà pas très peupler alors qu'il est public, la question serait ne faudrait-il pas plutôt retirer le canal et rediriger dans discutions ?

**Comment by Iltotore** [comment]
> Le vrai problème est que le salon architecture (ainsi que hardware) ne sont pas "protégé" par un rôle. Je pense qu'en activant un rôle dans #rejoindre-les-cannaux on va éviter tous les faux-positifs.

Je suis d'accord avec florent. Je pense qu'il faudrait laisser le canal ouvert à tous car finalement l'architecture logicielle, c'est quelque chose d'assez vaste et généraliste. Peu importe le langage, le sujet reste pertinent pour tout le monde et comme l'a fait remarquer florent, passer le canal sous grade risque d'entrainer une chute de l'activité.

**Comment by florentm35** [comment]
Nouveau cas :
https://discord.com/channels/323076998576603137/553130821603819530/918416400706568212

**Comment by Julien00859** [comment]
Désolé, je change pas le nom de la catégorie pour miiro

Quand un chef de projet parle avec un chef de projet:

![](https://www.commitstrip.com/wp-content/uploads/2014/11/Strip-les-PMs-qui-causent650-final.jpg)

**Comment by DrTableBasse** [comment]
Honnêtement, je pense que le salon architecture devrait, à mon sens, disparaître et rediriger toutes les personnes posant une question lié à ça dans un salon adéquate. Je m'explique.

En informatique, vous le savez tout comme moi, mais l'architecture peut être lié à un logiciel, un parc réseau ou bien même à du hardware, je pense que ramener les personnes dans ces salons serait sans doute la meilleure option à l'heure d'aujourd'hui. Même si il y a une description, qu'on soit honnête, énormément de personnes passent à coté, même si c'est pas correcte vis à vis du serveur. 
Dans la mesure où on souhaite garder ce salon, je pense qu'ajouter un réaction rôle à ce dernier serait très pertinent et de renvoyer les personnes dans d'autres salons si besoin est.

**Comment by Elanis** [comment]
Je suis pas fan de l'ajout d'un rôle perso, c'est un bon moyen pour tuer le peu d'activité legit qu'il y a dans ce channel imho. Je pense que renommer #architecture-logicielle serait suffisant à stopper la confusion avec l'architecture dans le sens de systèmes-et-réseaux

**Comment by Julien00859** [comment]
@SirLynix go ajouter `-dev` en suffix au salon.

**Comment by DrTableBasse** [comment]
> Je suis pas fan de l'ajout d'un rôle perso, c'est un bon moyen pour tuer le peu d'activité legit qu'il y a dans ce channel imho. Je pense que renommer #architecture-logicielle serait suffisant à stopper la confusion avec l'architecture dans le sens de systèmes-et-réseaux

Si on fait une architecture logicielle, faudrait aussi, peut être, voir pour un salon #architecture-réseau

**Comment by SirLynix** [comment]
> @SirLynix go ajouter `-dev` en suffix au salon.

Fait.
