### ISSUE TITLE
Modification de la couleur des rôles.

### ISSUE THREAD

**Issue by Walimouche** [NotANameServer/discord#69]
Hey ! J'ai eu une p'tite idée tout à l'heure en choisissant mon rôle sur le serveur :

Faire correspondre la couleur des rôles d'un langage avec celle sur GitHub (je sais pas si j'ai été compréhensible mais voici un exemple) 
![image](https://user-images.githubusercontent.com/81018485/146679921-839d3857-5c0e-4ab7-ab50-b2d7a13d86a2.png)
ici le rôle C# a une couleur (random), ce que je propose c'est que la couleur du rôle soit la couleur de ce-dernier sur GitHub. 

Dans cet exemple, le rôle aurait cette couleur 
![image](https://user-images.githubusercontent.com/81018485/146680028-cb6ab63e-6d38-4936-a50f-9a214934d180.png)

Je propose donc que pour chaque rôle il ait "sa couleur GitHub" (si la proposition est acceptée je me chargerais de collecter les codes couleur des langages)

PS : Tant qu'on y est, attribuer la couleur "officielle" nitro boost (#f47fff) au rôle des boosters ?

**Comment by SirLynix** [comment]
Personnellement je n'ai rien contre

**Comment by x0rld** [comment]
ça avait pas déjà été proposé et refusé de mettre les couleurs github ?

**Comment by Elanis** [comment]
Hello, cette conversation a déjà eu lieu il y a quelques temps, et il en était conclu que c'était le bordel de changer l'existant: https://github.com/NotANameServer/discord/issues/46

**Comment by SirMishaa** [comment]
Refusé

La couleur de Rust n'est pas assez jolie : https://github.com/NotANameServer/discord/issues/46#issuecomment-894285375

:Kappa:

**Comment by Walimouche** [comment]
Je comprends (c'est vrai que j'aurais peut-être du check si la proposition avait pas déjà été soumise, dans ce cas bonne journée à tous !
