### ISSUE TITLE
Rajouter cette chaine youtube pour les cours Java

### ISSUE THREAD

**Issue by adrien1212** [NotANameServer/discord#71]
Chaine Youtube du professeur José Paumard : https://www.youtube.com/channel/UCIatmtIm9z5YEWuHbrUMLsw
Où, on y retrouve des cours pour tout les niveaux

**Comment by SirLynix** [comment]
J'attends des retours des développeurs Java de la communauté pour savoir ce que ça vaut @florentm35

**Comment by SirMishaa** [comment]
Faudrait aussi une partie sur les cours / ressources pour Kotlin ! 

C'est quand même un gros standard quand on n'utilise la JVM, pour combler les lacunes de Java.

**Comment by florentm35** [comment]
> J'attends des retours des développeurs Java de la communauté pour savoir ce que ça vaut @florentm35

J'ai regardé 2-3 vidéos donc pas représentatif du tout, mais le type a l'air de s'y connaitre même si certain truc me fait un peux grincer des dents (typiquement les analogies avec les pointeurs de C/C++), sinon sont format a l'air pas mal fait, il faudrait clairement regarder plus pour avoir un avis



> Faudrait aussi une partie sur les cours / ressources pour Kotlin !
> 
> C'est quand même un gros standard quand on n'utilise la JVM, pour combler les lacunes de Java.

Sauf que ça n'a rien a voir avec l'issue, du coup creer plutot une autre issue en proposant des cours, ça eviteras que ça passe a la trape

**Comment by adrien1212** [comment]
Quelques arguments

**Qui est-il**
- A été Maître de Conférences
- Membre du Java Platform Group
- Java Champion
- Java Rockstar speaker régulier pour Devoxx (FR, BE, UK)

**Les vidéos** (celles que j'ai suivies)
- cours Principes SOLID et Design Patterns
  - Présente les problèmes d'une architecture telle qu'on là réaliserait
  - Présente donc des solutions pour pallier à ces problèmes
  - => Il n'évoque pas juste les principes mais par un jeu de "réflexions" montre comment voir le problème et comment le résoudre logiquement
  - Un fil conducteur au début (qui est par la suite abandonné) 
  - Présentation de certain patron de conception, où de même, il ne présente pas le problème mais montre comment il apparait, comment le reconnaitre pour ensuite appliquer une bonne solution
  - Cours qui a été mis à jour récemment

- JPA et Hibernate
  - De même, cours très bien structuré 
  - Il amène les problèmes et apporte des solutions
  - => apporte une réflexion

- Plein d'autres cours, avec un format assez long (plusieurs heures) pour aborder les différentes notions dans Java

- Les cours sont pour tous les niveaux de ceux qui débutent en programmation JAVA à ceux qui veulent aller plus loin dans ce langage
- 
- On est sur un format "papier". Le professeur n'écrit pas de code sous un IDE, se qui n'ai pas plus mal
   - Pas de données superflues, on reste sur l'essentiel
   - Prise de note manuelle facile grâce à ce format

**Comment by Elanis** [comment]
Up @Iltotore @florentm35

**Comment by Iltotore** [comment]
Merci de m'avoir mentionné, je vois exactement qui c'est. J'adore suivre les JEP Café.

Je vais voir de ce pas à quoi ressemble ses cours.

**Comment by florentm35** [comment]
j'ai déjà fait mon retour un peu plus haut, mais clairement j'aurais pas le temps (et l'envie) de me farcir plus de vidéo.

**Comment by Elanis** [comment]
Merci de ton retour, j'ajoute dans la commande dans ce cas ;)
