### ISSUE TITLE
Salons Projets

### ISSUE THREAD

**Issue by Walimouche** [NotANameServer/discord#72]
Hey, je propose de renommer les salons de projets directement avec leur nom.

Par exemple, le salon s'appellerait
**nazara** et pas *projet-nazara*

Je trouve que c'est assez inutile de mettre projet- dans le nom du salon, sachant qu'ils sont déjà dans une catégorie nommée Projets.

**Comment by SirLynix** [comment]
Effectivement, ça date de l'époque d'avant les catégories et c'est aujourd'hui redondant, je suis pour également.

**Comment by Elanis** [comment]
Ca me semble être une bonne idée oui, c'est vrai que c'est redondant

**Comment by SirMishaa** [comment]
Qu'il en soit ainsi ! !
