### ISSUE TITLE
Ajouter le rôle ping/ne pas ping

### ISSUE THREAD

**Issue by YouStones** [NotANameServer/discord#74]
Cela fait pas mal de temps que je suis sur le serveur, et j'ai déjà eu plusieurs remarque comme quoi il ne fallait pas ping. Hors, par exemple, j'ai personellemnt besoin que l'on me ping pour que je réponde rapidement, puisque je check les serveurs de façon random.

**Comment by SirMishaa** [comment]
![image](https://user-images.githubusercontent.com/42717232/147820615-0538096b-6c68-42c7-a8a7-be5406e84ba6.png)

**Comment by SirMishaa** [comment]
- :bellhop_bell: : **Utilisé pour indiquer aux autres si vous voulez être mentionné quand on vous répond**

**Comment by YouStones** [comment]
oui mais ça n'indique pas si l'on peut ping son interlocuteur, et c'est assez ennuyant de devoir le mettre à chaque message

**Comment by x0rld** [comment]
> oui mais ça n'indique pas si l'on peut ping son interlocuteur, et c'est assez ennuyant de devoir le mettre à chaque message

Les gens te disent de pas ping parceque c'est dans une conversation qui se suit probablement

**Comment by Julien00859** [comment]
Lorsque quelqu'un pose une question et qu'il n'a pas le temps *tout de suite* de regarder les réponses, il met 🛎️ pour signaler qu'il est surement afk et qu'on peut le notifier avec la réponse. Le truc avec "répondre" et les notifications en générale est de permettre de remettre en contexte un sujet qui a été perdu à la suite d'autres conversations. Le plus souvent les noobs pings (explicitement ou par inadvertance via "répondre") alors que leur sujet et leurs interlocuteurs sont clairement identifiés, les notifications sont donc inutiles et envahissantes (surtout lorsque qu'on "répond" au message juste au dessus, ça copie le message pour rien).

Ping n'est pas interdit sur NaN, ce que nous dénonçons régulièrement ce sont les pings inutiles, là où un peu de jugeote permet de comprendre le contexte de chaque message.

Si tu poses une question et que tu veux être notifié avec la réponse, tu ajoutes 🛎️ sur ton message. Si tu poses une question et qu'on t'y répond tout de suite, il n'y a plus besoin de notifier vu que le contexte (le sujet + les interlocuteurs) sont clairement identifiés. Si on te répond (via un ping, plus tard) à ta question mais que tu n'es pas présent à ce moment, il est admit que tu peux ping en retour celui qui t'a répondu lorsque tu auras lu sa réponse.

**Comment by Julien00859** [comment]
Concernant le rôle, l'immense majorité des membres habitués ne veulent *pas* être ping pour rien. D'ailleurs un rôle "ping ok" vs "ping ko" ne servira à rien car les noobs ne respecteront pas le "ping ko".
