### ISSUE TITLE
Des equipes de Developpeurs

### ISSUE THREAD

**Issue by Syplosis** [NotANameServer/discord#75]
Je pense qu'il serait bon de créer des équipes de développeurs capable de réaliser des projets en équipe pour créer du lien,  pour aider des gens qui n'ont pas de compétences dans l'informatique (par exemple créer un site web pour un photographe) ou simplement pour s'entrainer a réaliser une démarche de projet.
Perso je serai hyper partant !

**Comment by Syplosis** [comment]
PS : Mimile#1063

**Comment by Julien00859** [comment]
Salut @Syplosis, il y a déjà pléthore de projets sur NaN tu peux proposer ton propre projet et également rejoindre le projet d'autrui. L'idée est que ce sont les développeurs qui choisissent de monter un projet de nous faire la demande pour avoir un salon associé, ça a été le cas avec Not-a-Hub par exemple, il y a un salon dédié pour discuter de l'écriture d'articles sur notre blog. L'idée n'est pas qu'un client puisse créer un projet et demander à *d'autres* de le développer à sa place. Nous avons toujours refusé être un serveur à petites annonces, lorsque du monde cherche à démarcher activement des développeurs pour des projets non-open-source, ça doit se passer via le salon #offre.

Il est vrai que peu de projets sont fortement actifs, par exemple Not-a-Hub que j'ai cité plus haut n'est plus actif depuis quelques mois.
