### ISSUE TITLE
Renomer #bots-discord en #chatbots

### ISSUE THREAD

**Issue by Julien00859** [NotANameServer/discord#76]
Il y a de plus en plus de discussion sur les chat-bots, du moins dans le salon #python. Ces discussions sont ennuyantes à gérer car systématiquement très spécifique au chat en question, que ce soit telegram, hangout ou encore IRC (je plaide coupable pour IRC). La plupart du temps si s'agit de programmation réseau et/ou d'utilisation d'API web au travers de lib dédiées.

M'est d'avis que ces discussions sont très récurrentes et touchent le même publique que les développeurs de bots discord. Je propose de changer le règlement et le salon pour que toutes les discussions sur les chatbots s'y déroulent. L'intérêt est aussi que #bots-discord soit moins vu comme un salon à part où on "se débarrasse" des noobs, que le salon devienne une vraie section générale.

**Comment by Equinox4** [comment]
Bonne idée, mais je ne sais pas si beaucoup de gens vont faire le lien entre chatbot et bot discord, le fait est que la plupart des questions posées à propos des bots discord le sont par des débutants, donc si il n'y a pas le mot discord dans le nom du canal, je crains que la plupart ne se tournent vers #python ou #javascript encore plus qu'avant.
Néanmoins, à tester.
