### ISSUE TITLE
Modmail - nom channel - bug/feature ...

### ISSUE THREAD

**Issue by andrelec1** [NotANameServer/discord#77]
Mon pseudo est : ` Andrelec1#0001`

![image](https://user-images.githubusercontent.com/3273204/148776284-0cd2b829-1f63-40e6-80ca-eb361ee67277.png)
Le channel modmail ne comporte pas le 1 a la fin de mon pseudo ...

Que ce passe-t-il si un autre utilisateur rejoint le serveur avec le compte `Andrelec2#0001` ou` Andrelec#0001` ?

**Comment by Elanis** [comment]
Il semblerait que le code se limite aux 8 premiers caracteres du pseudo:
https://github.com/DigitalPulseSoftware/NotaBot/blob/master/module_modmail.lua#L398

**Comment by Equinox4** [comment]
Cela provient peut-être d'une limitation sur les ancienne versions de discord, mais actuellement le nom d'un canal est limité à 100 caractères, donc ce code n'a plus lieu d'être (sauf raison que je ne connais pas).
Toutefois, ce serait une sacré coincidence qu'une personne rejoigne le même serveur que toi, avec un pseudo dont les 8 premiers caractères sont identiques, et qui ouvre un ticket en même temps que toi. C'est possible, mais très peu probable.

**Comment by x0rld** [comment]
On peut créer 2 channel avec le même nom dans la même catégorie en soit 
![image](https://user-images.githubusercontent.com/45242856/148787533-077e8fdd-0c29-402a-ae43-a4514290541c.png)

**Comment by SirLynix** [comment]
C'est un comportement parfaitement voulu. La limite de 8 caractères dans le nom du canal est arbitraire (l'idée étant juste que Discord l'affiche en entier). Le nom du canal ne sert qu'à retrouver plus facilement un ticket, mais le bot ne s'en sert à aucun moment (il utilise le snowflake unique du canal à la place).

Et comme répondu plus haut, Discord autorise les doublons dans les noms de canaux

**Comment by andrelec1** [comment]
A ok ,donc le fais que seul le chiffre a la fin de mon pseudo soit tromqué n'est qu'une cohincidence...
Du coup devrais pas y avoir de bug possible la dessus ...
