### ISSUE TITLE
Réorganiser les rôles

### ISSUE THREAD

**Issue by Walimouche** [NotANameServer/discord#78]
Salut à tous (mêmes ceux qui détestent Python) !
Je sais pas si cette suggestion a plus sa place ici ou [chez NaB](https://github.com/DigitalPulseSoftware/notabot) mais vu que c'est plutôt en rapport avec le serveur je suppose que c'est ici.

![image](https://user-images.githubusercontent.com/81018485/149623121-0a5ed0ea-bcd0-4698-9c25-f9ed1ffba1e2.png)

> Ici Lynix dit que l'ordre des rôles est totalement arbitraire est peu changer en fonction du nombre de personnes qui ont un rôle, > j'ai donc eu l'idée d'une p'tite fonctionnalité à ajouter à NaB :

Le bot regarde combien de personne a chaque _rôle de langage_ et plus il y a de personnes qui ont un rôle plus le bot le met haut dans la liste, les rôles les plus donnés seront au dessus, et le rôle assembleur sera tout en bas xD

**Comment by florentmartin35** [comment]
Pour moi ça n'apporterais rien du tout au serveur

**Comment by Equinox4** [comment]
ça servirait à quoi de faire ça ?
de toute façon y a tellement de gens sur le serveur que la liste à droite ne sert à rien, à part pour NaB et le staff (et les nitro boosters, eventuellement).

**Comment by Julien00859** [comment]
Si on devait changer quelque chose ce serait de ne plus séparer les gens part rôle dans la liste de droite. Mais on ne le fera pas parce qu'on s'en fou

**Comment by JeanCASPAR** [comment]
Et en plus, tout le monde préfère que Rust soit en haut 😊

**Comment by pauloud** [comment]
Si on devait s'intéresser à l'ordre des rôles je prescrirais l'inverse : on affiche pour chacun le langage le plus rare qu'il a choisi
