### ISSUE TITLE
Ajout d'une protection anti-suceur

### ISSUE THREAD

**Issue by Tim-ats-d** [NotANameServer/discord#79]
Bonjour à toute la communauté NaN !

INTRODUCTION
=============

C'est ma première issue donc soyez indulgents avec moi, je ne suis pas encore acclimaté à ce milieu très codifié ^^'

DESCRIPTION
============

En tant que membre plutôt actif au sein du serveur, je souhaite apporter ma pierre à l'édifice et proposer mon idée : une protection anti-suceur. En effet, ils sont de plus en plus nombreux à exercer sur le serveur et leur prolifération devient assez gênante (gênant).

EXEMPLE
========

Les membres de cette espèce sont particulièrement présent dans le channel #python et sucent tous la bite à Dr Lazor.

REMERCIEMENT ET CONCLUSION
============================

Voilà, c'est déjà tout pour moi. N'hésitez pas à envoyer du feedback concernant cette proposition, je pense réellement qu'elle pourra améliorer la vie sur le serveur et délester la charge de travail pour les modérateurs.

En bref : merci à tous!

**Comment by Julien00859** [comment]
C'est parce qu'elle est grosse et bien juteuse
