### ISSUE TITLE
Supprimer le canal #infographie

### ISSUE THREAD

**Issue by florentm35** [NotANameServer/discord#80]
Le canal #infographie n'est plus actif du tout, il avait été historiquement créé pour Lolock, mais est depuis longtemps à l'abandon.

De plus avec les canal #html-css + #rendu3d on peux se poser al question de l'utilité de ce canal, potentiellement si il y a vraiment un besoin, voir pour plutôt rediriger les gens vers une communauté dédié

**Comment by Elanis** [comment]
J'ai bien envie de re up' cette demande, les seuls posts du dernier mois dans le channel sont des pubs ou du recrutement ...

**Comment by Nolent** [comment]
Il faudrait faire une annonce pour prévenir les gens de récupérer les messages non ?

**Comment by Elanis** [comment]
Le canal a été supprimé
