### ISSUE TITLE
Ajouter un paragraphe pour "répondre" aux guidelines

### ISSUE THREAD

**Issue by Julien00859** [NotANameServer/discord#85]
Il est fréquent qu'on doivent demander d'éviter de ping à outrance, souvent à cause de "réponse". Ajouter un paragraphe dans les guidelines qui explique en long en large en travers pourquoi c'est chiant et souvent inutile nous permettrait de link le message depuis les guidelines et ne plus avoir à le ré-écrire systématiquement.

**Comment by florentm35** [comment]
ça pourrais être un truc du style :

### Le ping

Eviter d'abuser des pings notamment au niveau des réponses, cela peut être irritant pour la plus part des membres et vous desservir plus qu'autres choses.
Le ping est là pour notifier quelques choses d'important pour l'interlocuteur, il y a de forte chance que votre demande d'aide ne soit pas prioritaire pour celui-ci.
Pour rappel le serveur est là pour l'entraide et est géré par des passionnés bénévoles et vous-même, il ne s'agit pas d'un serveur de SAV.

**Comment by AlphaNow37** [comment]
aussi, il fait préciser d'enlever le ping quand on répond

**Comment by Elanis** [comment]
Il faudra mettre :mention: comme possibilité pour trigger le message 😄

**Comment by Karomy404** [comment]
Depuis que l'on a appris que Shift + Répondre = NoPing , il serait d'utilité publique de crée cette commande afin que notre NAB nationale puisse rependre la bonne parole non ? 
On dit que c'est pas bien que on aime pas et comment faire pour l'éviter :)

**Comment by JeanCASPAR** [comment]
Tu viens de me l'apprendre 😁
Je plussoie l'idée d'une guideline et d'une commande NaB

**Comment by Julien00859** [comment]
Réglé avec #87 cf8827a93836baf75a44ba2f22947b59a1d080a1
