### ISSUE TITLE
Liens utiles

### ISSUE THREAD

**Issue by DrTableBasse** [NotANameServer/discord#88]
Bonsoir ! 

J'ai pensé mais il serait peut être utile d'avoir, par langage, un document ou autre avec des liens utiles. 
Je m'explique, comme vous le savez depuis peu je me lance dans le web et j'aime bien avoir des outils qui me permettent de voir le développement d'une autre façon comme tailwind avec le css. Donc peut être, grâce à la commu et à l'entraide commune, réaliser un document sur les outils, frameworks et lib qui peuvent être utile. 
Bien sûr, on pourrait regrouper ça en catégorie par langage. 
Exemple avec python : 

- interface graphique 
   . lien 1 
   . lien 2 etc
- jeu 

vous avez compris le schéma. Ca permettrait d'avoir une trace car en sachant que mon thread sur le screen que j'avais mis disparaîtra un jour, j'ai peur de perdre pas mal de choses. On va dire que ça me sert de mémo.

**Comment by florentm35** [comment]
Il y a déjà pas mal de chose qui existe sur NaN pour gérer ça, primo en générale dans les message pin dans les salon de langage tu peux retrouver plusieurs ressources, mis par le staff (Modérateur et Ambassadeur), de leur initiative ou à la demande des membres du salon.

Il existe un canal plus spécifique et externe pour les cours (commande !cours sur le discord ou https://www.learndev.info/fr)

Finalement le dernier canal est NotAHub, qui à récemment été mis en place qui est la pour que les membres puisse y publier des articles sur l'informatique, que ce soit des lib cool, des cours perso, ou autres (bon il n'y a pas encore beaucoup de choses dessus).

Donc pas sur qu'il y ai besoin d'un nouveau canal de ressources.

**Comment by DrTableBasse** [comment]
oh pas forcément un nouveau canal, je me suis mal exprimé mais plus une commande et oui je connais déjà learndev mais sait-on jamais. Peut être que cette idée intéressera des gens !

**Comment by florentm35** [comment]
Si tu as des listes de ressources pertinente, tu peux tout à fait les proposer à ton ambassadeur de canal ou via ticket, il pourras être jugé si cela à sa place en message épinglé, voir en commande.

**Comment by JeanCASPAR** [comment]
On a déjà ce genre de listes de ressources épinglée dans #python, mais peut-être que ça pourrait aller sur le site aussi ?

**Comment by Julien00859** [comment]
Les média existent, sous la forme des repo learn-dev (awesome-list) et not-a-hub (blogging), tous les deux open-sources et ouverts aux contributions via github. Il ne s'agit pas d'inventer une nouvelle plateforme, il s'agit de fournir du contenu aux plateformes existantes.
