### ISSUE TITLE
Nouveau émoji sueur

### ISSUE THREAD

**Issue by DrTableBasse** [NotANameServer/discord#89]
J'aime bien ces émojis, ça irait de paires avec le :notlikethis: 

[multisueur](https://cdn.discordapp.com/emojis/798872964979752980.webp?size=128&quality=lossless)

[sueur intensifiée](https://cdn.discordapp.com/emojis/798872965089329152.webp?size=128&quality=lossless)

[sueur](https://cdn.discordapp.com/emojis/798872964854579201.webp?size=128&quality=lossless)

*ce sont les cdn de discord je peux les mettre directement si vous voulez

**Comment by Julien00859** [comment]
+1 pour ajouter juste sueur, il est souvent utilisé pour montrer qu'un sujet est difficile et qu'on éprouve du mal à comprendre. De mon expérience perso les deux autres "multisueur" et "sueur intensifiés" sont juste utilisés par les kikoo pour spam.

**Comment by Elanis** [comment]
Done, j'ai mis :sueur:
