### ISSUE TITLE
Changer !debutant en !nouveau

### ISSUE THREAD

**Issue by Linkkonu** [NotANameServer/discord#91]
Bonjour, le terme « nouveau » serait plus approprié. Il est logique qu'on pense à faire un !nouveau pour un nouveau venu plutôt que !debutant qui est moins logique.

**Comment by Julien00859** [comment]
Je pense plutôt merdre !salenoob :thinking:

**Comment by Elanis** [comment]
Plutôt que changer, je verrais bien un ou plusieurs alias perso. Sinon oui, comme discuté hier sur #discussions, !nouveau serait pas mal aussi

**Comment by florentm35** [comment]
Il y avait déjà eu sinon quelque proposition avec !bienvenue par exemple
![image](https://user-images.githubusercontent.com/31475579/163191366-b6906b0a-c83f-49b1-b576-3e5a6d75aa97.png)

**Comment by Julien00859** [comment]
`!bienvenue` a été ajouté
