### ISSUE TITLE
Ajout command !noasktoask

### ISSUE THREAD

**Issue by andrelec1** [NotANameServer/discord#94]
Ajout d'une command !noasktoask qui link : https://dontasktoask.com/fr/

**Comment by andrelec1** [comment]
Pour moi, ce sont deux choses différentes ...

Le !ask quand la question est incompréhensible.

Et le asktoask quand quelqu'un demande un expert sur une techno sans pose de réelle question.

**Comment by zazbone** [comment]
La commande a plutôt été créé pour les deux cas
Et le modèle de https://dontasktoask.com/fr/ n'a pas été choisis, car un peu agressif
