### ISSUE TITLE
modification du nom de #rôle-test

### ISSUE THREAD

**Issue by x0rld** [NotANameServer/discord#95]
![image](https://user-images.githubusercontent.com/45242856/166255844-161eb6fa-03a9-4156-8447-1992379d8ce1.png)
![image](https://user-images.githubusercontent.com/45242856/166255893-f66ab98a-f6c9-4b00-9cf0-2be8767d9510.png)

est ce que ça serait possible d'enlever l'accent à rôle test parce que c'est pas pratique quand on recherche

**Comment by SirLynix** [comment]
Vraie question : est-ce qu'on ne remettrait pas plutôt des accents à tous les noms de salon ?

**Comment by Julien00859** [comment]
Vu qu'on est déjà tous habitué à ctrl-k sans accent, genre ctrl-k "detente" je pense qu'il est préférable de persister sur l'ascii.

**Comment by JeanCASPAR** [comment]
et c'est relou sur téléphone

**Comment by Elanis** [comment]
Au départ je n'étais pas trop d'accord avec le fait d'enlever les accents, mais je fini par être d'accord, vu qu'il n'y a pas de recherche par accent insensitive (et que ce n'est pas possible simplement côté dev pour discord, c'est normal). Ce serait peut être plus interessant de passer sur roles-test

**Comment by SirLynix** [comment]
C'est fait, par contre il faudra vraiment que je finisse la tâche et qu'on remplace #rejoindre-les-canaux par ce canal.

**Comment by Elanis** [comment]
Yes, je vais créer une autre issue dédiée ;)
