### ISSUE TITLE
Rediriger automatiquement dans un salon

### ISSUE THREAD

**Issue by luc-git** [NotANameServer/discord#98]
Souvent les débutants écrivent des messages dans le mauvais salon. Il pourrait être cool que le bot redirige automatiquement la personne dans le bon salon à l'aide du message, ou quand un autre membre lui indique le bon salon ou avec une commande.

**Comment by Julien00859** [comment]
Le sujet a été déjà adordée dans #64, si je peux te demander de bien vouloir lire les commentaires qui avaient été fait pour l'issue (pas strictement identique à celle-ci je te l'accorde). Je remet mon avis que j'estime pertinent pour cette issue aussi

https://github.com/NotANameServer/discord/issues/64#issuecomment-950625219

> Je suis contre, pour moi il doit y avoir de la part de chaque membre une implication minimale dans chaque serveur discord qu'il rejoint. Dans le cas de NaN il s'agit de lire les règles, les guidelines et savoir utiliser rejoindre-les-canaux. Le type de population qui rejoint le serveur et qui court-circuite ces étapes sont le plus souvent des gens qui ne s'impliquent pas dans le serveur, qui ne sont là que pour qu'on les aide mais qui n'apporteront pas d'aide en retour. Ils mettent une mauvaise ambiance car la plupart des membres vont se contenter de leur répondre !ask ou !code. Le passage minimal par rejoindre-les-canaux rend l'affaire un tantinet plus difficile et permet de filtrer les profils les moins impliqués.
