### ISSUE TITLE
Suppression de Dyno du serveur Discord

### ISSUE THREAD

**Issue by Elanis** [NotANameServer/discord#99]
Dyno est le bot de modération historiquement utilisé sur Not A Name, mais il a tendance à être très instable.

Pour cela, depuis 4 ans est créé et amélioré continuellement Not A Bot. Il manque maintenant peu de features à Not A Bot pour pouvoir complètement retirer Dyno du serveur.

Voici la liste des issues restantes:
<https://github.com/DigitalPulseSoftware/NotaBot/issues/47>
<https://github.com/DigitalPulseSoftware/NotaBot/issues/48>
<https://github.com/DigitalPulseSoftware/NotaBot/issues/49>

**Comment by Elanis** [comment]
Une des trois taches à été traitée par Mjölnir il y a quelques semaines, grace à lui on a un !userinfo tout beau dans NaB. N'hesitez pas à contribuer vous aussi à NaB pour qu'on puisse faire avancer le serveur (même sur d'autres idées que celles là).

**Comment by Julien00859** [comment]
:tada:
